### ISSUE TITLE
How to place IntroJs inline with other page elements

### ISSUE THREAD

**Issue by elektronika-ba** [usablica/intro.js#1002]
I would like to embed IntroJs into the page itself, not to have it over the contents. Is it possible with some hacky CSS to accomplish this?

For example, I have a DIV on my page where I would like to have IntroJs appear and function inside it (inline), while not highlighting nor focusing on any element on the page.

**Comment by doodhJalebi** [comment]
I think you can accomplish that by simply setting the opacity of the overlay to 0 (making it transparent) and allowing interaction outside the focused part. Refer to the [Intro API -> Options](https://introjs.com/docs/intro/options/) for this. For the last part, if you want intro.js to just create tooltips for elements inside a particular `<div>`, just...code it that way.
