### ISSUE TITLE
Shadow Dom Support - Lit Element

### ISSUE THREAD

**Issue by zsarnett** [usablica/intro.js#1005]
## Description

I am looking to integrate IntroJs into my project. I am using Lit Element and Web components. An issue I am encountering is that Intro JS seems to insert the overlays, and layers into the body of the page instead of the current dom. Because the outside dom has no idea what is in the inner doms as well as the other way around this makes it difficult to use. Is it possible to run Intro JS within a Shadow Dom and have it append the created divs inside it?

## Expected Behavior

I expected Intro JS to append its Div elements to the inside of the current shadow dom or allow me to specify which element it should append these elements

## Actual Behavior
Appended Elements to the body of the page

## Errors and Screenshots (optional)
Give us any additional information if you have.

## Example (recommended)
How can someone else see/test this issue?  List the steps or write some code; or create a jsfiddle or codepen.
![image](https://user-images.githubusercontent.com/18730868/82094163-83fa4a80-96ca-11ea-900b-0ba4500cea30.png)

in the image you can see how at the bottom the Introjs elements were inserted into the body but the real element that is step one is located 7 shadow doms deep

**Comment by zsarnett** [comment]
Basically, what I am asking for is do you have something that is similar to Shepard's modalContainer?

`modalContainer An optional container element for the modal. If not set, the modal will be appended to document.body.`

**Comment by zsarnett** [comment]
Not sure if this has been addressed yet

**Comment by zsarnett** [comment]
Not sure if this has been addressed yet

**Comment by zsarnett** [comment]
Shadow Dom is Great!

**Comment by afshinm** [comment]
Hey @zsarnett 

You can use `useRef` and pass the currentNode to Intro.js: https://codesandbox.io/s/introjs-shadow-dom-qr1h0?file=/src/App.js

Intro.js supports both string CSS selector and DOM element.

**Comment by urswilke** [comment]
I was also struggling with this. The problem was that in my case, I have lit elements nested within another lit element. See a small toy example repo [here](https://gitlab.com/urswilke/lit-with-intro.js).
When running introjs after the parent lit element has first updated, the children are not rendered yet. Therefore, I have to wait until the children are also rendered (see [here](https://gitlab.com/urswilke/lit-with-intro.js/-/blob/main/src/my-element.js?ref_type=heads#L9)).
