### ISSUE TITLE
Modal auto scroll not working.

### ISSUE THREAD

**Issue by thiagokernell** [usablica/intro.js#1016]
I'm using modal with introjs, but it doesn't autoscroll when the element is lower

![6177816a-822d-11e4-97cf-2d7ad9e8f60f](https://user-images.githubusercontent.com/58084143/93514447-977a2400-f8fd-11ea-84ec-c0c160e488cf.png)

**Comment by ClevelandWhat** [comment]
im also having the same issue, hopefully someone has an answer for this. I love this tour option its currently the best i could find

**Comment by akshaykumar12527** [comment]
I am also facing the same issue, is there any option available where I can define the parent element in which scroll needs to happen.
