### ISSUE TITLE
css syntex need to be fix from !Important to !important

### ISSUE THREAD

**Issue by vipulism** [usablica/intro.js#1038]
css syntex need to be fix from `!Important` to `!important`

https://github.com/usablica/intro.js/blob/6a23221d23bc853540a211e8736e4fc4a7ff115c/themes/introjs-royal.css#L116

https://github.com/usablica/intro.js/blob/6a23221d23bc853540a211e8736e4fc4a7ff115c/themes/introjs-royal.css#L118

**Comment by davidsneighbour** [comment]
why?

**Comment by vipulism** [comment]
capital `I` in `!Important` is not compatible with all browser

**Comment by vipulism** [comment]
also if any once want to concatenate this css with their one it will throw error
