### ISSUE TITLE
introJs('.some-class-name').start() does not select any element

### ISSUE THREAD

**Issue by janroesner** [usablica/intro.js#104]
I'm using 0.3.0 in a single page application. Since I need different help items in every view, I gave every item a class per page, so that .start() should only open the relevant items following your documentation. 

If I do so and for example call: 

```
introJs('.intro-foo').start()
```

with two elements in the active view like:

```
<div class="some-class intro-foo" data-intro="some text" data-step="1">
<div class="other-class intro-foo" data-intro="some other text" data-step="2">
```

nothing is opening at all. If I omit the classnames like:

```
introJs().start()
```

every item shows up, even those which I'd like to filter. Is that a known issue in 0.3.0?

**Comment by vanjor** [comment]
by refer from issue: https://github.com/usablica/intro.js/issues/69
we could using following function:

introJs().setOptions({groupClass:'.intro-foo'}).start();
