### ISSUE TITLE
TypeError pressing right arrow key in latest step

### ISSUE THREAD

**Issue by mondeja** [usablica/intro.js#1051]
## Description
When I press the right arrow key in lastest step the library throws next error:

```
Uncaught TypeError: nextStep is undefined
    nextStep intro.js:1348
    onKeyDown intro.js:1445
    handler intro.js:160
    on intro.js:164
    introForElement intro.js:2235
    start intro.js:2400
```

## Expected Behavior
Nothing to do because is the latest step.

## Actual Behavior
Raises `TypeError`

## Environment (optional)
intro.js v3.0.1

**Comment by afshinm** [comment]
@mondeja can you share your code please?

**Comment by mondeja** [comment]
No, it's part of a privative application and very large, using other libraries and internal dependencies of the project. The key handling part to advance steps is managed entirely by `intro.js`, we are not using nothing more. Sorry it's all i can tell you.

**Comment by RoyXun** [comment]
Here is a demo: https://codepen.io/Xun/pen/eYzqZzR?editors=1010

Open the chrome devtools and navigate with keyboard. It will throw an error when we are at the end of the tour.

There was a closed PR :https://github.com/usablica/intro.js/pull/962, which was not merged.
