### ISSUE TITLE
no dist folder and intro.js in the source.zip file

### ISSUE THREAD

**Issue by hardsun-cn** [usablica/intro.js#1071]
no "dist" folder and intro.js in the  source.zip file of the latest release.
https://github.com/usablica/intro.js/releases

and also there's no such folder in "code":
https://github.com/usablica/intro.js

could you please check it?

**Comment by afshinm** [comment]
@hardsun-cn you are right @hardsun-cn. I have removed the `dist` folder from GitHub releases but you can download the source code and follow the manual to build the code. Alternatively, you can download the compiled files from https://unpkg.com/browse/intro.js@3.0.1.
