### ISSUE TITLE
How does introjs jump from the first step to the nth step （skip button click）

### ISSUE THREAD

**Issue by zhenujt** [usablica/intro.js#1103]
## Description
Can't jump from the first step to the fourth step

## Expected Behavior
Hope there is corresponding api support, or I did not find an existing api

## Actual Behavior
Can't jump from the first step to the fourth step
## Environment (optional)
window chrome introjs v3.1.0 React

**Comment by afshinm** [comment]
You can use https://introjs.com/docs/intro/api#introjsgotostepstep
