### ISSUE TITLE
Skip button missing?

### ISSUE THREAD

**Issue by micrology** [usablica/intro.js#1104]
## Description
In a previous version, the first step showed two buttons, Skip and Next.  The current version show Back (inactive) and Next

## Expected Behavior
The first step should show a Skip button for those who don't want to work through the Intro

## Actual Behavior
No Skip button, only an inactive (and useless) Back button

## Example (recommended)
See https://introjs.com/example/hello-world/index.html as an example of this

## Environment (optional)
Chrome v87, Javascript, no frameworks

**Comment by ZsharE** [comment]
Also the **Done** button is missing when there is just one step.
You could copy / paste this in the console on https://introjs.com/ for demo:
```
introJs().setOptions({
    steps: [{
        intro: "Some test message here"
    }]
}).start();
```

**Comment by ZsharE** [comment]
Same problem here, any solution ?

**Comment by afshinm** [comment]
The skip button has been replaced with a close "x" button since v3. The close "x" still triggers the same events, etc. but visually, it has been changed a bit.

**Comment by micrology** [comment]
Can we have the Skip button back, please, at least as an option?

**Comment by micrology** [comment]
Even if the Skip button is lost, it still doesn't make much sense to have an inactive Back button on the first step.  It's just visual clutter.  So my ideal solution would be to replace the inactive Back button with an active Skip button (it doesn't matter that there is also a close x that has the same effect), and my alternative, second best, solution would be to remove the Back button entirely.

**Comment by afshinm** [comment]
@micrology sure, you can use the `hidePrev` option to hide the back button: https://introjs.com/docs/intro/options#hideprev

**Comment by Evilscaught** [comment]
[The website guides still show the classic skip button. ](https://introjs.com/docs/themes/list)

<img width="859" height="425" alt="Image" src="https://github.com/user-attachments/assets/6ecaff56-9552-4dd6-818f-5624e97715d6" />
