### ISSUE TITLE
How to enable input datetime interaction with introJs ?

### ISSUE THREAD

**Issue by bastien70** [usablica/intro.js#1120]
## Description
I am using IntroJs to make a tutorial to help the user complete a form, step by step.

In one step, it has to fill in a datetime field (I use the flatpickr library for this). Except that the calendar is hidden by introJs, preventing the user from selecting their date

## Expected Behavior
I want the user to be able to select their date in the field, while keeping introJs open.

## Errors and Screenshots (optional)
![image](https://user-images.githubusercontent.com/53140475/102336264-3f50cd80-3f91-11eb-88d2-6e2fe93893a1.png)

## Example (recommended)
https://jsfiddle.net/kiuega/x1u5b204/12/

In the example, the introJs tooltip hides the calendar that we are trying to display a bit, but that's okay, that's not the problem, although the 'position' option doesn't work, but that's it. is another problem.

Just click on the field to display the calendar, and see for yourself that you cannot select a value

## Environment (optional)
Symfony v5.2.0
IntroJs v3.1.0

**Comment by ZsharE** [comment]
Don't know if it helps, but try this in your application:

`$("#my_date").flatpickr({ static: true });`

**Comment by bastien70** [comment]
Yes thank you it works great !
