### ISSUE TITLE
Overlay problem with my element on my navbar with intro.js

### ISSUE THREAD

**Issue by bastien70** [usablica/intro.js#1128]
## Description
When Intro.js takes a step on an element of my page, there is an index problem with respect to my navbar, which I don't normally have.

```scss
.navbar {
  overflow: visible;
  height: 70px;
  z-index: 9999;
}
```

## Without intro.js

![image](https://user-images.githubusercontent.com/53140475/102998396-6413ea80-4527-11eb-87d3-86ff6a5c59fb.png)

No problem with superimposing the content of my page on my navbar

## With intro.js

![image](https://user-images.githubusercontent.com/53140475/102998492-84dc4000-4527-11eb-8ce3-b3a6b2c4f414.png)

Element overlaps my navbar

## Expected Behavior
The goal would be that when intro.js points to a DOM element, that there isn't this kind of problem with the element overlapping my navbar.

## Environment (optional)
Symfony v5.2.0
Intro.js v3.2.1

**Comment by f5cs** [comment]
in function placeTooltip,go to this line switch (currentTooltipPosition) {,then insert the code before:arrowLayer.style.left = null;
find case: "top-middle-aligned",change the logic to:
        arrowLayer.className = "introjs-arrow bottom-middle";
        var tooltipLayerStyleLeftRight = targetOffset.width / 2 - tooltipOffset.width / 2; // a fix for middle aligned hints
	
		var left = (windowSize.width - tooltipOffset.width)/2;
		
		if(tooltipOffset.left > left){
			left = left - tooltipOffset.left;
		}else{
			left = tooltipOffset.left - left;
		}
		
		
        if (hintMode) {
          tooltipLayerStyleLeftRight += 5;
        }

        if (checkLeft(targetOffset, tooltipLayerStyleLeftRight, tooltipOffset, tooltipLayer)) {
          tooltipLayer.style.right = null;
          checkRight(targetOffset, tooltipLayerStyleLeftRight, tooltipOffset, windowSize, tooltipLayer);
        }
		
		arrowLayer.style.left = targetOffset.left - targetOffset.width * 1.5 - 5 + 'px';
		tooltipLayer.style.left = "".concat(left, "px");
	
        tooltipLayer.style.bottom = "".concat(targetOffset.height + 20, "px");

**Comment by f5cs** [comment]
in the other case: "top-middle-aligned", user the similar solution.

**Comment by afshinm** [comment]
Try to disable element interaction, example: https://introjs.com/docs/examples/customizing/disable-interaction
