### ISSUE TITLE
Intro.js highlight not working in material ui dialog

### ISSUE THREAD

**Issue by nlafleur** [usablica/intro.js#1134]
## Description
div is not highlighted inside material ui dialog, the stepper does point to the correct div.

## Expected Behavior
I made the following image in photoshop;
![image](https://user-images.githubusercontent.com/40174298/103654204-db08a480-4f65-11eb-89ab-8209d2c13792.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/40174298/103654257-ecea4780-4f65-11eb-930f-edb9f61c089d.png)

For some reason the div with the class 'step2' is not highlighted.
I tried to give the parent an higher z-index, this brings the dialog to the front but "highlights" the whole dialog and makes the backdrop useless, when u click next to the dialog it closes the dialog instead of firing the intro.js his backdropclick function.
(like: ![image](https://user-images.githubusercontent.com/40174298/103654345-0a1f1600-4f66-11eb-92cf-5e18d5e72986.png))
> after the backdrop click; ![image](https://user-images.githubusercontent.com/40174298/103654404-1efba980-4f66-11eb-82fa-b40037864ac1.png)

![image](https://user-images.githubusercontent.com/40174298/103655076-093ab400-4f67-11eb-95e8-8ab7cebe7d0c.png)

## Environment
Browser: Google Chrome,
"@material-ui/core": "^4.11.0",
"intro.js": "3.2.1",
"intro.js-react": "^0.2.0",
"react": "^16.12.0",

**Comment by afshinm** [comment]
Intro.js cannot listen/close the modal when the popup is closed. This is your responsibility to close the Intro.js (using the exit() function) once the modal is closed.

Also, try to use the introjs.refresh() button once your popup is fully rendered: https://introjs.com/docs/hints/api#introjsrefresh -- this function forces Intro.js to find the target css selectors again and re-render the helpers.
