### ISSUE TITLE
Keeps Showing After First Tour

### ISSUE THREAD

**Issue by samkarpenter** [usablica/intro.js#1146]
Dear community. I am new to programming (sorry if this is too simple).

The tour keeps showing every time someone visits that particular page. Is there a way to remember that the visitor clicked on the tour once and stop showing the tour after the first time user interacts with it?

Thank you.

**Comment by vincentRaiffe** [comment]
Hi, 
I think the solution is to store the information either on the user machine (with local storage or setting a  specific cookie) but if the user erase his cookies he would go through the intro again,  or either store the data in your BDD (the best method in my opinion).

**Comment by samkarpenter** [comment]
Thank you very much for the response. The second option is definitely great. May I ask if you could suggest how could I do that? I would really appreciate your help with this. 

Either way, thank you in advance.

**Comment by vincentRaiffe** [comment]
In my project, I use ajax before the function intro.js. I check if the user has already watched the intro (with a boolean). If I get true, I do nothing, if false I update the user profile and launch the function with intro.js  

` jQuery(document).ready(function () {
        $.ajax({
            url: 'getIntro',
            type: 'GET',
            success: function (data) {
                if (data == false) {
                    startIntro();
                }
            }
        })
    });`

the function startIntro has the options and the start for the intro.

The php function who check the boolean: 
`public function getIntro(Request $request)
    {
        $user = $this->getUser();
        $intro = null;

        if ($request->isXmlHttpRequest()) {
            $intro = $user->isIntro();;
            if ($intro == false) {
                $em = $this->getDoctrine()->getManager();

                $user->setIntro(true);
                $em->persist($user);
                $em->flush();
            }
        }
        return new Response($intro);

    }`
