### ISSUE TITLE
Positioning breaks when passing relatively-positioned element to introJs() to limit the presentation section 

### ISSUE THREAD

**Issue by bendavis78** [usablica/intro.js#1147]
If I use introJs on a relatively positioned section (or has a relatively positioned parent), the positioning of the helper layer will be incorrect:

```javascript
introJs('.my-relative-el').start()
```

This is because positioning is determined using `getBoundingClientRect()`, which is relative to the viewport. However, the top/left properties are relative to the parent target element because the helper layer is appended to that target element.

**Comment by afshinm** [comment]
Thanks @bendavis78 -- can you send us an online example (jsfiddle, codesandbox, etc) please?

**Comment by bendavis78** [comment]
Sorry for the late reply, here is a jsfiddle demonstrating the issue:

https://jsfiddle.net/opkjfvw4/27/

**Comment by rr222cy** [comment]
Just installed intro.js into a new project using a sidebar navigation menu and experiencing the same issue due to relatively-positioning. Would be great if @bendavis78 fix could be accepted :) @afshinm

**Comment by fantypants** [comment]
is this the same as https://github.com/usablica/intro.js/issues/855 ?

**Comment by bendavis78** [comment]
@fantypants possibly -- you might want to check out this branch to see if it fixes your issue: https://github.com/BoldIdeaInc/intro.js/commits/issue-1147

**Comment by bendavis78** [comment]
@afshinm can you remove the "question label"? Were you able to see the jsfiddle or review the PR?
