### ISSUE TITLE
Dropdown Issue

### ISSUE THREAD

**Issue by alanish08** [usablica/intro.js#1150]
## Description
Dropdown comes below the selected element and not clickable

## Errors and Screenshots (optional)
![image](https://user-images.githubusercontent.com/67004803/106262870-9eb92300-6249-11eb-8617-16481a8e4cb8.png)

  introJs().setOptions({
                    steps: [
                        {
                            element: '#panel1',
                            intro: 'Enter a name for your list for future reference',
                            position: 'left',
                        },
                        {
                            element: '#panel2',
                            intro: 'Click here to upload a list, or drag and drop a list from your computer. While you\'re in trial mode, you can test the outreach with up to 5 phone numbers. Make sure you’ve obtained consent before you reach out to them, and are aware they’ll be receiving messages!',
                            position: 'left',
                        },
                        {
                            element: '.panel3',
                            intro: 'Click here to create a new campaign.',
                            position: 'left',                            
                        },
                        {
                            element: '#panel4',
                            intro: 'Upload your list!',
                            position: 'left',
                        }
                    ],
                    exitOnOverlayClick : false,
                    showStepNumbers : true,
                    // overlayOpacity : 0,
                    // showProgress: true,
                    })
                        .onbeforeexit(function () {
                                localStorage.setItem("listUploadTour", 0)
                            }).start()
                        }
                    }

**Comment by afshinm** [comment]
This is probably because the parent element has position: absolute, fixed or relative.
