### ISSUE TITLE
IntroJs steps that display on the right side of the screen are partially off screen

### ISSUE THREAD

**Issue by markgonz** [usablica/intro.js#1169]
## Description
I am using introJS in an app and any steps that are near the right side of the screen display partially off-screen. I have tried setting position to auto, left, right, etc, but this item always appears this way (the other "steps' appear within the window). Alternatively, I would consider just having all the tooltips be centered and have the element highlighted as usual, but I am not sure this is an option. 

## Errors and Screenshots (optional)
<img width="475" alt="off screen step" src="https://user-images.githubusercontent.com/7225854/108085802-b531ed80-7043-11eb-9726-d8e98ae2f562.png">

## Environment (optional)
Intro.js v3.3.1, IONIC 5

**Comment by tjhunkin** [comment]
Same here whilst creating a responsive web app

**Comment by markgonz** [comment]
Any word on this? Or the PR with the fix here: #1153

**Comment by afshinm** [comment]
Merged.
