### ISSUE TITLE
callbacks are a bit confusing

### ISSUE THREAD

**Issue by Aerlinger** [usablica/intro.js#117]
There should be a better reference be an example for how to use the callbacks (I know there was an earlier thread about this). What I'm referring to is the odd behavior of callbacks returning a introJs object reference with the bound callback. However, this is much different than most existing standards (e.g. DOM methods, jQuery, etc) where the callback is bound the original object. For instance, my initial assumption was that it worked like this:

```introJs.onchange(function(targetElement) {
  // something here
});

introJs().start();```

But this doesn't work and there's no documentation on what an effective implementation is.

**Comment by danielgolden** [comment]
I actually couldn't get these callbacks functioning properly until I read through this thread. I agree with @Aerlinger, the documentation is confusing about this.
