### ISSUE TITLE
using document.querySelector to select parent and child elements with intro.js

### ISSUE THREAD

**Issue by PeterPilley** [usablica/intro.js#1189]
## Description
I setting up intro.js for some of our services. we are using document.querySelector('[class]')[0] to successfully use specific areas on the page. What we are trying to do is use a child of this element.

I am trying the following

document.querySelector('[class] >div:first-child') which in javascript works fine, but in intro.js it is not resulting in the correct element being selected. 

## Expected Behavior
I was hoping to be able to dynamically assign an step to an element, hopefully I am just selecting the elements incorrectly

## Actual Behavior
It defaulted to a centre page view

## Errors and Screenshots (optional)
Give us any additional information if you have.

## Example (recommended)
to recreate
html page -> <div class='intro-test'><div></div></div>

Javascript
document.querySelector('.intro-test')[0] -> will highlight the div
document.querySelector('.intro-test >div:first-child') -> will highlight the first child

Intro.js
```
var Steps = [
  {
    element: document.querySelectorAll('.intro-test')[0],
    intro: 'Step 1',
    position: 'bottom'
  },
  {
    element: document.querySelector('.intro-test >div:first-child'),
    intro: 'Step 2',
    position: 'bottom'
  }
]
```

```
$(document).on('click','#help',function(){
  // initialize an introjs instance
  var intro = introJs();

  // pass in the Steps array created earlier
  intro.setOptions({steps: Steps });

  // start intro.js
  intro.start();

})
```
## Environment (optional)
intro.js via cdn link
jquery latest

**Comment by afshinm** [comment]
Is your element available in DOM when you call introjs.start()? Can you create a simple jsFiddle to reproduce the issue?

**Comment by PeterPilley** [comment]
Yep will do
