### ISSUE TITLE
start and stop position of data step

### ISSUE THREAD

**Issue by ajitkparida** [usablica/intro.js#120]
can we give a start and stop position like we use "introJs().goToStep(2).start();" 

we need something like introJs().startStopStep(2,5).start();
the demo will started from step 2 and stop when it reach to step 5

**Comment by mnts26** [comment]
Hello.

Now can i use stop function ?

**Comment by jonnyparris** [comment]
+1 - If anyone knows a way to stop after a certain step then please share!

**Comment by bozdoz** [comment]
@jonnyparris Can you do `intro.exit()` after a step has been reached, programmatically?
