### ISSUE TITLE
Intro.js v3.2.1 static positioned parent + scrolled window will result highlight box in wrong position

### ISSUE THREAD

**Issue by reigokyngas** [usablica/intro.js#1204]
![pilt](https://user-images.githubusercontent.com/42967042/113997882-3a29ce00-9861-11eb-9733-42e2e8f1d43e.png)

In added picture menu is statically positioned and (Re) Reeno should be highlighted but instread highlight box is located below right position and it seems exactly the same amount as the scrollposition.

For workaround I added window.scrollTo(0,0); before step and this fixed the issue for me for now. Page html is availiable on weekdone.com (registration required).

**Comment by firashamila33** [comment]
+1

**Comment by afshinm** [comment]
@reigokyngas I wasn't able to reproduce this bug. Could you create an online demo on codesandbox/jsfiddle please?
