### ISSUE TITLE
Dynamic theming

### ISSUE THREAD

**Issue by ash0x0** [usablica/intro.js#1218]
## Description
Dynamic theming don't work and dark themes with the default stylesheet don't follow global style.

## Expected Behavior
When the application offers the option to switch between light and dark themes, the intro.js tooltip should follow the global theme and inherit background from the theme.

## Actual Behavior
When the theme is switched from light to dark, the tooltip body color doesn't change but the text color changes, which produces white text on white background with dark themes.

## Errors and Screenshots
Light theme:
![whiteTheme](https://user-images.githubusercontent.com/12426718/116067750-c0c81300-a689-11eb-96a7-1b5ba2c4885e.png)
Dark theme:
![darktheme](https://user-images.githubusercontent.com/12426718/116067779-c887b780-a689-11eb-8bbd-9eea93ad3e4a.png)

## Example
Simply try the tooltip in any dark theme application with the default css sheet.

For now, the workaround I found is to just force the text color to black using options, in react:
```css
.customTooltip * {
  color: #000000;
}
```
```js
<Steps
  options={{
    tooltipClass: 'customTooltip',
  }}
  ...
/>
```
This works for both dark and white themes as the body color never actually turns dark so it's always black text on dark background. This however does not address the dynamic theming issue and doesn't make the tooltip follow theme.

## Environment
React with [intro.js-react](https://github.com/HiDeoo/intro.js-react) and [material-ui](https://material-ui.com/) styling and theming.

**Comment by afshinm** [comment]
Thanks @ash0x0. How did you apply the theme?

**Comment by ash0x0** [comment]
@afshinm Apologies, I missed your question. I'm using material-ui [theming](https://material-ui.com/customization/theming/). Here's how it's applied:
```js
import React, { useEffect, useMemo, useState } from 'react';
import CssBaseline from '@material-ui/core/CssBaseline';
import { createMuiTheme, ThemeProvider } from '@material-ui/core';
import { blue } from '@material-ui/core/colors';
import ReactDOM from 'react-dom';
const { ipcRenderer } = window.require('electron');

import App from './app/App';

import 'fontsource-roboto';
import 'intro.js/introjs.css';
import './index.css';

function Index() {
  const [selectedTheme, setSelectedTheme] = useState(defaultTheme);

  useEffect(() => {
    const themeListener = (event, args) => {
      setSelectedTheme(args.theme);
    };

    ipcRenderer.on('theme_selection', themeListener);

    return () => {
      ipcRenderer.removeListener('theme_selection', themeListener);
    };
  }, []);

  const theme = useMemo(
    () =>
      createMuiTheme({
        palette: {
          primary: blue,
          type: selectedTheme,
          background: {
            default: selectedTheme === 'light' ? '#E0E0E0' : '#303030',
          },
        },
        overrides: {
          MuiCssBaseline: {
            '@global': {
              html: {
                WebkitFontSmoothing: 'auto',
              },
            },
          },
          MuiSelected: {
            color: 'red',
            backgroundColor: 'red',
          },
        },
      }),
    [selectedTheme]
  );

  return (
    <React.StrictMode>
        <ThemeProvider theme={theme}>
            <App />
        </ThemeProvider>
    </React.StrictMode>
  );
}

ReactDOM.render(<Index />, document.getElementById('root'));
```

The way I've found to change the background of the introjs box is by changing the background color for css `html` or `root` elements.
material-ui doesn't update that dynamically. I'd consider my usecase niche to material but my question is how the background for the introjs is applied and if we can feasibly change it to follow something compatible with material-ui, and probably ant as well though I haven't tried ant.
