### ISSUE TITLE
Separate content + HTML

### ISSUE THREAD

**Issue by alvarotrigo** [usablica/intro.js#122]
First of all, great plugin dude! Keep going with it! Is quite smart and modern.

Now. I would recommend to separate the content of the plugin from the the content of the site.

If you take a look for example at "joyride" plugin, they do a list with all the information needed for the plugin to work.
This way the content of the site will still being clean and untouchable and the jQuery plugin content apart. 

This is also good in case i want to add a very big text or explanation (or even with HTML content like lists, bold...etc), which is not that simple to do it in an attribute (and is also quite ugly).

I comment this because is the problem I have just found trying to apply it and which probably will make me take another way right now.

**Comment by rizqinizamil** [comment]
Is <code>data-class</code> / <code>data-id</code> still can be used in current version?
