### ISSUE TITLE
Width of introjs-helperLayer and introjs-tooltipReferenceLayer

### ISSUE THREAD

**Issue by abijotgupta** [usablica/intro.js#1236]
## Description
The width of these layers is about 5 px greater than the original bounding box of the element.
Is it possible to set the width to the exact size of the data-step/data-intro element by using npm package?

If possible, then how can I do that? 
Help me in sorting out this @afshinm

**Comment by afshinm** [comment]
Please fill out the issue template and/or provide an online example/screenshots.

**Comment by Livijn** [comment]
I was having this issue as well so I deep dove the code and found out that you can disable this behavior with the `helperElementPadding` option.
