### ISSUE TITLE
exitonoverlayclick not working

### ISSUE THREAD

**Issue by tuannt777** [usablica/intro.js#1242]
Hi all, I use the option 'exitonoverlayclick  = true' to exit as soon as the user clicks outside, however it doesn't run
Please help me
Code:

> let options = {
                        'tooltipPosition': 'right',
                        'doneLabel': 'Đã hiểu',
                        'showBullets': false,
                        'showStepNumbers': false,
                        'exitOnOverlayClick': true,
                        steps: [
                            {element: ".intro-search-cv", intro: 'Teset'},
                        ]
                    }
                    introJs().setOptions(options).start();
                    localStorage.setItem('search_cv_popup_state', 'shown');

**Comment by afshinm** [comment]
Please provide an online example/screenshot.
