### ISSUE TITLE
Ability to confirm before exiting the guide

### ISSUE THREAD

**Issue by drgomesp** [usablica/intro.js#125]
Is there a way to fire a confirmation popup on the exit action?

I see this being implemented inside a `onbeforeexit` callback, which the API currently doesn't support.

**Comment by kotmatpockuh** [comment]
so did you do that?

**Comment by russellmann** [comment]
It's a good question. :)

**Comment by pydolan** [comment]
@afshinm -- why was this closed with no response? I also suggest adding this feature.

**Comment by afshinm** [comment]
sure, sorry for closing it (not sure why I did that). I will add to the next version.

**Comment by afshinm** [comment]
Added to 2.7.0
