### ISSUE TITLE
Tour across different pages in vue-application / refresh not working?

### ISSUE THREAD

**Issue by iparker** [usablica/intro.js#1251]
Hello,

I'm trying to implement a simple tour inside a vue/nuxt application. I use https://github.com/alex-oleshkevich/vue-introjs to get introjs running and it seems that everything is working fine.

But I wonder how I can make a tour across different pages in my spa?

When the tour starts on one page everything seems fine. But when I click on an link/element and another page/content is loaded inside the spa it seems that introjs is not able to find these new elements.

I tried to add an intro.refresh() in an onbeforechange-callback and also in the mounted of the next loaded page - but this does not work.

How can I solve this? Do I miss anything? Is there a way to do something like a refresh? I hoped that the refresh handles this but this does not work.

Thanks for some help with this!

Best regards,

Timo

**Comment by afshinm** [comment]
Try calling `introjs.refresh()`: https://introjs.com/docs/hints/api#introjsrefresh on your next page (right after navigating to the new page) and see if it helps?

**Comment by iparker** [comment]
Thanks for your reply! I tried it but unfortunately it is not working.

```
mounted() {
      console.log('intro refresh in myData mounted');
      this.$intro().refresh();
    },
```

Maybe I did something wrong. But it seems that this isn't a good approach to split the tour logic across different components.

**Comment by afshinm** [comment]
Right, I'm not entirely sure how Vue.js navigation/routing works but Intro.js scans for all available element on the page after calling the refresh() function. So my only suggestion is to make sure your target elements are actually fully rendered before calling the refresh() function.
