### ISSUE TITLE
Callback for when the user skips

### ISSUE THREAD

**Issue by mwagg** [usablica/intro.js#128]
It'd be useful to have a callback specifically for when the user skips the intro.

**Comment by andela-oagunbiade** [comment]
A easy work-around would be to update your database once the tour gets started without the use of the `oncomplete` event. I used something like this:
 `if (xxxxxxxxxx && !currentUser.takenTour) {
     introJs().start();
    Accounts.update({_id: Meteor.userId()}, {$set: {takenTour: true}});
  }`
