### ISSUE TITLE
use introjs with storybook 6

### ISSUE THREAD

**Issue by parisabrz** [usablica/intro.js#1281]
hi guys,
im using storybook in my app, when i open intro component in storybook, it show the intro box in wrong place, please help me im need it
آقای افشین مهربانی ممنونم از اینکه این ماژول به این خوبی رو کد زدین، لطفا کمکم کنین چون توی استوری بوک جای اشتباه نشون میده
React, storybook 6

**Comment by afshinm** [comment]
Please provide your code, the error that you're seeing, etc. I can't unfortunately help without those details.
