### ISSUE TITLE
tooltipLayer undefiend when resize window size after call `Introjs().exit()` 

### ISSUE THREAD

**Issue by 0721Betty** [usablica/intro.js#1282]
## Description
resize window size after call `Introjs().exit()`

## Expected Behavior
no issue

## Actual Behavior
![image](https://user-images.githubusercontent.com/48433973/120463982-02f21c00-c3cf-11eb-95f9-c404999557fa.png)

## Errors and Screenshots (optional)
![image](https://user-images.githubusercontent.com/48433973/120464461-8875cc00-c3cf-11eb-8faf-847d9394354d.png)

![image](https://user-images.githubusercontent.com/48433973/120464331-62502c00-c3cf-11eb-8503-fbdeb6d61871.png)

![image](https://user-images.githubusercontent.com/48433973/120464557-a6433100-c3cf-11eb-80a6-fac849a468e0.png)

## Environment (optional)
chorme, introjs: ^2.9.3, mac system, vue

**Comment by 0721Betty** [comment]
If I add the code circled in the screenshots，it will not report an error
![image](https://user-images.githubusercontent.com/48433973/120594129-0ccd5b00-c473-11eb-8921-b6475b765430.png)

**Comment by 0721Betty** [comment]
The latest version ^3.4.0 has the same error

**Comment by afshinm** [comment]
I was not able to reproduce this. I ran introJs.start(), then introJs.exit() and resized the window but didn't get the same error.
