### ISSUE TITLE
onbeforechange should allow you to skip that step

### ISSUE THREAD

**Issue by jherman** [usablica/intro.js#1293]
The callback here should return a bool that indicates whether to skip that step. In my use case, my intro may be different based on a user's access rights. So some navigation elements may not exist for that particular user. I can detect that on the callback for onbeforechange, but I can't tell it to skip that step if that element doesn't exist.

**Comment by afshinm** [comment]
could you send your Introjs config + your HTML?

**Comment by jherman** [comment]
Just looked at the code. Looks like it does accept a boolean as return type to cancel the call. I was just going off the documentation, so perhaps the documentation just needs to be updated:

```
introJs.onbeforechange(providedCallback)#
Given callback function will be called before starting a new step of introduction. The callback function receives the element of the new step as an argument.

Parameters:

providedCallback : Function
Returns:

introJs object.
Example:
...
```
