### ISSUE TITLE
After scroll the fixed element position is not correct

### ISSUE THREAD

**Issue by stonehank** [usablica/intro.js#1344]
## Description
If introduce button in the fixed element, after screen scroll, the position is **not correct**

## Expected Behavior
The introduce box should be at the `Sample button` position

## Actual Behavior
![1](https://user-images.githubusercontent.com/26397640/126607755-32a78da6-afe9-43bf-acd0-20c9a06d4f56.png)

## Example (recommended)
[code sandbox](https://codesandbox.io/s/intro-demo-bo23t?file=/index.html)

click the `detect button`

```js
function detect() {
  window.scrollTo({
    top: 200
  });
  setTimeout(() => {
    introJs()
      .setOptions({
        steps: [
          {
            intro: "Hello world",
            element: ".nav-button"
          }
        ]
      })
      .start();
  }, 500);
}
```

**Comment by margielm** [comment]
we are having exactly same issue.

**Comment by qweluke** [comment]
I have exactly same issue

**Comment by margielm** [comment]
we wanted to go with commercial license, so I've sent an email to support@introjs.com last week - but no feedback. 
This issue is a blocker for us, so if we wont get any solution we will have to move to https://shepherdjs.dev/ which is handling fixed elements correctly.
https://codesandbox.io/s/intro-demo-forked-n6uoi

**Comment by afshinm** [comment]
I just opened this PR https://github.com/usablica/intro.js/pull/1374/files and added a couple of tests. Could someone please test this patch and let me know if it works for you? I'm happy to publish a new version asap. cc @margielm @qweluke @stonehank

**Comment by margielm** [comment]
@afshinm , unfortunately the fix didnt work for me. 
![image](https://user-images.githubusercontent.com/684828/129686209-d8e23b6c-977b-46b8-9f6b-a4926897d9cb.png)

**Comment by afshinm** [comment]
@margielm how did you build the branch? Could you create a codesandbox for me please?

**Comment by margielm** [comment]
I did build from the branch. and I do see the added code in my project. But there is a possibility that I am doing something wrong about that. 
Will try to create codesandbox.

**Comment by margielm** [comment]
@afshinm , here you go:
https://codesandbox.io/s/intro-demo-forked-n6uoi

just scroll and launch introjs:

![image](https://user-images.githubusercontent.com/684828/129699667-056f640b-1111-420e-b66d-cbe049aba980.png)

**Comment by afshinm** [comment]
Right, thanks for confirming @margielm. I will send another patch in a few mins.

**Comment by afshinm** [comment]
@margielm just pushed another change + a test to check when the parent is also fixed. Could you please have a look?

**Comment by margielm** [comment]
@afshinm , I have tried in sandbox and our project and in both places in is working fine
Thank you!

**Comment by afshinm** [comment]
@margielm sorry for the delay. Please install 4.2.2.
