### ISSUE TITLE
How to continue and make two way (branch)

### ISSUE THREAD

**Issue by rmalenko** [usablica/intro.js#137]
Hi!

Help me please.

First step is sign in. After user have filled up form and have pushed button he will come to his profile where I wish to continue display guide.

I use this code for star at first page:

```
<script type="text/javascript">
      document.getElementById('startbuttontutor').onclick = function() {
        introJs().setOption('doneLabel', 'Next page').start().oncomplete(function() {
          window.location.href = 'profile_view';
        });
      };
</script>

<a id="startbuttontutor" href="javascript:void(0);"><?php echo __('step_one'); ?></li>

<form id="login_form" action=... class="login" method="POST" data-step="1" data-intro="...">

```

At next page profile_view intro isn't start and display. I use this code:

```
<script type="text/javascript">
        if (RegExp('multipage', 'gi').test(window.location.search)) {
        introJs().setOption('Next page').start();.oncomplete(function() {
        window.location.href = 'index.php/profile_settings';
        });
      };
</script>

<a data-intro='Hello step two!' data-step='2' data-position='bottom' title="..." class="settings">Settings</a>
```

Can you tell me please where I was wrong?

Second question: How to make two way?
User can simply login or if he doesn't have an account he can press register link on tool-tip or push button, etc... Hereafter he will come Sign up form with own guide. After user push button save he will come to page profile_view.

Login -> Profile_view
Sign Up -> Sign Up form - > Profile_view

**Comment by bozdoz** [comment]
Looks to me like there is a problem with your JavaScript:

`introJs().setOption('Next page')` **(Not a valid option)**

`.goToStep(2).start();.oncomplete` **(semi-colon in the wrong place)**
