### ISSUE TITLE
No width customization per tip

### ISSUE THREAD

**Issue by rzhh1212** [usablica/intro.js#1377]
## Description
I noticed there is no width or any other style support for the single tip, only position available to change, which is not convenient.

## Expected Behavior
Can you please add width support in json, or css class, I want different widths of tips sometimes

## Actual Behavior
What actually happened?

## Errors and Screenshots (optional)
Give us any additional information if you have.

## Example (recommended)
no necessary to provide sample

## Environment (optional)
List browser information, Intro.js version, Operating System, JavaScript libraries (jQuery, Angular, React), etc.

**Comment by afshinm** [comment]
Can you use something like this https://introjs.com/docs/examples/customizing/css-class?

**Comment by flppv** [comment]
> Can you use something like this https://introjs.com/docs/examples/customizing/css-class?

It would change the tooltip width for all steps, and OP asked for certain widths for each step.

**Comment by tyokobo** [comment]
For that you have to add specific id's to each step, since the tour doesn't do it automaticly yet.

You could use somethinf like this:

 intro.onbeforechange(function () {
    if (this._currentStep === 01) {
      jQuery('.introjs-helperLayer').attr('id', 'help-01');
      jQuery('.introjs-tooltip').attr('id', 'tooltip-01');
    }
});
