### ISSUE TITLE
[Feature Request] onComplete Improvments

### ISSUE THREAD

**Issue by ImBeCiliC** [usablica/intro.js#1385]
## Usecase
On last Step >>
Click on Done (Label - "Restart the Tour") -> Tour stays open like beforeExit(false) and jumps to Step 1
Click on Skip  (Label - "Tour Finished Congratulation!" +  the 'x') -> Tour exits and nothing happens.

## Solution
Give some Params into the Callback. Like StepNr, which Button triggered the Complete and the Possibility to return false to keep the Tour open.

In General more Params into the Callbacks would help with the Flexibility of the Library. Better send a bit more and let the User handle the Usage.

Thanks for the Development of this Lib! 🎉

**Comment by joostmeijles** [comment]
I need this as well. Is there currently a workaround to determine which button (back, next) was pressed?

**Comment by afshinm** [comment]
Agreed. I will add more details to the oncomplete callback.

**Comment by afshinm** [comment]
Added the tour step and a `mode` argument to the oncomplete callback. `mode`, the second argument, can have following values:

- `end`: when the tour ends (i.e no more steps in the tour to play)
- `skip`: when the skip button is clicked
- `done`: when the Done button is clicked
