### ISSUE TITLE
JS and CSS in CDN returns cannot find

### ISSUE THREAD

**Issue by roshan92** [usablica/intro.js#1389]
I was using the CDN below for the past few days and it seems fine until a few hours ago when it stopped working.

https://unpkg.com/intro.js/minified/introjs.min.css
https://unpkg.com/intro.js/minified/intro.min.js

Currently it returns the error below:

> Cannot find "/minified/introjs.min.css" in intro.js@4.2.1
> Cannot find "/minified/intro.min.js" in intro.js@4.2.1

**Comment by afshinm** [comment]
This issue is fixed now. Sorry about that folks.
