### ISSUE TITLE
Option to make the highlighted element unclickable.

### ISSUE THREAD

**Issue by WhileLoop** [usablica/intro.js#139]
Hi all,

First of all, great work, love this library. 

For my project I had the need to make it so that the element which was being highlighted should not be clickable since clicking it would modify the page and break the next step of the intro. I did this by creating a DIV which would use the same absolute positioning as the helperLayer, with a higher Z-index, a opacity of 0, and cursor: not-allowed. Alternatively the DIV could be added as a child to the helperLayer, this would remove the need to absolutely position.

If this is an acceptable solution I could create a pull request with the changes.

**Comment by delmicio** [comment]
Easier than @Alchnemesis method with css:
```CSS
.introjs-tooltipReferenceLayer {
    visibility: visible;
}
```

**Comment by bozdoz** [comment]
@iamdanfox looks like a good solution to this problem.  

in summary: add and remove an event listener to a button with `e.stopPropagation()` within the function to keep it from executing any other event listeners. 

I do not think this should be solved with CSS as others have recommended.  And I'm also unsure that this should be part of the library as opposed to just implemented when needed.  I personally did use something like this on my own project, however; so it could be useful to a number of people.  

@afshinm thoughts?
