### ISSUE TITLE
Unable to highlight particular class

### ISSUE THREAD

**Issue by NevethaNevi** [usablica/intro.js#1397]
## Description
Unable to highlight particular class that loads while tour is in in-progress.

## Expected Behavior
Classes that loads while the tour is in-progress should identify and highlight as its in flow

## Actual Behavior
But Classes are not highlighting, intro.js picking only the classes that exists already when the tour is started

## Errors and Screenshots (optional)
Expectation:
![Expections](https://user-images.githubusercontent.com/36670269/131498565-8f649167-f311-4585-be2d-1341409e4fe1.png)

What we are getting:
![Actual](https://user-images.githubusercontent.com/36670269/131498598-7f5bb92b-af67-4870-b360-e80ed016f3c7.png)

**Comment by afshinm** [comment]
Please share more details. Does that element exist on the page when you start the tour?

**Comment by NevethaNevi** [comment]
No, while we are in tour when we click next button in one tour the screen will open and we need to highlight that opened part as next step.
