### ISSUE TITLE
When i insert an element with height dynamic before the hight light element,the position of top can not recalculate,it will  cause the following problems

### ISSUE THREAD

**Issue by Junfeizhao** [usablica/intro.js#1403]
## Description
Describe one (and only one) issue or enhancement you want to see in Intro.js (before writing any code).

## Expected Behavior
What did you expect to happen?

## Actual Behavior
What actually happened?

## Errors and Screenshots (optional)
Give us any additional information if you have.

## Example (recommended)
How can someone else see/test this issue?  List the steps or write some code; or create a jsfiddle or codepen.

## Environment (optional)
List browser information, Intro.js version, Operating System, JavaScript libraries (jQuery, Angular, React), etc.

**Comment by Junfeizhao** [comment]
![图片](https://user-images.githubusercontent.com/47941990/132197003-de89fc55-890e-42ef-ab53-2b4dc064c0eb.png)

This happens when I have an iframe on my page. My current solution is to listen to iframe loading and then execute introjs. Can introjs be implemented internally?

**Comment by afshinm** [comment]
Please share more details.
