### ISSUE TITLE
onafterchange callback bug

### ISSUE THREAD

**Issue by leonepagani** [usablica/intro.js#1411]
Hey everyone. I'm trying to call onafterchange callback method, but, it still be called before change tutorial step, as onbeforechange method.

![image](https://user-images.githubusercontent.com/90622170/133085900-cea4e5bb-a9a5-432f-9700-34e61e9dba3c.png)

I saw that already be open a issue about this bug. but it's closed. There are some solution to this bug?

Thanks. Leone.

**Comment by afshinm** [comment]
Would you be able to create a jsFiddle/Codesandbox for me?
