### ISSUE TITLE
setOption does not update `disableInteraction` parameter

### ISSUE THREAD

**Issue by melissadiazokay** [usablica/intro.js#1414]
## Description
I have `disableInteraction` set to `true` when the tour initializes and using the `onchange` hook with the `targetElement` passed into the callback function to monitor the element being highlighted in my tour. I would like to set `disableInteraction` to `false` when a particular element is highlighted, allowing the user to click on this element. I am using the `setOption` method to set `disableInteraction` to `false` within the callback of the `onchange` method but it does not seem to have any effect on the users' ability to interact with the highlighted element.

## Expected Behavior
Running `introJs().setOption('disableInteraction', false);` in my code should enable the ability to interact with highlighted elements in the tour.

## Actual Behavior
There is no change in the users' ability to interact with the highlighted elements in the tour.

## Errors and Screenshots (optional)
n/a

## Example (recommended)
`      
    introJs()
    .setOptions({
      steps: tutorialSteps,
      disableInteraction: true,
    })
    .onchange(function (el) {
      if(el.classList.contains('my-class')){
        introJs().setOption('disableInteraction', false); 
      }
    }).start();`

## Environment (optional)
Intro.js v3.4.0, Vue JS v2.6.12, All browsers (firebox, chrome, safari, edge), Mac OS (but observed on Windows as well)
List browser information, Intro.js version, Operating System, JavaScript libraries (jQuery, Angular, React), etc.

**Comment by afshinm** [comment]
It is not possible to change the options at runtime yet unfortunately.

**Comment by tefod-zz** [comment]
Thanks for the info. That's a pitty.  I just ask myself why setoption()/setoptions() does really exist - or at least why it is not documented in the API description - since I stumbled over it now, too :)
