### ISSUE TITLE
[Question] How to change the border of helpLayer

### ISSUE THREAD

**Issue by Mihuuu** [usablica/intro.js#1418]
Hi, is there any method to remove or change the black border of the highlighted target? As the image below shows.(Should I use 'highlightClass' to change the box-shadow?)

![image](https://user-images.githubusercontent.com/22649884/133754360-908c0f39-e7c2-4aa0-a1ab-08950526f252.png)

**Comment by afshinm** [comment]
Your solution is actually great! thanks for sharing @ChihChunHan
