### ISSUE TITLE
[Question] How to use it with vue.js?

### ISSUE THREAD

**Issue by Jumborner** [usablica/intro.js#1419]
Hi, I want to use intro.js in my vue project running on vite but I cannot figure out how to do this. I have seen there there was a vue-introjs package, but that one is currently archived and made for vue cli + webpack.

**Comment by suryarajendhran** [comment]
I think you can initialise introJs inside your mounted block and add the data tags to your elements. Bind the introJs.start() call to a 'start demo' button.

**Comment by Jumborner** [comment]
> I think you can initialise introJs inside your mounted block and add the data tags to your elements. Bind the introJs.start() call to a 'start demo' button.

Did something similar, seems to work.
