### ISSUE TITLE
"onexit" event still being fired on overlay click when "exitOnOverlayClick" is set to false

### ISSUE THREAD

**Issue by nnieman** [usablica/intro.js#144]
If the "exitOnOverlayClick" option is set to false, when the user clicks the overlay (which would close the intro if "exitOnOverlayClick" were not false) the onexit event fires.  This is not expected behavior as the intro has not actually exited.

Code demonstrating problem:

``` javascript
var intro = introJs();

intro.setOptions({
  exitOnOverlayClick: false
});

intro.onexit(function() {
  alert("intro has exited");
});

intro.start();
```

**Comment by Chintub** [comment]
This below code is working. 

.introjs-overlay {
   pointer-events:none; 
}

**Comment by bozdoz** [comment]
The above code appears to be working: https://jsfiddle.net/bozdoz/s2mrfw7f/4/

Perhaps it has already been resolved in a more current version.  Thanks!
