### ISSUE TITLE
angular-intro.js

### ISSUE THREAD

**Issue by LEAGUEDORA** [usablica/intro.js#1444]
![image](https://user-images.githubusercontent.com/61022690/135787681-a8c5aba2-a857-4d41-b347-3bc5d04d8fea.png)
![image](https://user-images.githubusercontent.com/61022690/135787692-fe58a828-f9a4-45f6-9380-72dba8e9f4e8.png)
![image](https://user-images.githubusercontent.com/61022690/135787708-7118029e-b1d6-4dee-aee6-795c63a1f7b7.png)
When I am executing the code, it shows  core.js:6479 ERROR TypeError: introjs is not a function  at new AppComponent (app.component.ts:20)
[README.md](https://github.com/usablica/intro.js/files/7275247/README.md)

**Comment by afshinm** [comment]
Thanks for the question @LEAGUEDORA. We don't officially support the Angular wrapper yet. Please open an issue on their GitHub repo.

**Comment by maitrungduc1410** [comment]
it's simple, follow my gist: https://gist.github.com/maitrungduc1410/68ae50b9c9a6c893959075a1c15871a8
