### ISSUE TITLE
How can I get the button to show help when clicking on show help a second time. It is not toggling with the for loop if links are clicked?

### ISSUE THREAD

**Issue by vgingin** [usablica/intro.js#1446]
function introFunction() {
	if (false) {
		$("#helpFunc").html("Show Help");
		introJs().removeHints();
	} else {
		$("#helpFunc").html("Hide Help");
		introJs().showHints();
	}
	
	//hints = !hints;
	    for (var i = 0, n = allLinks.length; i < n; i++) {
	        allLinks[i].onclick = function () {
	        	$("#helpFunc").html("Show Help");
	        	introJs().removeHints()

	        }

	    }
	    // add hints and set options here
	    hints = !hints;
}

**Comment by afshinm** [comment]
I'm not exactly sure what the issue is here. Please fill out the issue template.
