### ISSUE TITLE
Not Clickable highlighted area

### ISSUE THREAD

**Issue by radhe-saini** [usablica/intro.js#1451]
## Description
Describe one (and only one) issue or enhancement you want to see in Intro.js (before writing any code).
` 

1. <Steps
          enabled={this.state.stepsEnabled}
          steps={this.state.steps}
          initialStep={this.state.initialStep}
          onExit={this.onExit}
          disableInteraction={false}
          options={{
            // showStepNumbers: true,
            showBullets: true,
            // exitOnOverlayClick: true,
            // doneLabel: "Finish",
            // nextLabel: "Next",
            // hideNext: true,
            // showProgress: true,
            // backgroundColor: 'white'
          }}
        />

`

## Expected Behavior
What did you expect to happen?
when we come to any step then we should get to the next one only when clicking on the highlighted area. if you have a feature then, please share the example code snippet.

## Actual Behavior
What actually happened?
i have tried a lot to make a functional highlighted button by using disable interaction props but this is not working for me.

## Errors and Screenshots (optional)
Give us any additional information if you have.
I think we use disable interaction props.

## Example (recommended)
How can someone else see/test this issue?  List the steps or write some code, or create a jsfiddle or code pen.

## Environment (optional)
List browser information, Intro.js version, Operating System, JavaScript libraries (jQuery, Angular, React), etc.
Reactjs

**Comment by afshinm** [comment]
@radhe-saini does the target element (or any parent elements) have position:fixed or absolute?

**Comment by Mihailoff** [comment]
Same issue, the highlighted area doesn't close/progress tour.

I'm using the `data-intro` attribute, position is not absolute.
