### ISSUE TITLE
Doesn't work properly over TR elements

### ISSUE THREAD

**Issue by alvarotrigo** [usablica/intro.js#146]
I have noticed it doesn't work properly if you try to point a TR element.
The content of the row is behind the tour overlay.

Here's a living demo:
http://jsfiddle.net/wP2d7/

**Comment by bozdoz** [comment]
Is this still an issue?

Posted the above code in a fresh jsfiddle with the current library here: https://jsfiddle.net/bozdoz/e4at4o5m/
