### ISSUE TITLE
`onBeforeStep` and `onAfterStep`

### ISSUE THREAD

**Issue by bilogic** [usablica/intro.js#1461]
## Description
I thought tracking by steps made more sense instead of tracking by the target elements, especially when there is already `goToStep()`

## Expected Behavior
`onbeforechange` and `onafterchange`, except the callback provides step as well as the target element

Thank you.

**Comment by afshinm** [comment]
You can get access to the target element using `this._targetElement` in your callback function.

**Comment by bilogic** [comment]
Sure, but what is the purpose of `step` since it exists?
