### ISSUE TITLE
`start()` does not trigger `onbeforechange` or `onafterchange`

### ISSUE THREAD

**Issue by bilogic** [usablica/intro.js#1462]
## Description
I'm trying to play audio in the event callbacks as suggested here https://github.com/usablica/intro.js/issues/722
However, `start()` does not trigger either event, thus my first step does not get audio.

## Expected Behavior
`start()` should be considered as a change/step and trigger the respective events.

## Actual Behavior
No event occurs on `start()`

## Example (recommended)
```javascript
<script>
      function intro() {
          introjs = introJs().setOptions({
              steps: [{
                      element: document.querySelector('#login2'),
                      intro: "Click here to login!"
                  },
                  {
                      intro: "Hello world!"
                  }
              ]
          }).start();

          introjs.onafterchange(function(elem) {
              console.log(elem);
              if (elem.id = "login2") {
                  var audio = new Audio('/storage/sound.mp3');
                  audio.play();
              }
          });
      }
</script>
```

**Comment by afshinm** [comment]
I see. I will add `onstart()` callback which would help you with this use-case. We already have onexit() callback.

**Comment by bilogic** [comment]
Thanks!

**Comment by bilogic** [comment]
It's been a while since I wrote the code, I think it makes more sense to just call `onafterchange`, so that all user logic can reside there. Maybe adding a `start` and `exit` flag makes more sense.

**Comment by afshinm** [comment]
Just added the onstart callback. I will release a new version in a few mins.

Re onafterchange: it's kinda scary to change the behavior of onafterchange/onbeforechange at this point, since many people are already using it. Having both onstart/onafterchage/onexit should address your issue.

**Comment by bilogic** [comment]
got it thanks~
