### ISSUE TITLE
Previous and Next button Trigger automatic

### ISSUE THREAD

**Issue by tyokobo** [usablica/intro.js#1470]
## Description
I need to trigger an element that opens a closes a side menu, so i did it when the "next" button is clicked, I trigger the element from menu, and the menu opens, however, when I go to the next step, it triggers the element again.

So I tried to remove the class from the buttons, and to my surprise, even without the class, they still going to the next and previous step.

I used onchange and onbeforechange to makes the functions work in the steps.

I added unique id's to each step, it works for styling with css, bu not working with js.

## Expected Behavior
Onchange  is supposed to trigger a element, only in that step, however it is triggering in everystep.

## Actual Behavior
Onchange  is supposed to trigger a element, only in that step, however it is triggering in everystep.

## Example (recommended)
var introTour = introJs();
$(function() {

     introTour.setOptions({
      hidePrev: true,
      hideNext: true,
      exitOnOverlayClick: false,
      exitOnEsc: false,
      showProgress: true,
      steps: [
        {
          element: ('.kjh'),
          position: 'top',
          intro: 'Begin',
            onchange: function() {
              jQuery('.introjs-helperLayer').attr('id', 'help-00');
              jQuery('.introjs-tooltip').attr('id', 'tooltip-00');
              jQuery('.introjs-nextbutton').attr('id','indo-00');
              jQuery('.introjs-prevbutton').attr('id','vindo-00');
              //do something interesting here...
            },
            onbeforechange: function() {
             
              //do something else interesting here...
            }
        },
        {
          element:  '.002',
          intro:    'Second',
          position: 'bottom',
          onchange: function() {
            jQuery('.introjs-helperLayer').attr('id', 'help-01');
            jQuery('.introjs-tooltip').attr('id', 'tooltip-01');
            jQuery('.introjs-nextbutton').attr('id','indo-01');
            jQuery('.introjs-prevbutton').attr('id','vindo-01');
            jQuery('#vindo-01').click( function() {
              alert('voltando01');
        });
         
            //do something interesting here...
          },
          onbeforechange: function() {
           
            //do something else interesting here...
          }
          
        },
        
        {
          element: ('.003'),
          
          intro: 'Third',
          position: 'bottom',
          onchange: function() {
            jQuery('.introjs-helperLayer').attr('id', 'help-02');
            jQuery('.introjs-tooltip').attr('id', 'tooltip-02');
            jQuery('.introjs-nextbutton').attr('id','indo-02');
            jQuery('.introjs-prevbutton').attr('id','vindo-02');
            jQuery('.menuMonitor').trigger('click');
            jQuery('#vindo-02').click( function() {
              alert('voltando02');
              jQuery('.introjs-prevbutton').removeAttr('id','vindo-02');
              jQuery('.menuMonitor').trigger('click');
        });
           
            //do something interesting here...
          },
          onbeforechange: function() {
         
            //do something else interesting here...
          }
        },
        {
          element: ('.004'),
          position: 'top',
          intro:    'fourth',
            onchange: function() {
              jQuery('.introjs-helperLayer').attr('id', 'help-03');
              jQuery('.introjs-tooltip').attr('id', 'tooltip-03');
              jQuery('.introjs-nextbutton').attr('id','indo-03');
              jQuery('.introjs-prevbutton').attr('id','vindo-03');
             
              //do something interesting here...
            },
            onbeforechange: function() {
              
              //do something else interesting here...
            }
       
          },
        {
          element: ('.005'),
          position: 'top',
          intro:
            'fith',
            onchange: function() {
              jQuery('.introjs-helperLayer').attr('id', 'help-04');
              jQuery('.introjs-tooltip').attr('id', 'tooltip-04');
              jQuery('.introjs-nextbutton').attr('id','indo-04');
              jQuery('.introjs-prevbutton').attr('id','vindo-04');
              jQuery('.menu').trigger('click');
             
              //do something interesting here...
            },
            onbeforechange: function() {
              jQuery('#vindo-04').click( function() {
                jQuery('.menu').trigger('click');
          });
              //do something else interesting here...
            }
        }
       
       
      ]
    });
  });

  function createStepEvents(guideObject, eventList) {

    //underscore loop used here.
    _.each(eventList, function(event) {
  
      //for the guid object's <event> attribute.
      guideObject[event](function() {
  
        //get its steps and current step value
        var steps = this._options.steps,
          currentStep = this._currentStep;
  
        //if it's a function, execute the specified <event> type
        if (_.isFunction(steps[currentStep][event])) {
          steps[currentStep][event]();
        }
      });
  
    }, this);
  }
  
  //setup the events per step you care about for this guide
  createStepEvents(introTour, ['onchange', 'onbeforechange','onafterchange']);
 

      var doneTour = localStorage.getItem('1.0') === 'Completed';
      if (doneTour) {
          return;
        
      }
      else {
      
        function tempo() {
          introTour.start()
        }

        setTimeout(tempo, 2000)

        introTour.oncomplete(function () {
          localStorage.setItem('1.0', 'Completed');
        });

        introTour.onexit(function () {
          localStorage.setItem('1.0', 'Completed');
        });
      }

}

**Comment by afshinm** [comment]
Intro.js doesn't support onchange for each step (in fact your JSON config for `steps` is not valid), see https://introjs.com/docs/examples/basic/json-config -- you can, however, use the onchange callback and `this._currentStep` to get your current tour step. Hope that helps.
