### ISSUE TITLE
Don't display data-info without a data-step

### ISSUE THREAD

**Issue by webhat** [usablica/intro.js#148]
I am using the data-intro attribute to display additional help items than I don't need to have displayed in my intro, I've currently solved this by with this modification. It would be handy to be able to skip elements which don't have the data-step attribute.

```
-var allIntroSteps = targetElm.querySelectorAll("*[data-intro]"),
+var allIntroSteps = targetElm.querySelectorAll("*[data-step]"),
```

**Comment by bozdoz** [comment]
I am unfamiliar with this aspect of the library. @afshinm

**Comment by webhat** [comment]
I did make the comment 4 years ago, so there's not an unreasonable chance it is no longer relevant. ;D
