### ISSUE TITLE
Incorrect behavior when auto aligning with "-right-aligned"

### ISSUE THREAD

**Issue by Livijn** [usablica/intro.js#1482]
## Description
Incorrect behavior when auto aligning with "-right-aligned". This issue might be related to #1267. This behavior is caused by this line: https://github.com/usablica/intro.js/blob/c8d0f538ecd951d2a5e74ec508d75d192c7505c3/src/core/placeTooltip.js#L48

Right now, we are not considering the elements width into consideration. Basically, it should be something like: 
```js
const referenceWidth = document.querySelector('.introjs-tooltipReferenceLayer').offsetWidth;

if (offsetLeft + referenceWidth < tooltipWidth) {
```

## Expected Behavior
The `-right-aligned` should take the element's width in consideration.

![Print](https://i.gyazo.com/e4ff6c0b57deb989510b366fe0edccee.png)

## Actual Behavior
Right now the tooltip breaks the viewport.

![Print](https://i.gyazo.com/76d8efea4a31cff28afb38b39bafd7e1.png)

**Comment by eddsaura** [comment]
This still doesn't work
