### ISSUE TITLE
Translate "of" in helperNumberLayer

### ISSUE THREAD

**Issue by dmitry53** [usablica/intro.js#1485]
How its possible to translate or change "of" ?
![Снимок экрана 2021-11-09 023224](https://user-images.githubusercontent.com/2632988/140834838-dfee7c86-deed-4060-ba88-1ae8c5b48f33.png)

**Comment by dmitry53** [comment]
any idea? I need use 1 / 18 step

**Comment by ivan-jumbomail** [comment]
> any idea? I need use 1 / 18 step

1. Add handler for onBeforeChange
2.  Find element represents it, for example `const stepNumsEl = document.querySelector('.introjs-helperNumberLayer');`
3.  Set data-attr to the elment like `stepNumsEl.setAttribute('data-step-nums', `${nextStepIndex + 1} / ${steps.length}`);`
4.  Add styles  like `
 .introjs-helperNumberLayer:before {
  display: block;
  position: absolute;
  bottom: 14px;
  content: attr(data-step-nums);
}
`
5. Hide previous text.
![image](https://user-images.githubusercontent.com/97881234/151795323-a27cfcc3-ca9e-4889-98cd-7c8a97179fd6.png)

**Comment by dmitry53** [comment]
> 4\. .introjs-helperNumberLayer:before {   display: block;   position: absolute;   bottom: 14px;   content: attr(data-step-nums); }

thank you Ivan, it works!

`     
      const intro = introJs();
      intro.setOptions({
        tooltipClass: 'introjs-vue',
        showBullets: false,
        showProgress: true,
        showStepNumbers: true,
        steps: this.IntroSteps,
      });

intro.onafterchange(() => {
        const stepNumsEl = document.querySelector('.introjs-helperNumberLayer');
        stepNumsEl.setAttribute('data-step-nums', `${intro._currentStep + 1} / ${intro._introItems.length}`);
      }).start();
`
css
`
.introjs-helperNumberLayer:before {
  display: block;
  position: absolute;
  bottom: -2px;
  content: attr(data-step-nums);
  font-size: 11px;
  white-space: nowrap;
}
`
