### ISSUE TITLE
*display: inline resulting in warning: Expected identifier but found "*"

### ISSUE THREAD

**Issue by dadasign** [usablica/intro.js#1507]
Not sure if this line is some feature or a typo, but it results in warnings when processed:
https://github.com/usablica/intro.js/blob/3143e1323ef63b6d2c99650c0c0f382dbf96d1c9/src/styles/introjs.scss#L235

I can imagine this being either a typo or some hack to block the line for particular browsers. If it's a 'feature' maybe a comment would help clarify where does the `*` come from and what its purpose is. I haven't seen anything like that before.

**Comment by ghonche** [comment]
I was getting the same warning. Hope my pull request will be approved
![Screenshot from 2021-12-19 11-13-39](https://user-images.githubusercontent.com/25591295/146671410-2931b283-83bd-430c-b589-2144d751d5a7.png)
.
