### ISSUE TITLE
position:fixed, the text color is white

### ISSUE THREAD

**Issue by wxs77577** [usablica/intro.js#151]
the text color is changed from black to white after I set the text wrapper div position:fixed;
help me please...

``` html
<div style="position:fixed">i am the text who your said.</div>
```

**Comment by esrefatak** [comment]
@afshinm  Did you fix the problem? I face too with this problem. Thanks.
@GenYii  did you find any workaround? Thanks.

**Comment by xiaomantoujun** [comment]
@afshinm Did you fix the problem? I face too with this problem. Thanks.
