### ISSUE TITLE
React warning on attribute data-hintPosition 

### ISSUE THREAD

**Issue by wouter-leistra** [usablica/intro.js#1560]
## Description
Our console is warning constantly that the HTML attribute data-hintPosition is against some rules or conventions for HTML attributes that should be all LOWERCASE (React). Do you think we could add a possibility to change 'data-hintPosition' to 'data-hint-position'?

## Environment (optional)
React

**Comment by afshinm** [comment]
https://github.com/usablica/intro.js/pull/1575
