### ISSUE TITLE
How can we add Checkbox in Intro.js.

### ISSUE THREAD

**Issue by shaileshsangle** [usablica/intro.js#1609]
## Description
How can we add Checkbox  (Don't show again)  on intro.js and how can we get the checkbox value?

## Expected Behavior
When a user clicks on a checkbox and clicks on the Done button, then a tour should not be displayed to the user.

## Actual Behavior
We are not able to create a checkbox and get the checkbox value.

## Environment (optional)
List browser information, Intro.js version, Operating System, JavaScript libraries ( React), etc.
1. Chrome, Mozilla, Safari, Edge.
2. Intro.js Version: 5.0.0.
3. OS: Windows and Mac
4. Javascript Libraries: Vanilla Javascript and React js.

**Comment by flinthamm** [comment]
+1
