### ISSUE TITLE
_exitIntro is not removing all introjs css that was added (HighPriority)

### ISSUE THREAD

**Issue by 21degrees** [usablica/intro.js#162]
_exitIntro method doesn't remove .introjs-showElement on all elements, it just removes the current element. This is causing other elements show up on top of introjs layer on subsequent tours and sometimes on the same tour. Suggested implementation to remove a particular class, this must be done for all classes added by introjs.

var showElements = $.find('.introjs-showElement');

showElements.each(function(showElement){
showElement.removeClass('.introjs-showElement');
})

**Comment by dearn44** [comment]
I actually can confirm this. The classes ```introjs-relativePosition introjs-showElement``` wont be removed if you try to exit by Esc or clicking somewhere on the page.

**Comment by bozdoz** [comment]
I believe this issue has already been addressed with new addClass and removeClass methods.  Please reopen if it is still an issue.
