### ISSUE TITLE
JSON steps not working for some elements?

### ISSUE THREAD

**Issue by ImaCrea** [usablica/intro.js#1627]
Hello there ! Thanks for this great tool :)

I try to make a scenario only by using a json but sometimes the intro doesn't focus on element event though querySelector is supposedly fine.

On `div` and `li` it looks fine. But on `a` doesn't seem it can focus to it.

Are there any limitation with the json way or should be able to focus on any kind of element of the DOM?

Thanks :)

**Comment by afshinm** [comment]
Please share your code. It's difficult for me to debug without seeing your config file at least.

**Comment by ImaCrea** [comment]
> Please share your code. It's difficult for me to debug without seeing your config file at least.

Hey, sorry I put on pause this project meanwhile and didn't see your reply. Thanks, I'll let you know what got me stuck when I'm back at it.
