### ISSUE TITLE
Webpack not found intro.module.js.map

### ISSUE THREAD

**Issue by popuguytheparrot** [usablica/intro.js#1641]
WARNING in ./node_modules/intro.js/intro.module.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/ruattr2/WebstormProjects/corpcrm-ui/node_modules/intro.js/intro.module.js.map' file: Error: ENOENT: no such file or directory, open '/Users/ruattr2/WebstormProjects/corpcrm-ui/node_modules/intro.js/intro.module.js.map'

**Comment by flacoman91** [comment]
Us react devs also see this too: https://github.com/usablica/intro.js/issues/1595 

Doesn't really break anything while we're developing since they're just warnings, but it would be nice to not see the warnings.
