### ISSUE TITLE
'scrollToElement' option doesn't work properly in Firefox and Safari

### ISSUE THREAD

**Issue by VladMakushenko** [usablica/intro.js#1666]
## Description
'scrollToElement' option doesn't work properly in Firefox and Safari

## Expected Behavior
It should jump to the next (or prev) element.
It happens in Chrome, but does not in Firefox and Safari

## Actual Behavior
When clicking the next (or prev) button, viewport doesn't change, so you have to scroll manually.

## Environment (optional)
Intro.js version is 5.1.0, but I tried different versions.

**Comment by afshinm** [comment]
Could you provide a screenshot or demo please?
