### ISSUE TITLE
npm package has source files minified

### ISSUE THREAD

**Issue by ryders** [usablica/intro.js#1671]
## Description
It appears that all source files are minified. I'm not a packaging expert, however looking at a few other packages installed in my node_module/ folder, and most have the source in src/ as not minified, and the source in dist/ as minified.

## Expected Behavior
I don't expect all .js to be minified, specially when it comes to debugging and trying to figure things myself, out prior to raising issues. I'm currently experiencing a problem where `.removeHints()` doesn't remove anything.. and I have no avenue to trying to understand whether anything I've done is impacting this.

## Actual Behavior
When debugging, if you're stepping into any intro.js functions, it's essentially impossible to figure out what's happening.

## Errors and Screenshots (optional)
Not Applicable. Well.. I've included one for your viewing pleasure!
![Screen Shot 2022-05-20 at 12 32 33](https://user-images.githubusercontent.com/242383/169599771-41439ad3-f7ed-455a-8ba9-5e9cdd4dd4f3.png)

Clearly -- I cannot step into intro.js:
![Screen Shot 2022-05-20 at 12 39 32](https://user-images.githubusercontent.com/242383/169600468-05f1e3d4-8518-4337-b1d1-b5e312418ddf.png)

Comparatively -- I can step into Angular' HttpClient class with no trouble
![Screen Shot 2022-05-20 at 12 41 40](https://user-images.githubusercontent.com/242383/169600501-e59a37f4-6919-4f27-8eaa-701dccce6aee.png)

## Example (recommended)
```npm install intro.js
cat node_modules/intro.js/intro.js```

## Environment (optional)
"intro.js": "^5.1.0"

**Comment by Ryders** [comment]
btw -- I was able to prettyprint (using, eg. beautifier.io) and manually save the file, but this goes beyond good practices for npm packages...

**Comment by bazubii** [comment]
Hitting the same issue. As a workaround, I commended out these lines:
https://github.com/usablica/intro.js/blob/55bac403388c5ee00d6c0139386d1687d9063877/rollup.config.js#L40
https://github.com/usablica/intro.js/blob/55bac403388c5ee00d6c0139386d1687d9063877/rollup.config.js#L46
and added `minimize: false` to the postcss of the non-minimized ones in the same file.
Then I built and copied the non-minimized ones.
This isn't a full fix as it breaks the minimized versions.

**Comment by afshinm** [comment]
Is it possible to use the sourcemaps? Intro.js provides sourcemaps for all minified files.

**Comment by sammuell** [comment]
I had exactly the same question in my mind when I installed this package. 
The main folder as well as the 'minified' folder within _both_ contain minified identical files (why?), making the minified folder and its contents completely obsolete.
To debug the npm package you basically have to clone the repo.

**Comment by sammuell** [comment]
> Were you able to use the sourcemaps provided in the package?
No, I ended up cloning the repo locally instead of using the npm package.

**Comment by ryders** [comment]
@afshinm can you confirm files are no longer minified? All I see here is a discussion of workarounds and alternatives, not addressing the root problem where good practices suggestthatminified JavaScript shouldn't be found in a file that is not named .min

Feel free to close but I don't have any evidence this was addressed.

**Comment by ryders** [comment]
@afshinm can you confirm files are no longer minified? All I see here is a discussion of workarounds and alternatives, not addressing the root problem where good practices suggestthatminified JavaScript shouldn't be found in a file that is not named .min

Feel free to close but I don't have any evidence this was addressed.
