### ISSUE TITLE
exitOnOverlayClick issue

### ISSUE THREAD

**Issue by raulmatei** [usablica/intro.js#172]
Hi,

I have to use exitOnOverlayClick/exitOnEsc: false options, that stop users to exit the tour, but onexit() I'm using a callback that fires a Bootstrap window, well exitOnEsc works well but when I click on the overlay the bootstrap window appears underneath.

Some ideas?

**Comment by afshinm** [comment]
Duplicate https://github.com/usablica/intro.js/issues/560

Fixed.
