### ISSUE TITLE
[React] Position in mobile is changed? 

### ISSUE THREAD

**Issue by eddsaura** [usablica/intro.js#1732]
## Description
The position when mobile is automatically set to center (inconsistently). Meaning if I have a step set to left, the class it has is center.

## Expected Behavior
I expect the tooltip has the position I set in `Steps[]`.

## Actual Behavior
Even I put `left` or `bottom` or `top` the tooltip is always centered and added the class `introjs-bottom-middle-aligned`

## Errors and Screenshots (optional)
We actually wanted it to be conditional depending on the width, but right now is fixed to left.
```js
   {
      intro: (
        <StepTooltip
          title={t('step3.title')}
          text={t('step2.text')}
          img="/img/tour/tour-step3.gif"
        />
      ),
      // ...(width > BREAKPOINTS.tablet ? { position: 'right' } : { position: 'left' }),
      position: 'left',
      element: '#seat-2',
      tooltipClass: 'custom-onboarding-tooltip'
    },
```
![image](https://user-images.githubusercontent.com/13334047/180401252-e57efad8-3d88-41c1-be76-445424101210.png)

Actually, when not mobile the class is the correct one. `introjs-bottom-right-aligned`
![image](https://user-images.githubusercontent.com/13334047/180426927-dd2533d2-a488-442e-8a2c-c21ca1437c32.png)

Once it reachs the mobile breakpoint the class is changed to `introjs-bottom-middle-aligned`

## Example (recommended)
You can check our repo, it's open sourced. [The PR in question](https://github.com/Stooa/Stooa/pull/536).

**Comment by eddsaura** [comment]
😢

**Comment by eddsaura** [comment]
I had to do it manually.
Set a custom class and position it as you need

**Comment by eddsaura** [comment]
Anyway, it still has some strange behaviour. Second time I run the intro the seconds step gets _**another**_ different class `floating`

**Comment by farhantahir** [comment]
@eddsaura Found any solution for this?  we are also facing same issue on mobile devices.

**Comment by eddsaura** [comment]
> @eddsaura Found any solution for this?  we are also facing same issue on mobile devices.

Sure, if you go to that specific PR I mentioned you can ser how I fixed. Not proud but I had to overwrite all the css.
