### ISSUE TITLE
Question: Possibility to customize/remove the border of `.introjs-helperLayer` element

### ISSUE THREAD

**Issue by silasjoisten** [usablica/intro.js#1741]
As you can see in the screenshot there is a border which is not that nice for our design. I have tried a bit but it seems not possible to remove the border because it gets set as `style` attribute via js.

```html
<div class="introjs-helperLayer" style="box-shadow: rgba(33, 33, 33, 0.8) 0px 0px 1px 2px, rgba(33, 33, 33, 0.5) 0px 0px 0px 5000px; opacity: 1; width: 628.672px; height: 90px; top: 199px; left: 390px;"></div>
```

![CleanShot 2022-08-03 at 15 14 48@2x](https://user-images.githubusercontent.com/10114981/182605654-ec8a7902-573e-4339-b00d-f11f503a8cd7.png)

You guys got any Idea?

**Comment by albaninho10** [comment]
Hello, If you are still stuck, where to next:

Personally I take the border off like this:

<style type="text/css">
      .introjs-helperLayer{
            box-shadow: 
            rgb(139 139 139 / 80%) 0px 0px 1px 2px, 
            rgb(33 33 33 / 50%) 0px 0px 0px 5000px !important
        }
</style>

**Comment by silasjoisten** [comment]
Thank you!
