### ISSUE TITLE
Modern THeme is not working as expected

### ISSUE THREAD

**Issue by srikanth1996** [usablica/intro.js#1771]
## Description
I have imported introjs-modern.css" into angular.json file , but getting below position and that too popup is  not coming properly

## Expected Behavior
It should open in certain position and next button should work
## Actual Behavior
It actually showing at bottom of page and next button is not working

## Errors and Screenshots (optional)
![Screenshot_266](https://user-images.githubusercontent.com/14906212/189390589-5abc0456-4773-4830-b622-d580324434f1.png)

## Example (recommended)
import introjs-modern.css file and execute the steps

## Environment (optional)
Using in angular project

**Comment by afshinm** [comment]
You would need to include the theme _after_ the official Intro.js CSS file.
