### ISSUE TITLE
dontShowAgainCookie lacks documentation

### ISSUE THREAD

**Issue by samsontv** [usablica/intro.js#1780]
## Description
There is no explanation of the dontShowAgainCookie on https://introjs.com/docs/intro/options

## Expected Behavior
Clear documentation of this option. Please explain the cookie-related options in more detail. Thank you.

## Actual Behavior
n/a

## Errors and Screenshots (optional)
n/a

## Example (recommended)
I believe this option is critical to being able to show different IntroJS on two pages. If a user selects the Don't Show Again checkbox on Page A, it prevents the different tour from showing on Page B too, which is an undesired outcome.

**Comment by samsontv** [comment]
OK, in testing it appears this might just be to set a cookie name and the following form in the JSON works as expected:
 `dontShowAgainCookie: 'dontShowIntroOnPageA',`  (OptionName: 'CookieName')

**Comment by TarasMARKEVYTCH** [comment]
Hello @samsontv 
I actually trying to use dontShowAgain option but it not working for me. I tried to put it as option "dontShowAgainCookie" and by setOption("dontShowAgain", true) but it not working anyway. Can you tell me how i can implement pls?
