### ISSUE TITLE
The way to use the API always fails to obtain dom elements.

### ISSUE THREAD

**Issue by PaulMing** [usablica/intro.js#1782]
## Description
It is always impossible to obtain dom elements in the way of API. How to solve this problem? Can you provide an asynchronous method to obtain dom

## Expected Behavior
Used during page initialization
<img width="351" alt="image" src="https://user-images.githubusercontent.com/40627394/191505876-93e7ab7c-259c-4d79-8b3d-e963fec58665.png">

**Comment by afshinm** [comment]
I'm not sure I understand this request. Could you provide an example or use-case please?
