### ISSUE TITLE
disableInteractions=false isn't working.

### ISSUE THREAD

**Issue by cpwisam** [usablica/intro.js#1786]
## Description
Using disableInteractions=false is not working for some reason, I am trying to allow the user to interact with the highlighted area if he wants but nothing changes when i toggle this property.

## Expected Behavior
Setting disableInteractions to false will allow the user to interact with elements inside the highlighted area.

## Actual Behavior
After setting the property to false , the user still cant interact with any highlighted element.

## Environment (optional)
Angular

**Comment by afshinm** [comment]
Could share your code/an example please? disableInteraction doesn't work when the parent has position `fixed` or `absolute`.

**Comment by Shwetha-GU** [comment]
Same issue Even im facing when im trying to include intro.js on popup. How to resolve it??
In my case pop-up(parent div) position is absolute. Is there a way to fix this issue without changing its position.

**Comment by BugProg** [comment]
Hi !
I have the same issue

**Comment by plamenkoyovchev** [comment]
I have the same issue with introjs in React application. disableInteractions=false is not working.

**Comment by Swertin** [comment]
As a semi-fix for this, if you add the following global css styles, it will allow you to click through: 
.introjs-overlay{
pointer-events: none;
}

.introjs-helperLayer{
pointer-events: none;
}

**HOWEVER,**
You will not be able to have the tour exit when clicking on the overlay (outside of the box)
