### ISSUE TITLE
Scrolling doesn't work inside a div with overflow:scroll

### ISSUE THREAD

**Issue by iamdanfox** [usablica/intro.js#182]
Place some content into `div.container`, with CSS `overflow:scroll`.  Create your IntroJs object:

```
intro = introJs('.container')
```

The `div` will not autoscroll if a step's element is outside of the visible rectangle.

**Comment by erikmourits** [comment]
Is there a workaround for this problem?

**Comment by andela-efortune** [comment]
I'm still having a problem with this, is there a work around for it yet?

**Comment by jasonphillips** [comment]
This appears to have been addressed by https://github.com/usablica/intro.js/pull/801 -- which isn't published yet, but is in the latest development code. It worked for us, in any case; perhaps this can be closed.
