### ISSUE TITLE
Include Source Map Error

### ISSUE THREAD

**Issue by irtaza9** [usablica/intro.js#1844]
# Error
 **Error: ENOENT: no such file or directory**

# Error Pic

![image](https://user-images.githubusercontent.com/98938307/210162420-43253077-b47e-445b-8b28-41239a1f11e2.png)

# Required

Please let us know how to resolve this warring in our project.

# My Imports

import { Steps } from "intro.js-react";
import "intro.js/introjs.css";

# Tech Stack

React JS

**Comment by afshinm** [comment]
#1595
