### ISSUE TITLE
Warning intro.js/intro.js CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by barrymolavenet** [usablica/intro.js#1849]
Hi

I upgraded the angular 13 to 14 but when I run my project there is a warning.

Warning `intro.js/intro.js`. CommonJS or AMD dependencies can cause optimization bailouts.

Can you help me to remove the warning in my angular project?
Thank you.

**Comment by afshinm** [comment]
I'm not entirely sure why you're getting that warning but I'm interested to know what build pipeline/tools you use?
