### ISSUE TITLE
CSS SRI Hash not working

### ISSUE THREAD

**Issue by samcsimpson** [usablica/intro.js#1878]
The Integrity hash is not working. It gives this error:

Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdnjs.cloudflare.com/ajax/libs/intro.js/6.0.0/introjs-rtl.min.css' with computed SHA-512 integrity 'DkI867vwQXhPLmELEfl4R4+Rg4i7d6GkhcGZ2SuKPm66KI9AAdrE2iCicrerzzwrD3twLrjMbuMyYWCEulTvyw=='. The resource has been blocked.

Chrome is my browser.

**Comment by afshinm** [comment]
Interesting. I'm wondering if this is an issue with the CDN provider?
