### ISSUE TITLE
Expose type-definitions

### ISSUE THREAD

**Issue by boris-petrov** [usablica/intro.js#1902]
## Description
It's great that the library was converted to TypeScript, well done! However, it would be nice to get also the benefits from that to the users by exposing some type-definitions.

## Expected Behavior
No type-errors when I import `intro.js`.

## Actual Behavior
Type-errors.

**Comment by afshinm** [comment]
Agreed and that's what I'm working on now. I'm hoping to publish a new version in the next few days.

**Comment by afshinm** [comment]
@boris-petrov would be great if you review this PR please #1903
