### ISSUE TITLE
Position 'bottom-left-aligned' does not exist

### ISSUE THREAD

**Issue by ironhussar** [usablica/intro.js#1923]
## Description
The position 'bottom-left-aligned' doesn't exist leaving some tooltips to be cut off on the far right of the screen.

## Expected Behavior
bottom middle/bottom right/top -left/top-middle/top-right are working, bottom-left-aligned seems to be missing.

## Actual Behavior
Wide tooltips get cut off on the right side

## Environment (optional)
Intro.js version 7.0.1

**Comment by tinyappz** [comment]
This is not fixed in the latest version
