### ISSUE TITLE
How to highlight multiple elements at the same step？

### ISSUE THREAD

**Issue by yinjiajun223** [usablica/intro.js#1931]
## Description
I want to highlight multiple elements at the same step

## Expected Behavior
I want to highlight multiple elements at the same step, and the element positions are independent of each other

**Comment by sovetski** [comment]
> ![image](https://user-images.githubusercontent.com/74704695/244285320-9b922c1e-898f-4544-8b85-7c748c8839d0.png)

did you test it?

**Comment by tinyappz** [comment]
I'm not sure if @sovetski's suggestion works but have you tried it? Feel free to reopen this ticket if you still need help

**Comment by sovetski** [comment]
Hi @tinyappz it was not my suggestion but @yinjiajun223 and I am not sure that it works, that is why I asked to @yinjiajun223 if hi tried it before suggesting because for me it was not working
