### ISSUE TITLE
Is it possible to disable 'Skip' button?

### ISSUE THREAD

**Issue by cilia** [usablica/intro.js#194]
In certain situations, I want to make sure that the users complete the tour, so an option for disabling the 'Skip' button would be nice.

Can we do this in intro.js at the moment?

**Comment by or9400** [comment]
Tanks xuanlt !

**Comment by dougvk** [comment]
+1

**Comment by CanRau** [comment]
+1
would be awesome when skip and done buttons are really separate and deactivatable :-)
and for a little more neatness, could be nice to disable prevbutton on first step

hacked the plugin to disable skip button, but couldn't disable prevbutton on first step easily.. :/

Saludos, nevertheless thanks for the nice plugin!
Tried many other webguide plugins, but intro.js works the best for me!

**Comment by flamner** [comment]
+1

**Comment by afshinm** [comment]
will fix it guys, thanks.

**Comment by RicardoVaranda** [comment]
+1

**Comment by delmicio** [comment]
+1 (7 months later)

**Comment by rinogo** [comment]
Having skip and done be indistinguishable from a CSS perspective makes Intro.js a lot less flexible.  I'm styling the "Skip" button to be a small, unobtrusive, "x" icon.  However, I want to leave the "Done" button styled similarly to the "Next" button.  With the current implementation, this requires a funky workaround.

Is @waynn's [solution](https://github.com/waynn/intro.js/commit/9ae68362dd2177dcf9e7751586a51d17fc9b1688) acceptable?  If so, can he/she open a PR to be accepted into master?

**Comment by rinogo** [comment]
Looks like [there's already a PR](https://github.com/usablica/intro.js/pull/259) - @afshinm, can you please Merge this PR?

**Comment by afshinm** [comment]
Just merged that PR. I will test it myself today and will include it for the next release. Sorry for this delay.

**Comment by radumpopescu** [comment]
Apparently it did create a bug. I made fix here: #675

**Comment by afshinm** [comment]
I will have a look @radumpopescu

thanks.

**Comment by zzfScarecrow** [comment]
Please fix this....And, I have a problem, please see this，
![image](https://user-images.githubusercontent.com/18343499/29069381-6943630e-7c6d-11e7-87b8-c1a687b8236c.png)
Why the highlight part covered by white?

**Comment by akrako1** [comment]
the introjs-disabled class is added to the 'previous' button on the first step, and the 'next' button on the last step.  i really just wanted them hidden, so i added the below to my css.  Poof!  Done!

.introjs-disabled {
    display: none !important;
}

**Comment by Rafaelinpsercom** [comment]
SOLUCIONADO CON CSS

::ng-deep .introjs-skipbutton{
  visibility: hidden !important;
}
::ng-deep .introjs-donebutton{
  visibility: visible !important;
}

**Comment by Arashturk** [comment]
> Please fix this....And, I have a problem, please see this， ![image](https://user-images.githubusercontent.com/18343499/29069381-6943630e-7c6d-11e7-87b8-c1a687b8236c.png) Why the highlight part covered by white?

hmmm.
you can use **highlightClass** attribute for this:
`steps: [
    {
      title: 'Farewell!',
      element: document.querySelector("#elCreateNew"),
      title: 'MyTitleIntro',
      intro: "This whole area does something.",
      highlightClass: "highlighted-element"
    },
]`

css:
`.highlighted-element {
  border: 2px solid #3498db;
  background-color: rgba(52, 152, 219, 0.3);
}`
