### ISSUE TITLE
How to modify the border of the highlighted area？

### ISSUE THREAD

**Issue by guochangxindeGH** [usablica/intro.js#1967]
## Description
Describe one (and only one) issue or enhancement you want to see in Intro.js (before writing any code).

## Expected Behavior
What did you expect to happen?

## Actual Behavior
What actually happened?

## Errors and Screenshots (optional)
Give us any additional information if you have.

## Example (recommended)
How can someone else see/test this issue?  List the steps or write some code; or create a jsfiddle or codepen.

## Environment (optional)
List browser information, Intro.js version, Operating System, JavaScript libraries (jQuery, Angular, React), etc.

**Comment by harshitkandpal** [comment]
you can use css border properties to do so 
like border-width, border-style, border-color, border-width
even you can combine it hover

**Comment by guochangxindeGH** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by guochangxindeGH** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
