### ISSUE TITLE
Please fix the wrong position bug when the elements are in iframe 

### ISSUE THREAD

**Issue by Hyperionlucky** [usablica/intro.js#1979]
## Description
When the element to be guided is in an iframe, the position of the element is shifted, and this bug needs to be fixed.

**Comment by tinyappz** [comment]
Please try the latest version and let me know if you're still experiencing the same issue.

**Comment by Hyperionlucky** [comment]
OfCourse, there is the same issue, resulting from that the point of reference of the elements in iframe differs from the elements in the main window when using get boundingClientRect() method.
