### ISSUE TITLE
Use relative paths on types 

### ISSUE THREAD

**Issue by luizluan** [usablica/intro.js#1983]
Please use relative paths
![image](https://github.com/usablica/intro.js/assets/13450436/aa8590c9-dc01-4b51-b9e1-d2eef4392660)

To
![image](https://github.com/usablica/intro.js/assets/13450436/7fa40f9d-abaf-416c-91fe-5aa1c8557acc)

https://github.com/usablica/intro.js/blob/cfff59d0a3e6357e335b061f634c09e97f8e6194/src/core/steps.ts#L4C1-L4C37

**Comment by tinyappz** [comment]
Thanks for reporting, this is now fixed
