### ISSUE TITLE
Multi page intro

### ISSUE THREAD

**Issue by vrish88** [usablica/intro.js#2]
How would you get an intro to continue across pages?

**Comment by Feile01** [comment]
It is working perfectly:

<script type="text/javascript">
if (RegExp('multipage', 'gi').test(window.location.search)) {
    introJs().setOption('doneLabel', 'Next Page &rarr; ').start().oncomplete(function() {
        window.location.href = 'nextpage.html?multipage=true';
    });
} 
</script>

**Comment by jangti** [comment]
Hi, 
Is there any way to add other steps for oncomplete method ?
introJs().addSteps([{
						element: $('#ck-main-notification-item')[0],
    					intro: "Click here to get message notification",
    					position: 'left'
					},
					{
						element: $('#ck-chat-enabler')[0],
    					intro: "click here for the message box",
    					position: 'top'
					}]).start().oncomplete(function(){
						**$('#ck-chat-enabler').trigger('click');**
						introJs().exit();
						introJs().addStes([{ 
							element:$('.ck-chat-user-list-group')[0],
							intro:'Choose the tabs as shown below',
							position:'left'
						},
						{	
							element:$('#ck-chat-selector')[0],
							intro:'Choose a tab for the specific chat',
							position:'left'
						}]).start();
					});

Because at this ** ck-chat-enable ** point I am opening chat box within page and introduce other steps

**Comment by juliettebeaudet** [comment]
[PROPOSING A SOLUTION] <br> 
For anyone consulting this former issue, having a multipage problem, please know that I opened a [similar issue](https://github.com/usablica/intro.js/issues/1253) which I solved with [this code (React Codesandbox)](https://codesandbox.io/s/hopeful-ramanujan-fvxmd?file=/src/Home.js). I also suggested an addition of the (already existing but so far undocumented) useful `onskip` callback on the official introjs documentation.
