### ISSUE TITLE
Is the library maintained?

### ISSUE THREAD

**Issue by neitwood** [usablica/intro.js#2039]
## Description
I would like to know if the library is maintained in working order before using and purchasing a license. The latest version was released on August 14, 2023. Since then, there have been no commits and no answers to questions.

**Comment by binrysearch** [comment]
@neitwood Yes, we are actively maintaining the project in different branches. We will release a new version soon.

**Comment by neitwood** [comment]
@binrysearch Thanks.
I have another question.

Please tell me what does "custom theme" mean in your licenses on the page https://introjs.com/#commercial ?

If I buy a "Starter", will I be able to redefine styles for my project or not?

And is it possible to read the license text?
