### ISSUE TITLE
Source map issue intro.js": "^7.2.0", "intro.js-react": "^1.0.0",

### ISSUE THREAD

**Issue by susant123** [usablica/intro.js#2061]
I used the Intro.js in my app using "intro.js-react" package. It works fine but its annoying to see "Failed to parse source map from 'D:\1 proj1\myProj\src\index.ts' file: Error: ENOENT: no such file or directory, open 'D:\1 proj1\myProj\src\index.ts'".

I think it should point to the node_modules folder as path for the source map. I see so many such errors on the console. This happens only for the intro.js. Can we get a fix for this please.

    "intro.js": "^7.2.0",
    "intro.js-react": "^1.0.0",

**Comment by binrysearch** [comment]
This should be fixed soon.
