### ISSUE TITLE
Error while setting up introJS Steps via options. If i use html attribute it works. 

### ISSUE THREAD

**Issue by akshaybheda30** [usablica/intro.js#2062]
Getting error in this code 

function it(t){if(null===t||"object"!==e(t)||"nodeType"in t)return t;var n={};for(var r in t)"jQuery"in window&&t[r]instanceof window.jQuery?n[r]=t[r]:n[r]=it(t[r]);return n}

Right-hand side of 'instanceof' is not an object
    at O (intro.module.js:10:20625)
    at Z (intro.module.js:10:27165)
    at intro.module.js:10:31145
    at intro.module.js:10:1488
    at Object.next (intro.module.js:10:1597)
    at intro.module.js:10:490
    at new Promise (<anonymous>)
    at e (intro.module.js:10:251)
    at nt (intro.module.js:10:30929)
    at t.<anonymous> (intro.module.js:10:33352)

I have webpack 4 , react 16.13.1

I am using npm to install the latest version

**Comment by akshaybheda30** [comment]
Does Jquery needs to be present globally?

**Comment by binrysearch** [comment]
No need for jQuery, no. This should be fixed in latest versions, can you give it a try @akshaybheda30?

**Comment by JLauwyck** [comment]
I just installed intro.js via npm in my Laravel Livewire application. When trying to add steps or use the JSON configuration, I too get stuck on this error. 
From what I experienced, it only crashes when trying to use 'element'.

**Comment by JLauwyck** [comment]
> I just installed intro.js via npm in my Laravel Livewire application. When trying to add steps or use the JSON configuration, I too get stuck on this error. From what I experienced, it only crashes when trying to use 'element'.

Nevermind, I got it working! Had to install the latest (beta) version via `npm install intro.js@8.1.0-beta.1 --save`. Now everything works as expected!
