### ISSUE TITLE
`8.0.0-beta.1` should be `@next` and not `@lastest`

### ISSUE THREAD

**Issue by mrleblanc101** [usablica/intro.js#2069]
I think something is wrong with how `8.0.0-beta.1` was published.
Currently, `npm outdated` list the beta as the `@latest`, but it should be marked as `@next`

**Comment by mrleblanc101** [comment]
@binrysearch You seem to be the one who created the tag on Github, possible for you to fix it on npm ?

**Comment by binrysearch** [comment]
@mrleblanc101 apologies for this mistake. Are you suggesting to publish all new beta versions as `@next`? We are planning on publish some new beta versions soon.

**Comment by mrleblanc101** [comment]
@binrysearch yes of course, this let people the choice to install the latest stable or the beta. This also prevent people running `npm upgrade` to be told that their package is outdated when it's not

**Comment by binrysearch** [comment]
@mrleblanc101 but the version number already has `-beta` in it? we're following semver to publish versions. Are you suggesting to use at next and -beta at the same time?

**Comment by mrleblanc101** [comment]
The fact that you use semver doesn't change anything for the npm registery, you need to tag your release properly. 

Currently, if a new user `npm install intro.js`, npm will default to install an unstable beta version, as npm think `8.0.0-beta.1` is the `@latest` stable release. 

Also, if someone run `npm outdated` or `npm upgrade` in an existing project their intro.js package will be marked as outdated and to be upgraded, when it actually is not outdated. 

If you tag it `@next`, like it should, it won't display as outdated and needing of being upgraded, but people will still be able to install `8.0.0-beta.1` using `npm install intro.js@next` and people running a regular `npm install intro.js` will get the latest stable release which is `7.2.0` until `8.0.0` is officially released it will become the @latest.

I recommend you read about npm tags: https://docs.npmjs.com/adding-dist-tags-to-packages

**Comment by binrysearch** [comment]
This is fixed now: https://www.npmjs.com/package/intro.js?activeTab=versions - Thank you

**Comment by mrleblanc101** [comment]
@binrysearch Thank you for the fix 🙌
