### ISSUE TITLE
Config option tooltipPosition is ignored in some cases

### ISSUE THREAD

**Issue by samiracho** [usablica/intro.js#209]
tooltipPosition config option must be used as the default one. If  I specify a programmatic definition, the tooltipPosition is always "bottom"

I solved it changing line 302:
var currentTooltipPosition = this._introItems[this._currentStep].position;

With:
var currentTooltipPosition = this._introItems[this._currentStep].position || this._options.tooltipPosition;

**Comment by afshinm** [comment]
fixed.
