### ISSUE TITLE
Elements larger than viewport will cause you to scroll to bottom of element and not see intro tooltip

### ISSUE THREAD

**Issue by philbarresi** [usablica/intro.js#215]
When you are trying to introduce an element that is longer than the viewport, introjs will scroll to the bottom of the element, making you unable to see the intro tooltip.

I have created an example [here](http://philbarresi.com/introjs/). Maybe it would make more sense to scroll to the tooltip instead of the target element?

**Comment by MaZZly** [comment]
I would like this feature as well... Annoying that the tooltip is half-visibe (in my case) and the user has to scroll up to see the info..
