### ISSUE TITLE
The problem with multi-page

### ISSUE THREAD

**Issue by soloviofff** [usablica/intro.js#229]
I have single one step on page 1, but there is only one button - skip, and by clicking on it the transition occurs to page two.

**Comment by juliettebeaudet** [comment]
[PROPOSING A SOLUTION] <br> 
For anyone consulting this former issue, having a multipage problem, please know that I opened a [similar issue](https://github.com/usablica/intro.js/issues/1253) which I solved with [this code (React Codesandbox)](https://codesandbox.io/s/hopeful-ramanujan-fvxmd?file=/src/Home.js). I also suggested an addition of the (already existing but so far undocumented) useful `onskip` callback on the official introjs documentation.
