### ISSUE TITLE
هماهنگی بیشتر با زبان فارسی

### ISSUE THREAD

**Issue by reza1615** [usablica/intro.js#232]
سلام
ممنون از ابزار خوبتان
ما در ویکی پدیای فارسی از آن استفاده کردیم و بسیار لذت بردیم فقط چند درخواست داشتم
۱-لطفاً امکانی محیا کنید تا بتوان اعداد مراحل را به صورت فارسی نوشت (عدد داخل دایره قرمز)
۲-برای موارد راست به چپ دکمهٔ بعد و قبل جابجا شود (بعد راست باشد و قبل چپ باشد)
۳-فکوس صفحه به نحوی باشد که صفحه کامنت مورد نظر را کامل پوشش دهد و نیاز نباشد کاربر اسکورال کند تا متن کامنت را ببیند
۴-صفحه‌ای در ابتدا یا انتها بتوان افزود که در آن ۳-۴ دکمه باشد و بتوان خوش‌آمد گویی یا پایان کار را به کاربر اطلاع داد مثلا اگر در ابتدا باشد به کاربر خوش‌آمدگویی کند وبگوید تور ۱ یا تور۲ یا تور۳ و... را می خواهی؟
۵-امکان پیوند دادن به صفحات وب از درون کامنت‌ها مقدور باشد مثلا کلمهٔ ایران قابل کلیک باشد
با تشکر الان ابزار در ویکی پدیای فارسی فعال است و می توانید آن را در
https://fa.wikipedia.org/wiki/%DB%8C%DA%A9_%D9%85%D9%82%D8%A7%D9%84%D9%87_%D9%86%D9%85%D9%88%D9%86%D9%87
مشاهده کنید. (بر روی دکمهٔ آموزش تعاملی کلیک کنید)
با تشکر

**Comment by afshinm** [comment]
Fixed.
