### ISSUE TITLE
Calling introJs.exit does not fire oncomplete callbacks

### ISSUE THREAD

**Issue by andrewjmead** [usablica/intro.js#242]
## **Version**

I'm using version v0.7.0 of IntroJs.
## **Problem**

`onexit()` callbacks are not fired when the tour is closed via `exit()`.

If I attach a callback via `onexit()`:

```
intro.onexit(function () {
    console.log('exiting');
});
```

It is not called when the tour is closed via calls to `exit()`.
`intro.exit()``
## **Expected Result**

I would expect callbacks registered with `onexit()` to be fired. They are not.

**Comment by esrefatak** [comment]
@afshinm I guess IntroJS project is down, will not continue, right?

**Comment by afshinm** [comment]
Fixed.
