### ISSUE TITLE
onexit not fired if intro exited via intro.exit()

### ISSUE THREAD

**Issue by mgiraldo** [usablica/intro.js#255]
For this sample code:
test.html

``` html
<a href='#' data-intro='Hello!<br />wait 3 seconds for automated close (onexit will not fire)'>one</a>

<a href='#' data-intro='Hello step two!'>two</a>
```

test.js

``` javascript
    var timerID;
    var myAlert = function () { alert("tutorial over!"); };
    var myintro = introJs();
    myintro.onexit(function() {
        myAlert();
        window.clearTimeout(timerID);
    });
    myintro.start();
    var quitIntro = function () {
        alert("automated quit!");
        myintro.exit();
    }
    timerID = window.setTimeout(quitIntro,3000);
```

The `onexit` event is not fired when the intro is closed programmatically via `intro.exit()`.

I made a [JSFiddle for this](http://jsfiddle.net/2mfm6/).

**Comment by guncha** [comment]
Just got caught by the same issue. How this makes sense is beyond me.

**Comment by AdriVanHoudt** [comment]
This has been added here https://github.com/usablica/intro.js/commit/66b2f1a18ba143eca593fc4f05e1b5861f0d5cce#diff-42068bed56449c4ec84ddf8745e56b7cR426
which is 1, weird to have that in that commit, 2 an undocumented fix, 3 not yet released

**Comment by afshinm** [comment]
Fixed.
