### ISSUE TITLE
onbeforechange - onafterchange

### ISSUE THREAD

**Issue by ric79** [usablica/intro.js#269]
hello,
I don't understand how to use these two methods.

Let us suppose this:

``` javascript
var $myIntro = introJs();
$myIntro.setOptions({
    steps: [{
        element: '#id1',
        intro: "Blah Blah1"
    }, {
        element: '#id2',
        intro: "Blah Blah2"
    }, {
        element: '#id3',
        intro: "Blah Blah2"
    }, {
        element: '#id4',
        intro: "Blah Blah3"
     }]
});
```

I need:
- to open a bootstrap modal [`$('#loadingModal').modal('show');`] before step id2 
- to close the bootstrap modal [`$('#loadingModal').modal('hide');`] after step id3

Is it possible to do this using onbeforechange - onafterchange?

Riccardo

**Comment by guillaumegarcia13** [comment]
Using __currentStep_ may help too (because in my case, targetElement is always empty):
```
$myIntro.onbeforechange (() => {
    let currentStep = steps[$myIntro._currentStep];
   // do stuff
});
```
