### ISSUE TITLE
Bootstrap dropdown menu

### ISSUE THREAD

**Issue by jbaudens** [usablica/intro.js#271]
I am having an issue trying to add a step that would target a bootstrap dropdown menu. 

What I would like to do is have the step toggle the dropdown <ul> and then potentially have "substeps or subsequent steps" go over the various <li>.

I tried a few things using onbeforechange and trying to toggle the dropdown.
$('a.dropdown-toggle').dropdown('toggle');
This is unsuccessful. 

Is this feature available in IntroJS. If yes what am I doing wrong. If no is this something that will be available later.

Thanks

**Comment by alerancur** [comment]
I'm having this very same issue. Did you find a solution?

**Comment by Maado** [comment]
i am working on making a callback funcition to each slice of the intro

**Comment by paresh-2016** [comment]
What is the fix for this issue?
