### ISSUE TITLE
intro.js with bootstrap3 dropdown

### ISSUE THREAD

**Issue by jbaudens** [usablica/intro.js#272]
I am trying to have my steps go over a bootstrap3 dropdown but I cannot get it to work.

Here is an example I tried:
https://github.com/jbaudens/intro.js/blob/master/example/programmatic/Bootstrap3-Dropdown.html

I try to get the menu to pop up using onbeforechange but it disappears right away.

**Comment by alerancur** [comment]
I'm having the same issue. Did you find a solution?

**Comment by Nicenonecb** [comment]
Now，I'm having the same issue too. Did you find a solution?
