### ISSUE TITLE
intro.js have something wrong working with bootstrap

### ISSUE THREAD

**Issue by zombiezlk** [usablica/intro.js#316]
When there is a bootstrap.css file working with intro.js and introjs.css , the width and height of introjs-helperNumberLayer will reduce which makes the style of  introjs-helperNumberLayer very weird . 
   It seems like the border width and padding of introjs-helperNumberLayer will be counted in its height and width.

**Comment by clarmso** [comment]
Here's the demo on JSFiddle: http://jsfiddle.net/4evx1537/3/

Note that the number in the upper left corner is not centered.
![screen shot 2015-11-02 at 1 08 30 am](https://cloud.githubusercontent.com/assets/1740517/10875254/42bd8c58-80fe-11e5-94be-1e274b9c69d2.png)

**Comment by leonfong** [comment]
@clarmso edit introjs.css _line-height: 20px;_ to 10px; in line 110
