### ISSUE TITLE
Functionality to set custom width, height and offset for the tooltip like in hopscotch.

### ISSUE THREAD

**Issue by anupamapanchal** [usablica/intro.js#326]
Hey, I have moved from hopscotch to intro.js for my site because of its highlighting the section feature. But I still think that the intro.js misses on features listed below when compared to its competitors
1.  Setting the custom width and height of the tooltip for each step.
2.  Setting the offset position for the tooltip as well as the arrow for each step.
3.  Setting the z-index and informing about the fixed positioned elements.

There are more such small and helpful options and events possible.

It would be great if we can build these features onto intro.js and make intro.js the first choice of all.

Let me know if you need any help?

**Comment by dchaddock** [comment]
Any movement on this or a possible solution? I need to change the width of my tooltips since I have a larger than normal amount of text to display.

**Comment by afshinm** [comment]
@dchaddock you can use custom css rules to alter the size of tooltips.
