### ISSUE TITLE
Cannot define step programmatically

### ISSUE THREAD

**Issue by ericenns** [usablica/intro.js#332]
When I define step in my json, it is ignored and starts from 1 for the page again. I would either like to set step in each data structure or set a starting number for multi page programmatic intros.

**Comment by sbludlow** [comment]
I'm running into a similar issue.  When intro is initialized, some ajax loaded elements are not on the page (but are triggered from a prior step) and therefore are not rendered properly when their step is active.

**Comment by tracethompson** [comment]
any workarounds for this? having the same problem - dynamic elements cause the intro box to be placed in the center of the screen

**Comment by godd9170** [comment]
+1
