### ISSUE TITLE
disableInteraction broken (i.e. always active)

### ISSUE THREAD

**Issue by Snaptags** [usablica/intro.js#356]
Any of the commits AFTER Sep 21, 2014 broke the new disableInteraction feature, rendering introJS completely unuseable. disableInteraction seems to be always active now and cannot be turned off.

**Comment by masaki925** [comment]
+1 works. Thanks @yuvale

**Comment by nedyalkov** [comment]
Do somebody knows why the PR is not merged yet? It seems it works great. It solved the problem for me as well.

**Comment by sup3rb0wlz** [comment]
This looks great in #424 I was wondering if there is a way to listen to a click on the element and go to the next step. This would be great for having a user follow along, and guide them every step. This could be done manually in the OnChange probably, but it would be nice to have built in I think

**Comment by ka7eh** [comment]
You might want to update the minified version of intro.css too!

**Comment by kleinph** [comment]
This issue was solved with #368. So I think it should be closed.
