### ISSUE TITLE
Option to disable overlay layer

### ISSUE THREAD

**Issue by quanghoc** [usablica/intro.js#359]
Sometime we need to allow users to interact with other DOM while showing the intro. The "overlay" kind takes over the whole screen. Making overlayOpacity=0 doesn't solve the problem as you cannot click anything outside.

I am proposing a way to disable this overlay layer completely.

If there is workaround / alternative, please let me know

**Comment by buremba** [comment]
`pointer-events:none` may also help as a workaround.
