### ISSUE TITLE
Placement issues with 1.0.0 + probably Bootstrap 3.2.0

### ISSUE THREAD

**Issue by kviktor** [usablica/intro.js#361]
with 0.9.0 and this CSS:

```
.introjs-helperLayer *,
.introjs-helperLayer *:before,
.introjs-helperLayer *:after {
  -webkit-box-sizing: content-box;
    -moz-box-sizing: content-box;
      -ms-box-sizing: content-box;
      -o-box-sizing: content-box;
          box-sizing: content-box;
}
```

![kijeloles_024](https://cloud.githubusercontent.com/assets/1112058/4808848/8acfa084-5ea5-11e4-8cdd-1effe5871cb0.png)

with 1.0.0

![kijeloles_025](https://cloud.githubusercontent.com/assets/1112058/4808850/8e33130a-5ea5-11e4-8e68-3884de092c9e.png)

**Comment by thotmx** [comment]
@connyay Thanks a lot. That worked for me. I hope @afshinm could merge this.
