### ISSUE TITLE
Feature Request: Add ability to track step progress in callbacks

### ISSUE THREAD

**Issue by Michelangelo9** [usablica/intro.js#365]
Hi, 

Would it be possible to have a user-friendly way  of tracking what the current step is on the onchange callback so that I can dynamically change the page accordingly for interactive elements. 

Currently I can do so by accessing the object attribute below, but would be nice if the plugin provided a cleaner way.

$(this)[0]._currentStep;

Otherwise, excellent plugin!

**Comment by dahoo** [comment]
+1
