### ISSUE TITLE
oncomplete callback isn't called when hitting Enter with Done focused

### ISSUE THREAD

**Issue by yuvale** [usablica/intro.js#366]
Example here: http://jsfiddle.net/LpLtnyrs/
On step 2 the Done button is initially focused. Hitting Enter completes the intro but the oncomplete callback isn't called.
If there's just one step, the Done button isn't focused (that's another (minor) issue), so at least 2 steps are required to demonstrate the problem.

**Comment by afshinm** [comment]
fixed.
