### ISSUE TITLE
starting one intro from oncomplete callback of another

### ISSUE THREAD

**Issue by jfrueh** [usablica/intro.js#383]
I'm trying to start a new intro from the oncomplete callback of another...

intro1 = introJs();
intro2 = introJs();

intro1.onComplete(function(){
     if (condition){
        intro2.start();
   }
});

after the call to intro2.start(), I'm just left with an empty overlay that blocks the UI.

A work-around I've found to this is to wrap the call to intro2.start() in a timeout so a slight delay is applied:
setTimeout(function () {
                    intro2.start(); 
}, 250);

I was surprised that there wasn't a way to launch one intro from the completed callback of another.  Is there a proper way to do this or is this a bug?

Thanks for the great plugin - really cool!

**Comment by ali-codehoppers** [comment]
I am facing the same issue, in older version we are the overlay comes and goes. In the latest version it does not highlight the elements correctly.
