### ISSUE TITLE
intro.js not working on https://

### ISSUE THREAD

**Issue by sachy123** [usablica/intro.js#387]
untill i had http:// it worked, when i switched to https:// its not working as it should! i have downloaded all the files on my localmachine and they are on the server directory ( all js files)

**Comment by dvorapa** [comment]
I don't think it is a problem of intro.js or? Do other local js files work? Have you set all preferences in `httpd.conf` (for Apache) needed to be set to make local JS files work? And for CDNs: Have you set CORS correctly? Switching to https is complicated all the time and I think, that there is no way how to write JavaScript to not work on HTTPS, and therefore you might try to search where is that problem.

**Comment by sachy123** [comment]
Extremely apologize!! I missed one of the files on the server, its working like a charm
