### ISSUE TITLE
CDN delivered CSS is incomplete

### ISSUE THREAD

**Issue by erullmann** [usablica/intro.js#392]
I noticed that the introJS CSS file that's delivered via the jsdelivr CDN is incomplete and doesn't contain all the necessary styles. Hope this can be fixed or that an alternate CDN can be provided.

http://cdn.jsdelivr.net/intro.js/1.0.0/introjs-rtl.min.css

**Comment by jimaek** [comment]
https://raw.githubusercontent.com/usablica/intro.js/v1.0.0/minified/introjs-rtl.min.css and http://cdn.jsdelivr.net/intro.js/1.0.0/introjs-rtl.min.css are identical

**Comment by erullmann** [comment]
Oh shoot this is kinda more my bad. I included the right-to-left css without the normal CSS and thought it was incomplete. I didn't really read what css file the CDN was delivering and thought it was the regular one. Could we get the full intro.css on the CDN though?

**Comment by jimaek** [comment]
We already host it //cdn.jsdelivr.net/intro.js/1.0.0/introjs.min.css
I guess you didnt press the "show more" button :)

**Comment by erullmann** [comment]
I guess I did not. Nevermind. :) And thanks.
