### ISSUE TITLE
publish 1.0 on npm

### ISSUE THREAD

**Issue by j0hnsmith** [usablica/intro.js#394]
https://www.npmjs.com/package/intro.js has 0.9.

**Comment by scottbrady** [comment]
I'll second this request.  I was surprised to see 0.9.0 when I did an npm install.

**Comment by elfreyshira** [comment]
+1
Having 1.0 on npm would be nice.

**Comment by Firfi** [comment]
> Jan 19

That's a quite important thing, I think. Second this.

**Comment by Kreozot** [comment]
@usablica, Please, do the ```npm publish```! Thank you!
