### ISSUE TITLE
Can this work on elements inside a fixed footer? (added plnker)

### ISSUE THREAD

**Issue by constellates** [usablica/intro.js#401]
I'm trying to use intro for an element inside of a fixed position footer. The way in which intro climbs up every parent element and forces "position: absolute !important" is causing this fixed footer to break and hop up the page a bit because it's no longer fixed to the bottom. Is this a known issue, or should this be possible to do and I'm just doing it wrong?

**Comment by constellates** [comment]
Here's a plnkr example. Click the left bottom nav button to start intro.js. http://plnkr.co/edit/zNxKXV?p=preview

**Comment by majorye** [comment]
same problem for me ,opppppps !

**Comment by rockcoder23** [comment]
you can  set the option 'scrollToElement'  to false.  this is a bug maybe, I have a similar situation with you. you can see the issue below:

https://github.com/usablica/intro.js/issues/400

**Comment by Gadgetdude** [comment]
+1 for solving this issue. Any updates on this (or #400), @afshinm?

**Comment by 0xPr0xy** [comment]
[Guide.js](https://github.com/Dozyatom/guide.js) has a different implementation, that does not suffer from the z-index with fixed elements issue in WebKit
