### ISSUE TITLE
Display problem

### ISSUE THREAD

**Issue by sofianegargouri** [usablica/intro.js#405]
Hi !

I just tried to add Intro.js to my website, I included the minified JS and CSS, and this is what i get:
![image](https://cloud.githubusercontent.com/assets/4323986/6245831/ef89db78-b762-11e4-89e8-5e9539723853.png)

As you can see, there is no modal when i click on the button, but there is the text just before the end of my body

![image](https://cloud.githubusercontent.com/assets/4323986/6245851/1565bd62-b763-11e4-9e0e-3ad4d6006c6d.png)

**Comment by BKD-Digital** [comment]
Likely an invalid asset URL/path.

**Comment by skeletalbassman** [comment]
This is for sure an invalid path. I just had the same issue and it was just because I put the wrong path to the stylesheet.
