### ISSUE TITLE
Question: can I set a class to "introjs-helperLayer"?

### ISSUE THREAD

**Issue by lizfranco** [usablica/intro.js#406]
Can I set a class to 'introjs-helperLayer' so I can add different styles to the steps?

**Comment by mrmading** [comment]
You can simply use Jquery:
<script>
    $( document ).ready(function() {
        $( ".introjs-helperLayer" ).addClass( "myClassWithOverridingStyles" );
    });
</script>

**Comment by mrmading** [comment]
Actually you can just use this:

data-highlightClass: Optionally append a CSS class to the helperLayer
