### ISSUE TITLE
Implement cookies

### ISSUE THREAD

**Issue by alexandernst** [usablica/intro.js#413]
It would be useful if Introjs could run only once (based on cookies).

**Comment by alexlouden** [comment]
I'm using local storage at the moment - `show_intro()` is called on page load.

```javascript
function show_intro() {
    if localStorage.getItem('intro_shown') {
        // already shown
        return
    }
    localStorage.setItem('intro_shown', true)
    intro = introJs()
    intro.setOptions([ ... ])
    intro.start()
}
```

**Comment by isdaft** [comment]
https://github.com/isdaft/introjs-dropcookie-onhint

**Comment by hajimurtaza** [comment]
> https://github.com/isdaft/introjs-dropcookie-onhint

Can you verify this @afshinm @bozdoz ?
