### ISSUE TITLE
Interaction with elements in Firefox

### ISSUE THREAD

**Issue by ghostangel77** [usablica/intro.js#418]
I can't click buttons or links in Firefox.
![intro](https://cloud.githubusercontent.com/assets/5560483/6718699/847bc7a6-cd83-11e4-9128-a54e7cfd8040.PNG)

**Comment by GoomiChan** [comment]
I worked around this by adding the css below after the intro.css import.

```
.introjs-tooltipReferenceLayer
{
    pointer-events:none;
}
```

**Comment by driannaude** [comment]
Good catch @GoomiChan. I was headed down the JS path for solving this problem ... Simple and elegant.
