### ISSUE TITLE
Make Highlighted Area Clickable

### ISSUE THREAD

**Issue by NickBolles** [usablica/intro.js#424]
I want to make the button that I was highlighting clickable, and then continue to the next step. Is this possible? I know that I can make it clickable with

```
.introjs-overlay,
.introjs-helperLayer,
.introjs-tooltipReferenceLayer{
   pointer-events:none;
}
```

But How can i listen to the click and go to the next step of the tutorial? Can Intro.js have an option to listen to the button event, or to the click on the highlighting layer to go to the next step?

**Comment by xaviesteve** [comment]
+1 :+1: 

Would love to see this feature too. 
It makes a lot of sense to allow the user to do things along with the instructions.

**Comment by xaviesteve** [comment]
There's a fix here #368 :)

**Comment by sup3rb0wlz** [comment]
Awesome! Anyone know if there is anyway (besides manually) to listen to the button click and move to the next step?

**Comment by hoschnok** [comment]
this is a bug. .introjs-tooltipReferenceLayer needs lower z-index then .introjs-helperLayer . that's it. I will create a pull request for this.

**Comment by sup3rb0wlz** [comment]
It looks like there is already a pull request as @xaviesteve referenced. It's just not merged yet for some reason...

**Comment by hoschnok** [comment]
too bad. this little bug destroys core functionality. great tool tho.

**Comment by NickBolles** [comment]
#368 was completed, closing this issue
