### ISSUE TITLE
Ignore hidden elements

### ISSUE THREAD

**Issue by DanielHoffmann** [usablica/intro.js#431]
Hello, if I have some hidden elements in my page that I don't want introJs to step through them, unless they are visible. I think an option to do that is required as any workaround would be quite ugly, like removing the data attributes from the tags when hiding the elements and re-adding them once they are visible.

**Comment by renanleandrof** [comment]
+1 to this feature.

**Comment by gigadigito** [comment]
+1 para este recurso.

**Comment by decadehew** [comment]
+1

**Comment by anitr** [comment]
I was using version v2.7.0, with option: jQuerySelector. So, I was able to add something like:

intro.setOptions({
                jQuerySelector: true,
                steps: [
                    {
                        element: '.presentation-element:visible',
...

So, I could add jQuery selector :visible that worked.

But now, I upgraded to version 2.9.3 and there is no more jQuerySelector option!!

**Comment by tjhunkin** [comment]
+1
