### ISSUE TITLE
Does not release keypress listeners on exit

### ISSUE THREAD

**Issue by acarnwath** [usablica/intro.js#433]
Please see this sample:
https://jsfiddle.net/xe9vh35f/

If `introJs().exit()` is called, the tooltips are dismissed, but if a user hits "enter" or the left/right arrow keys, the intro tooltips continue to be opened (sidenote: there is no overlay when they are open).

**Comment by piotrf** [comment]
I’m experiencing the exact same issue. Any clue how to get around it?

**Comment by thekirtan** [comment]
```
var intro = null;
$(document).ready(function () {

   intro = introJs();
     intro.setOptions({
        steps: [  ],
        exitOnEsc: false,
        exitOnOverlayClick: false,
        showStepNumbers: false,
        showBullets: false,
        disableInteraction: true,
        skipLabel: 'Exit',
        scrollToElement: true
    });

});

function exitTour() {
    intro.exit();
}

```


I had same issue, and solved it by this way.

**Comment by swapnil0545** [comment]
Need to fix the same issue. Any help other than above?

**Comment by bozdoz** [comment]
@thekirtan has illustrated the **proper way** to exit an introJs tour.  

**Here's the problem**:

In the jsfiddle from @acarnwath an instance of introJs is created in an onclick handler:

```html
<a 
  href="javascript:void(0);" 
  onclick="javascript:introJs().start();">Show me how</a>
```

Implemented in this way, **there is no way to get the reference to that instance**.  Note that this will create a **new** instance:

```javascript
$(".demo-exit").on("click", function() {
    introJs().exit(); 
});
```
So, basically, you're exiting an instance that wasn't started.   I'm going to submit a PR to more reliably deal with events and add a helper method for `instances`; although I'm not sure it makes sense to deal with it in this way.  Something like this:

```javascript
introJs.instances[0].exit();
```
