### ISSUE TITLE
Multi-page demo is throwing error

### ISSUE THREAD

**Issue by lamoni** [usablica/intro.js#434]
This isn't an issue with the code (I don't think, anyway), but the example for multi-page is broken.

It goes to the second page just fine, and then after hitting Next once, it throws:

```
TypeError: Cannot set property 'className' of null
http://usablica.github.io/intro.js/intro.js:745
```

**Comment by gsivaprabu** [comment]
I have comment below line is working now
![comment](https://cloud.githubusercontent.com/assets/2444608/14709555/d782c12e-07ee-11e6-8f9b-9f43390ce0f4.png)


` //oldReferenceLayer.querySelector('.introjs-bullets li > a.active').className = '';`

**Comment by xmon** [comment]
#619 merged didn't solve it. The problem continues with version 2.5.0, as you can see in the [demo](http://introjs.com/example/multi-page/second.html?multipage=true)
