### ISSUE TITLE
How can I set in JSON Step number / priority - Or better way to start from specific part?

### ISSUE THREAD

**Issue by iq-dot** [usablica/intro.js#436]
Is there a way to define the step number in the JSON object? e.g.:

```
{
element: '#mybtn',
intro: 'button',
step: 2
}
```

?

I am basically trying to create a multi-section intro, which due to the tech stack (AngularJS) and single page nature, I need to rely on step numbers to specifically sub-divide parts of my IntroJS object using steps.

Ideally it would be great if I could sub-divide using labels instead:

```
{
section1: [
 {
   element: '#mybtn',
   intro: 'button',
   step: 2
  }
]

IntroJS.start('section1');
```

Now I don't think something like that exist but the step numbers exist in the 'data-step' attributes so is there an equivalent in the programmatic way?

Thanks

**Comment by krngrvr09** [comment]
One of the ways is to define different tours for different sections.

Eg.
```
var feature1 = introJs();
var feature2 = introJs();

feature1.setOptions({
    steps:[
        {
            ...
        },
        {
            ...
        },

]
})
.oncomplete(function(){
    setTimeout(function(){ feature2.start(); },500)
})

feature1.setOptions({
    steps:[
        {
            ...
        },
        {
            ...
        },

]
});
```

**Comment by donaldwasserman** [comment]
I took a slightly different approach by using a custom data-attribute, then match that 'token' against my JSON array: 

```json
{
        "token": "global_pages",
        "steps": [
          {
            "intro": "asdf."
          },
  ```

```html
<button class="button js-start-tour" data-token="global-pages>Click Me!</button>
```

*then*

(see underscore docs, btu you can do this natively as well...)

```js
$('.js-start-tour).on('click', function() {
  var tour = _.findWhere(parsedJson, {token: token});

pageTour = introJs();

pageTour().start()
});
```
