### ISSUE TITLE
Skip and Exit button?

### ISSUE THREAD

**Issue by cmosboss** [usablica/intro.js#442]
So In the docs how it shows the setup of an "Exit" type button is by adding a skip button and setting the label to exit, this works for me except in the last step. At the end you can set the "Done Label" which is the message that shows up at the end, I currently need two of these. All of my current introJS are set with a done label of "Next Page" so that they can continue on with the tutorial, however I also want an exit button so that they do not have to keep going. So right now I have a "Next page" button that fires the oncomplete action, but is there anyway to have two buttons?

**Comment by msakhawat** [comment]
something like this. 
https://github.com/usablica/intro.js/commit/c26b69c8770befaf60a69f3060859b1210c93600
