### ISSUE TITLE
how to start intro.js tour only on first visit to website

### ISSUE THREAD

**Issue by icase** [usablica/intro.js#443]
I put the code into my website pages. it works normal. but after the first visit, it also display one time on the pages. the script I set:

<script type="text/javascript">introJs().start();</script>

How to set it is correct?

I don't how to write script code, can you help me?

**Comment by saurabh-pathak94** [comment]
Create a button or a clickable element : 
 <a class="class_name" href="javascript:void(0);" onclick="javascript:introJs().start();">Tour this website</a>
and set the data-step and data-intro for the elements you'd want to highlight.

**Comment by icase** [comment]
Thx. But I hope anyone first visit, it auto run. how do I write the code?

**Comment by saurabh-pathak94** [comment]
@icase It'll run only if the user presses the button that is assuming you're not running the javascript code on body load.

**Comment by icase** [comment]
@saurabh-pathak94  auto（）support auto run isnt it?

**Comment by saurabh-pathak94** [comment]
@icase where are u getting the auto() function?! 
Please post the code.

**Comment by icase** [comment]
@saurabh-pathak94  here:

https://github.com/usablica/intro.js#introjsstart

**Comment by ysjwang** [comment]
@icase it sounds like you're trying to have it remember if a user has seen it before or not. I don't believe this comes native in the library - you'd have to write your own storage mechanism to track if a user has seen it before or not. This could be either in your server-side database or via client-side cookies, or any variation in between.

**Comment by icase** [comment]
@ysjwang Yes, you are right! But I don't know if this part of the code is included.

**Comment by ysjwang** [comment]
@icase as far as I know it's not, as this is something that each person would probably implement differently. I'm working on open-sourcing the implementation I have for using a combination of redis/cookies to memoize this, but I haven't really seen a consistent manner that people approach this.

**Comment by radiodario** [comment]
just add a flag to `localstorage` specifying that the user has done the intro

```javascript

// add a flag when we're done
introJs.oncomplete(function() {
  localStorage.setItem('doneTour', 'yeah!');
})

// and check for it when deciding whether to start. 
window.addEventListener('load', function() {
  var doneTour = localStorage.getItem('doneTour') === 'yeah!';
  if (doneTour) return;
  introJS().start()
}
```

just make sure you also set the flag when the user skips the tour - you don't wanna annoy your users!

**Comment by HornKild** [comment]
Hi, when I use the window.**addEventListener** it fails to load introJS(), any idea what could be wrong ?

Please find my code : 
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/intro.js/2.4.0/intro.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/intro.js/2.4.0/introjs.min.css" />

<script>
introJs().oncomplete(function() {
  localStorage.setItem('doneTour', 'yeah');
});
introJs().onexit(function() {
   localStorage.setItem('doneTour', 'yeah');
});
window.addEventListener('load', function() {
  var doneTour = localStorage.getItem('doneTour') === 'yeah';
  if (doneTour) return;
  introJS().start();
});
</script>
```

**Comment by HornKild** [comment]
This doesn't work for me :(

**Comment by p10ns11y** [comment]
Write a util function something like this. if your website has a flow 

user visits `/createStore` and provides details. After signedup you redirect to them to `/dashboard`

Then inside `/dashboard` try to detect where it is coming from only one time it would come from `/createStore` other times it might be `/login` or someother redirects. 

if above condition met invoke introjs

```
detectIfFirstLogin() {
    // const { referrer,  } = document;
    if (document.referrer) {
      const linkElm = document.createElement('a');
      linkElm.setAttribute('href', document.referrer);
      if (/createStore/.test(linkElm.pathname)) return true;
    }

    return false;
  }
```

**Comment by samir07** [comment]
@radiodario This doesn't work for me...@afshinm no errors as such..local storage storing the values. Please, let me know the best solution for this. Thanks.

**Comment by bozdoz** [comment]
@samir07 @radiodario gave the best solution for this.  Could you share details about your browser? Also if you have localStorage, and you can see that localStorage is storing the values, I have no idea why that script wouldn't work.

**Comment by samir07** [comment]
@bozdoz Thanks for your kind reply, I'm using the latest version of introjs 1.7,  oncomplete and onexit functions doesn't work for me, tried inspecting no errors, idk they don't get fire on Done and Exit Button.

**Comment by ArunEdathadan** [comment]
From @radiodario 
modified  a bit

    var introguide = introJs();


    // and check for it when deciding whether to start.
    window.addEventListener('load', function () {
        var doneTour = localStorage.getItem('EventTour') === 'Completed';
        if (doneTour) {
            return;
        }
        else {
            introguide.start()

            introguide.oncomplete(function () {
                localStorage.setItem('EventTour', 'Completed');
            });

            introguide.onexit(function () {
                localStorage.setItem('EventTour', 'Completed');
            });
        }
    });

**Comment by FotieMConstant** [comment]
Thanks @ArunEdathadan, this works for me!

**Comment by Jazz4dev** [comment]
just Use Local storage 
Past this code into 

  ngAfterViewInit(): void {
  if (localStorage.getItem('screenLoaded') === 'yes') {
//here u can simply empty
    } else { 
//here u can call the intro function like that 
      localStorage.setItem('screenLoaded', 'yes');
      this.initIntroJs()
    }
}

**Comment by cavaquinho93** [comment]
For anyone coming to this later... the introJs API now provides a method for this (I'm not sure if this was available before or not). You can either display a dialog to the user where they check a "Don't show again" checkbox, or you can set this manually using `introJs().setDontShowAgain(true)`. In this case, you could attach this to the `beforeunload` event on the window object.

Just make sure this feature is enabled by using `introJs().setOption("dontShowAgain", true)`

Under the hood, introJs sets a cookie whose parameters are configurable using [various options](https://introjs.com/docs/intro/options#dontshowagain)
