### ISSUE TITLE
issue in multipage intro example

### ISSUE THREAD

**Issue by manojverma086** [usablica/intro.js#466]
![Uploading Screenshot from 2015-09-17 20:12:17.png…]()
I tried it and when introduction finishes on last page then  there is an error:-  "uncaught TypeError: Cannot set property 'className' of null".

**Comment by gsivaprabu** [comment]
I have comment below line is working now
![comment](https://cloud.githubusercontent.com/assets/2444608/14709555/d782c12e-07ee-11e6-8f9b-9f43390ce0f4.png)


` //oldReferenceLayer.querySelector('.introjs-bullets li > a.active').className = '';`
