### ISSUE TITLE
Highlight not working properly

### ISSUE THREAD

**Issue by LulzAugusto** [usablica/intro.js#474]
Edit;
Nvm. It was a problem with my css

**Comment by LulzAugusto** [comment]
<img width="1472" alt="screen shot 2015-10-02 at 8 48 57 am" src="https://cloud.githubusercontent.com/assets/254107/10245896/8969a8be-68e2-11e5-8874-28657d89d978.png">

**Comment by afshinm** [comment]
Cool.
