### ISSUE TITLE
Scroll to element, the viewport jumps down

### ISSUE THREAD

**Issue by laerke93** [usablica/intro.js#482]
<img width="1261" alt="skaermbillede 2015-10-27 11 18 34" src="https://cloud.githubusercontent.com/assets/15340864/10755228/a19d058e-7c9c-11e5-8c14-abccb259f18f.png">

Hello. I have tried looking all the issues through, but I cannot find a solution that solves my problem. 
When I click next and the page scroll down to the next step, the enlightened area and explanation box jumps to the bottom of page. How can that be? 

Yours sincerely 
Lærke

**Comment by julienchepa** [comment]
Hi, 

I'm having the same issue. 

Did you find any solution to solve it ?

**Comment by afshinm** [comment]
We have applied and will apply more patches in the next few versions for this.
