### ISSUE TITLE
intro.js does not consider the margin-top on html tag

### ISSUE THREAD

**Issue by pratham2003** [usablica/intro.js#483]
I noticed this problem in Wordpress.
When the Wordpress admin bar is being displayed it sets a margin-top: 48px on the html tag. As intro.js is not taking that into consideration the 'window' which intro.js creates appears 48px above the selector.

Screenshot: http://i.imgur.com/hy6KIVX.png

**Comment by christianwach** [comment]
Yup, confirmed here. I use a simple jQuery check for `margin-top` in `_getOffset()` to correct this. Would be nice not to have to, though.
