### ISSUE TITLE
Problem with bootstrap modals

### ISSUE THREAD

**Issue by sebaxq** [usablica/intro.js#485]
Hi, I'm using intro.js and I find an error when I use it on a Modal of Bootstrap. Intro.js adds a class to fix the position for elements ("introjs-fixParent") and the style "position:absolute !important;" makes that the modal moves from the center of page. I fixed the problem changing the style to "position:relative !important;" and adding this javascript code "$(window).scrollTop(0);" to fix the vertical alignement problem, this is before to launch Intro.js.

**Comment by Mmatiasn** [comment]
Thank for the temporary solution sebaxq.

**Comment by silentFred** [comment]
Also having this issue when using bootstrap 3 modals

**Comment by brunocechet** [comment]
+1 with bootstrap 3 modals

**Comment by bytebrain** [comment]
I've fixed it. I've added this to my css, and your **modal elements** should be **at the end of your** `<body>` and not in any child element, or else all you'll get strange positioning.

```css
.introjs-fixParent.modal,
.introjs-fixParent.modal-dialog {
  position: relative !important;  
}
```

Fixed my modals with this:
```js
$(document).ready(function(){
    $('div.modal').appendTo('body');
});
```

**Comment by afshinm** [comment]
fixed.
