### ISSUE TITLE
Doesn't work on children of absolute/relative positioned elements

### ISSUE THREAD

**Issue by m-mitchell** [usablica/intro.js#50]
![introjs_stackingcontextbug](https://f.cloud.github.com/assets/169674/278236/7cac96ea-90e0-11e2-92b6-b8eca8ddb753.png)

Source for test here: http://pastebin.com/ztyuYjK7
More info about stacking contexts here: http://tinyurl.com/cnxomh5

I think the problem is that the introjs elements are added to the global stacking context, regardless of the stacking context of the target. This causes the overlay and helper layers to be stacked on top of the desired target, instead of underneath.

**Comment by danielgolden** [comment]
Why is this issue closed? I'm still experiencing this bug:

![screen shot 2016-11-14 at 3 42 55 pm](https://cloud.githubusercontent.com/assets/812989/20282042/0889c5c6-aa81-11e6-830e-3126801b8eb9.png)

**Comment by yassinphilip** [comment]
This does it (hiding the highlighted elt) for `position: fixed` too ; switching from `fixed` to `absolute` solves the problem indeed. Problem is I _need_ `fixed` :(
