### ISSUE TITLE
Scrolling does not show entire intro tooltip

### ISSUE THREAD

**Issue by beedaan** [usablica/intro.js#503]
I recently tried setting `scrollToElement` equal to `true`.  The browser will scroll to show my element, but it will cut off the padding of the tooltip on the bottom.  Here is a [jsFiddle](https://jsfiddle.net/beedaan/te56sct0/) demonstrating the issue.

Here is a screenshot of what I am talking about:
![screen shot 2015-12-22 at 4 54 27 pm](https://cloud.githubusercontent.com/assets/884240/11967056/e795b1e6-a8cd-11e5-91f3-467b2c14eef0.png)

I inspected the element and I found that the part of the tooltip that was getting cut off was the padding.
![screen shot 2015-12-22 at 4 57 58 pm](https://cloud.githubusercontent.com/assets/884240/11966963/35644938-a8cd-11e5-9b50-582e015af0d5.png)

I suggest the behavior of the `scrollToElement` is changed so that the entire tooltip is displayed, including the padding.  Perhaps there should even be a 10px offset around the tooltip, so it's not touching the boundary of the viewport?

**Update** Upon inspection of the source code, it looks like the size of the tooltip is not taken into consideration at all, just the target element.  The default location of the tooltip is `bottom`.  The combination of these two settings will cause the tooltip to flow out of the viewport.

```javascript
var rect = targetElement.element.getBoundingClientRect(),
  winHeight = _getWinSize().height,
  top = rect.bottom - (rect.bottom - rect.top),
  bottom = rect.bottom - winHeight;

//Scroll up
if (top < 0 || targetElement.element.clientHeight > winHeight) {
  window.scrollBy(0, top - 30); // 30px padding from edge to look nice

//Scroll down
} else {
  window.scrollBy(0, bottom + 100); // 70px + 30px padding from edge to look nice
}
```

**Comment by g13013** [comment]
any new on that ?

**Comment by analog-nico** [comment]
+1

**Comment by afshinm** [comment]
Scroll padding is added to the latest version.

**Comment by analog-nico** [comment]
@afshinm Since the `scrollPadding` option still does not consider the size of the tooltip please reconsider pull request #270 and the comment I added there. Thanks a lot!
