### ISSUE TITLE
Cannot place hints on items inside a fixed position container

### ISSUE THREAD

**Issue by pg1671** [usablica/intro.js#507]
I have a header at the top of my application with position: fixed; but whenever I try to add a hint onto a child of that header the hint does not display.

If I remove the position fixed the hint is places correctly.

Is it possible to place hints inside a fixed position container?

**Comment by pml984** [comment]
I'm having the same issue, is there a work-around to this issue?

**Comment by vijayvishnu** [comment]
+1

**Comment by jeffatpf** [comment]
+1

**Comment by zoheiry** [comment]
+1

**Comment by duledjurasevic** [comment]
Was this ever fixed? What's the solution/workaround?

**Comment by dipiana** [comment]
+1
