### ISSUE TITLE
Publish 2.0 on npm

### ISSUE THREAD

**Issue by maxilev** [usablica/intro.js#511]
Do you plan to publish 2.0 version on npm? Latest available version there is 1.1.1.

**Comment by yomena** [comment]
same with bower. would be awesome to get the latest version via bower. thanks

**Comment by rogamoore** [comment]
yes please :+1:

**Comment by yomena** [comment]
I temporarily solved it by changing the intro.js entry in my bower.json file to
```javascript
"intro.js": "https://github.com/usablica/intro.js.git#2.0"
```
Now I get v2.0

**Comment by thelinuxlich** [comment]
+1 for npm

**Comment by lordakshaya** [comment]
+1

**Comment by Glavin001** [comment]
+1

**Comment by chicoxyzzy** [comment]
yep. it would be cool

**Comment by mhxbe** [comment]
+1 for npm

**Comment by JvJefke** [comment]
+1

**Comment by jeromemacias** [comment]
:+1:

**Comment by afshinm** [comment]
Hey guys,

Excuse me for this delay. I was moving to Ireland last month.

I will update the NPM and reply to all issues/PRs this weekend. 

Cheers,
Afshin

**Comment by runia1** [comment]
Please update Bower too :)  Still reporting 1.1.1 as latest

**Comment by zfoltin** [comment]
+1 bower

**Comment by afshinm** [comment]
Done.
