### ISSUE TITLE
Uncaught TypeError: intro.onhintsadded is not a function

### ISSUE THREAD

**Issue by adamplabarge** [usablica/intro.js#512]
This example does not seem to work. (https://github.com/usablica/intro.js/blob/master/example/programmatic/hint.html)

Looking for a way to hook a function in after the user clicks the next hint button.

intro.onhintclick also throws error.

**Comment by kodeine** [comment]
i am getting the same error!

**Comment by bozdoz** [comment]
I can't reproduce this.  Is this still an issue?
