### ISSUE TITLE
Something css conflicted with Bootrtrap.css

### ISSUE THREAD

**Issue by yaochiqkl** [usablica/intro.js#513]
It looks different when linked with Bootstrap.css .
The solution is add "box-sizing:content-box !important" to some layers such as 
` .introjs-tooltip {
  box-sizing: content-box !important;
} ` 
It will help.

**Comment by adamplabarge** [comment]
Remember, CSS is cascading.

**Comment by zhanghaowx** [comment]
Thanks, that helps! Fixed problem when using intro.js together with bootstrap.

**Comment by nealeu** [comment]
Hi,
I think there are more elements that require this, as bootstrap sets border-box globally.

Can this fix be prioritised please.

**Comment by afshinm** [comment]
hey guys, sorry about that issues. Can you please give me a clue to fix that? 

Added to the next release backlogs.

**Comment by nealeu** [comment]
Hi,
I think you need to be explicit about content-box for a number of classes, in the same way that you do for introjs-helperLayer.

In my case it was .introjs-tooltipReferenceLayer that needed it adding.  Perhaps add a bootstrap demo for 2.2.0, that way you'll confirm that it's working nicely.

**Comment by afshinm** [comment]
sorry about that but since v2.2.0 is already overdue, I'm going to move this to 2.3.0.

**Comment by afshinm** [comment]
ok guys, I have added the fix to the repo and also an example of Bootstrap 3 integration to the examples folder. Please let me know if you are happy with this fix. Cheers.
