### ISSUE TITLE
Angular.js app with ng-view

### ISSUE THREAD

**Issue by matisoffn** [usablica/intro.js#515]
I'm trying to implement this into my Angular.js app which uses `ng-view` to render templates into.

The `data-intro` attributes are being placed on the templates rendered by Angular.js, but the Intro.js isn't rendering.

How can I implement this into my Angular.js app?

**Comment by ashleywb** [comment]
http://code.mendhak.com/angular-intro.js/example/index.html

**Comment by maitrungduc1410** [comment]
I don't think you need directive for that.

it's simple, follow my gist to see how to run introjs on angular (>=2) project: https://gist.github.com/maitrungduc1410/68ae50b9c9a6c893959075a1c15871a8
