### ISSUE TITLE
data attribute names are invalid

### ISSUE THREAD

**Issue by glenngillen** [usablica/intro.js#519]
I've been trying to debug an issue I was having locally, and I think it might be in part due to the fact that the suggested `data-` attribute for adjusting hint position is called [`data-hintPosition`](https://github.com/usablica/intro.js/blob/8979fc6569fb405c987e1d9ebbc94113b530d6d1/intro.js#L1241-L1242). 

According to the [HTML spec](https://html.spec.whatwg.org/multipage//dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes):

> A custom data attribute is an attribute in no namespace whose name starts with the string "data-", has at least one character after the hyphen, is XML-compatible, and contains no uppercase ASCII letters.

To migrate to a standards compliant approach we'd need to support both mixed-case and lowercase variants of the settings, but deprecate the mixed-case version. 

I'm happy to submit a patch with the required change. Just wanted to make sure this is a direction y'all are happy with before I commit the time to doing it.

**Comment by sibbl** [comment]
I came across the problem while integration IntroJs into a React application. They only support attributes which are lower case only, see https://facebook.github.io/react/docs/dom-differences.html

I think React should be big enough to support it properly.

**Comment by fernandobrito** [comment]
I'm also having problems integrating a Ruby on Rails app using HAML and Intro.js, as HAML accepts a Ruby hash as HTML tag attributes and converts it to HTML following the spec above.

I upvote adding the select as an option or @glenngillen suggestion.

**Comment by afshinm** [comment]
that's correct. I will work on this. That would be great if someone sends a PR, too.
