### ISSUE TITLE
Disabling 0.3 sec timeout

### ISSUE THREAD

**Issue by arahansen** [usablica/intro.js#523]
I'm not liking the brief pause between intro tooltips.

According to this comment,
https://github.com/usablica/intro.js/blob/master/intro.js#L800
there is a timeout between showing intros to account for the CSS animation.

If I were to disable this transition animation, would it be safe to remove this 350 ms timeout?

Maybe this could be implemented as a feature?

**Comment by mdanzinger** [comment]
If you want to remove the brief pause, you can just remove the timeout (or decrease the timeout) from line 863 https://github.com/usablica/intro.js/blob/master/intro.js#L863

**Comment by afshinm** [comment]
I don't think this could be a feature at the moment but you can alter this line: https://github.com/usablica/intro.js/blob/master/intro.js#L878
