### ISSUE TITLE
Intro JS z-index issue on IE and chrome when working on partial views

### ISSUE THREAD

**Issue by Muthukumaruma** [usablica/intro.js#530]
its working fine when i give direct single page, but partial views i am getting only white background on IE and chrome. Firefox working fine. please help me.

**Comment by rattrayalex** [comment]
I am having this problem as well. 
![screen shot 2016-04-18 at 1 48 53 pm](https://cloud.githubusercontent.com/assets/704302/14619412/53333f2c-056c-11e6-8315-d1167bec3841.png)

Displays normally in Firefox, and when the related div is not loaded with ajax. 
Relevant code: 

```js
$myElement.html(htmlFromServer);
$myElement.addClass('animated');
$myElement.show();
```

**Comment by rattrayalex** [comment]
`.introjs-showElement` and `.introjs-fixParent` appear as normal.

**Comment by CheemaSingh** [comment]
I am also having same problem, any did you find any solution yet?

**Comment by otumer** [comment]
I am using chrome 54.0.2840.87 m (64-bit) version and I have same problem with @rattrayalex.
![intro problem](https://cloud.githubusercontent.com/assets/23259631/20005058/8eb4ef04-a298-11e6-9825-7b734d790182.JPG)
Is there any solution @afshinm

**Comment by tanoy2k** [comment]
Hi, I am also having same problem, did you find any solution Or some work around to fix it, thank you

**Comment by aimamovic3** [comment]
I commented line 1146  parentElm.className += ' introjs-fixParent';

With this line I have this:

![image](https://cloud.githubusercontent.com/assets/6852487/21498252/33c06a9e-cc2b-11e6-845b-f53e2d5c5b8b.png)

and after I move to the field in tab:

![image](https://cloud.githubusercontent.com/assets/6852487/21498272/581c84fe-cc2b-11e6-8f9e-84244f701f0b.png)

Without this line:

![image](https://cloud.githubusercontent.com/assets/6852487/21498287/6bb593c0-cc2b-11e6-8da9-3fe4bafa1647.png)

but it seems that isn't same problem

**Comment by afshinm** [comment]
could you please share your example? or a jsfiddle.

**Comment by afshinm** [comment]
This could be because the element is not on the page. use refresh() method to change the position of target element.

**Comment by guptarohit** [comment]
@afshinm Please provide an example of how to use the above method. Can you please elaborate how should I use refresh() method with an example.
Thanks in advance :+1:
