### ISSUE TITLE
Provide a different CSS class for done button

### ISSUE THREAD

**Issue by maelfrize** [usablica/intro.js#531]
Currently, the done button has the same CSS class like the skip button (.introjs-skipbutton).

In order to add a different styling to the done button, it would be great to have a different class (something like .introjs-donebutton)

This would be consistent with the fact that one can set a different label for the done button.

What do you think about?

**Comment by rhyous** [comment]
I agree. 

Also, done and skip show up as grayed out even though they aren't disabled. They can be clicked. This seems odd. 

I get why we might want Skip to look less clickable, as that urges the user through to intro, but Done should definitely not appear be grayed out.

So if this gets done, let's make sure Done text is black, not gray.

**Comment by msqar** [comment]
I agree 100%.
What you guys can do in the meantime, is use the onbeforechange event callback and based on the _currentStep, if it's the last one, just change the skipintro css, maybe add a css to the button, to make it look different.

**Comment by khari1090** [comment]
Totally agree!
