### ISSUE TITLE
Cannot click next button on mobile when disableInteraction: true,

### ISSUE THREAD

**Issue by kissgyorgy** [usablica/intro.js#535]
When I set `disableinteraction` to `true` and the tooltip shows up on the center of the screen (on small screen), it's not possible to click on the Next button, because the `.introjs-tooltipReferenceLayer`'s `z-index` is `10000000` (ten million), but the `.introjs-disableInteraction`'s z-index is `99999999!important` (ninetynine-million), which is bigger.

**Comment by afshinm** [comment]
Can you please share a jsFiddle?
