### ISSUE TITLE
Introjs highlighted area css issue

### ISSUE THREAD

**Issue by ovaiskhan11** [usablica/intro.js#536]
I am using your introjs plugin but I have faced some issues. The highlighted area becomes completely white. I am guessing that this is some CSS conflict because I am also using bootstrap.

I have asked same question on stackoverflow: http://stackoverflow.com/questions/35536584/introjs-highlighted-area-css-issue and also emailed to afshine but didn't get my answer.

What can I do to determine the cause of this problem?
![introjs_issue](https://cloud.githubusercontent.com/assets/14327377/13210142/946f45ba-d945-11e5-9831-f222f89580c2.png)

**Comment by afshinm** [comment]
Just answered the Stackoverflow's thread.
