### ISSUE TITLE
Unexpected CSS token: : in Safari 9.0.3

### ISSUE THREAD

**Issue by skeet** [usablica/intro.js#537]
Hi,

I'm seeing exactly the same issue as https://github.com/select2/select2/issues/3304

In 3 different places, I'm getting a CSS warning on Safari : 

![screen shot 2016-02-22 at 11 59 09](https://cloud.githubusercontent.com/assets/1735459/13217616/beab5a42-d95b-11e5-8564-3995c3f8cdc4.png)

Here's 2 instances of offending code (cut-down for brevity):
```
.introjs-helperNumberLayer {
    filter: progid: DXImageTransform.Microsoft.gradient(startColorstr='#ff3019', endColorstr='#cf0404', GradientType=0);
    filter: progid: DXImageTransform.Microsoft.Shadow(direction=135, strength=2, color=ff0000);
}
```

Filter expects a string so should be like so:
```
.introjs-helperNumberLayer {
    filter: "progid: DXImageTransform.Microsoft.gradient(startColorstr='#ff3019', endColorstr='#cf0404', GradientType=0)";
    filter: "progid: DXImageTransform.Microsoft.Shadow(direction=135, strength=2, color=ff0000)";
}
```

The 3rd warning comes from the same code in `.introjs-overlay`.

Happy to create a PR - I think preventing 3rd party libraries throwing warnings is a good thing for everyone.

Cheers.

**Comment by afshinm** [comment]
That would be great if you send a PR @skeet.
