### ISSUE TITLE
All demo examples in http://usablica.github.io/intro.js/ points to a broken link (404)

### ISSUE THREAD

**Issue by karloespiritu** [usablica/intro.js#544]
All the demo examples in the project page points to a broken link (404):

http://usablica.github.io/example/hello-world/index.html
http://usablica.github.io/example/hello-world/withProgress.html
http://usablica.github.io/example/hint/index.html
http://usablica.github.io/example/programmatic/hint.html
http://usablica.github.io/example/hello-world/withoutBullets.html
.....

**Comment by afshinm** [comment]
Please use introjs.com. So:

http://introjs.com/example/hello-world/index.html
