### ISSUE TITLE
Receiving support? 

### ISSUE THREAD

**Issue by Francolpm** [usablica/intro.js#551]
Hi there! This isn't a issue but I didn't know where to ask!
Are you accepting donations or supports? Because I want to give some of money to intro.js, but there is no donate button o something like that.
I don't trying to spam you, but I want to invite you to beerpay.io, a simple platform to monetize open source projects, like intro.js. 
I know that the open source is free, but it's okay if someone want to contribute in other way.

Thanks for this work!

**Comment by afshinm** [comment]
Hi Sir,

I'm working on business/commercial plans and will add them in next two days then you will have premium support by email. Stay tuned, will update this thread as well.

Cheers.
