### ISSUE TITLE
Plans for Angular 2 Directive?

### ISSUE THREAD

**Issue by tehaaron** [usablica/intro.js#552]
I noticed there is a nice Angular 1.X directive but was curious if anything specifically for ng2 was in the works?

**Comment by afshinm** [comment]
Good idea @tehaaron. I don't have enough time myself to contribute to this idea. I prefer to work on the main application and improve it + addressing existing issues.

Are you keen to start it?

**Comment by tehaaron** [comment]
@afshinm I believe my team plans to use intro.js in our ng2 app but I am not sure to what extent. If we end up with some extra time to do the port I will certainly contribute.

**Comment by afshinm** [comment]
that's great! Let me know then ;)

**Comment by maitrungduc1410** [comment]
I don't think you need directive for that.

it's simple, follow my gist to see how to run introjs on angular (>=2) project: https://gist.github.com/maitrungduc1410/68ae50b9c9a6c893959075a1c15871a8
