### ISSUE TITLE
get current step/input focus

### ISSUE THREAD

**Issue by vana-dev** [usablica/intro.js#553]
I make tutorial over editable form, and I have one big issue, I have to set focus on current step input, any ideas, how can I make it? e.g recognized current step, set focus on this element, and blur for others.

**Comment by BKD-Digital** [comment]
Create your introJs object and leverage the event methods made available by introJs.

Example is as follows:

var intro = introJs();

intro.onchange(function () {
console.log(this);
// you'll notice the object's properties have _currentStep - use that :)
});

easy, huh?

**Comment by ShamanSC** [comment]
Cesar-

Thanks I really appreciate the help.


Gary L Fry
MCITP/MCTS
shamansc@outlook.com<mailto:shamansc@outlook.com>
803-312-4588

**Comment by rattrayalex** [comment]
Ideally this would be a public method, or an argument passed to the `onchange` callback.

**Comment by Jeffreyrn** [comment]
> Cesar-
> 
> Thanks I really appreciate the help.
> 
> Gary L Fry
> MCITP/MCTS
> [shamansc@outlook.commailto](mailto:shamansc@outlook.commailto):[shamansc@outlook.com](mailto:shamansc@outlook.com)
> 803-312-4588
> 
> From: Cesar Perez [mailto:[notifications@github.com](mailto:notifications@github.com)]
> Sent: Saturday, March 12, 2016 10:46 AM
> To: usablica/intro.js [intro.js@noreply.github.com](mailto:intro.js@noreply.github.com)
> Subject: Re: [intro.js] get current step/input focus (#553)
> 
> Create your introJs object and leverage the event methods made available by introJs.
> 
> Example is as follows:
> 
> var intro = introJs();
> 
> intro.onchange(function () {
> console.log(this);
> // you'll notice the object's properties have _currentStep - use that :)
> });
> 
> easy, huh?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/[/issues/553](https://github.com/usablica/intro.js/issues/553)#issuecomment-195764386.

thanks for your solution!
