### ISSUE TITLE
license subscription

### ISSUE THREAD

**Issue by nekkon** [usablica/intro.js#554]
The company I am working for is interested in obtaining a license for commercial use. We would like to know if the payment is for a life-time license or must be paid monthly. It is not clear..

**Comment by afshinm** [comment]
Hey @nekkon. This is a lifetime payment. Sorry, I will add more details.

**Comment by niftylettuce** [comment]
Here's an MIT licensed version, free for all.  https://github.com/niftylettuce/introjsmit  Install on Bower or NPM with the name `intro.js-mit`
