### ISSUE TITLE
bottom-middle-align not working

### ISSUE THREAD

**Issue by nekkon** [usablica/intro.js#555]
Hello, I can not make the intro tooltip have "bottom-middle-align" position. Left, right, bottom works but not bottom-middle-align.. Any suggestions?

**Comment by kencoxdesign** [comment]
Same issue.
Tooltips are getting set to an inline style of left: 0px so I can't even just override with css.

**Comment by metronomx** [comment]
https://github.com/usablica/intro.js/blob/55f6bb746a9f48e43d4cc6b8740e28f1c4dfedf4/intro.js#L804-L808

This is because of this non-working piece of code. 
(possiblePositions.indexOf(desiredTooltipPosition) > -1) is always false.}

Is this project dead?

**Comment by metronomx** [comment]
made a PR on this
https://github.com/usablica/intro.js/pull/771

**Comment by bozdoz** [comment]
Fixed in #768
