### ISSUE TITLE
anchorLink.href violates unsafe-inline content security policy

### ISSUE THREAD

**Issue by hakib** [usablica/intro.js#557]
The `anchorLink.href` is hard coded to `'javascript:void(0);'`. This violates the `unsafe-inline` content security policy for the `script-src` directive. The violation does not effect the functionality in any way but it triggers a CSP report and that's usually reported back to the server (which cause a lot of unnecessary noise).

I think that this should be configurable for those who wish to enforce CSP.

**Comment by harunsmrkovic** [comment]
Also, just removing a `href` attribute from anchor works just fine. I can create a PR with this fix.

**Comment by afshinm** [comment]
@harunsmrkovic can you please?

**Comment by harunsmrkovic** [comment]
#568

**Comment by hakib** [comment]
Hey @harunsmrkovic, I just tested the PR on chrome and FF and it's no longer violates the unsafe-inline CSP policy. Thanks.
