### ISSUE TITLE
Attribute data-hint is chosen unlucky

### ISSUE THREAD

**Issue by mambax** [usablica/intro.js#559]
I really love the new tooltips, the small dots, awesome!!!

Although I discovered a small conflict which disturbs our (and maybe others) applications:

The library [HINT.CSS](http://kushagragour.in/lab/hint/) uses `data-hint` as selector too. Their hints are slightly different from yours, being on hover and having no dot (which we also need).

Now as you can imagine of course they clash on the data attribute.

I'd be happy to fork and create a pull request and suggest changing the data attributes everywhere to `data-introjs-*` to avoid any other possible clash.

Any thoughts?

**Comment by mambax** [comment]
#519 would also be resolved by this in btw.

**Comment by bozdoz** [comment]
I like this idea, and agree that it should help reduce any potential conflicts.

**Comment by seanwalsh** [comment]
I think across the board the `data-attributes` need a little better namespace. We ran into an issue where we had already used `data-step` and had to rescope that so we didn't have any conflicts. So something like `data-introjs-step` would be better.
