### ISSUE TITLE
Call onexit handler in .exit method

### ISSUE THREAD

**Issue by ypanyukov** [usablica/intro.js#560]
It will be really great if when I call .exit method, onexit handler would get called too

**Comment by piotr-cz** [comment]
Yes please, I'm doing a cleanup after

**Comment by hyperknot** [comment]
Yes, this is an important issue. I had to go through the full code of introjs to find out why is my onexit handler not working when I'm calling `.exit()`.

Also, I'd recommend collecting all the:
```
         if (self._introExitCallback != undefined) {
            self._introExitCallback.call(self);
          }
```

Lines throughout the code into a cleaner function.

**Comment by afshinm** [comment]
Apologies for this mistake. Just fixed and will be available for the next release (in a week)
