### ISSUE TITLE
Urgent Problem with hints in SPA

### ISSUE THREAD

**Issue by babnik63** [usablica/intro.js#564]
When changing routes in SPA's hints stays on the window but every thing is changed.
I think having somthing like: introjs().removeHints() could solve the issue.

**Comment by babnik63** [comment]
I did some tricks and failed, I think it needs a public function.

**Comment by afshinm** [comment]
Can you please prepare an online demo for this issue? a jsfiddle maybe

**Comment by babnik63** [comment]
I'm using Meteor so jsfiddle is not possible. I need to be able to remove hits manually by code, then I can use this function in my routing changes.

**Comment by tonyspb** [comment]
@afshinm 
https://jsfiddle.net/0xbxmvu2/2/

the thing is one can't hide unused hints and show new hints.

**Comment by babnik63** [comment]
@tonyspb Yes this is exactly my problem.

**Comment by afshinm** [comment]
ah I see. will apply a new patch today/tom and release v2.0.1.

**Comment by afshinm** [comment]
guys @babnik63 @tonyspb, I've added a refresh function for hints that re-arranges all hints. 
Do you think this can help you?

**Comment by babnik63** [comment]
Hi,
I think we can call this Refresh while changing routes or any thing else.
BUT: the refresh function should not do anything if the hint is not active and called before. the refresh function is not the showhint() function

**Comment by babnik63** [comment]
I saw you changes
I have tested     introJs().refresh(); but nothing changed. the hint element is no longer on page but the circles are showing.
I think we need to remove old hints so a removeHints function is a better solution.
is there any?

**Comment by babnik63** [comment]
@afshinm what is you idea about the above comment?

**Comment by afshinm** [comment]
hey @babnik63. I added "hideHint" function to the public api last night. could you please check this and lmk if it is the one you are looking for?

**Comment by babnik63** [comment]
Dear Afshin
hideHint() needs stepid, but I need something to call and remove all active hints.
this is my suggested code:
  ` function _hideAllHints() {
        _removeHintTooltip.call(this);
        var hint = this._targetElement.querySelectorAll('.introjs-hint');

        if (hint) {
            var i;
            for (i = 0; i < hint.length; i++) {
                hint[i].className += ' introjs-hidehint';
            }

        }

       
    };`
Thanks

**Comment by afshinm** [comment]
thanks @babnik63. will add this for v2.2.0.

**Comment by afshinm** [comment]
done @babnik63
