### ISSUE TITLE
Firefox - quitting intro stalls the status bar

### ISSUE THREAD

**Issue by omerkarj** [usablica/intro.js#565]
Exiting the intro (through a 'finish' / 'skip' etc.) will trigger an href="javascript:void(0)".
In firefox, the status bar (which displays the hyperlink destination on hover, at lower left of the screen) will keep displaying the "javascript:void(0)" text until the user switches tabs.

![screen shot 2016-03-30 at 12 42 01 pm](https://cloud.githubusercontent.com/assets/5781473/14138256/e7984cc2-f674-11e5-8d2f-f505722a887a.png)

**Comment by harunsmrkovic** [comment]
This issue is probably resolved by CSP fix here #557 in #568
