### ISSUE TITLE
Add a way to highlight multiple elements at once not only one for a single step

### ISSUE THREAD

**Issue by msqar** [usablica/intro.js#567]
I would like to highlight a button that opens a dropdown and the dropdown itself but seems to be impossible right now.
I tried doing it with the jQuery multiselector way, but didn't work.

i.e.
element: '.dropdown-btn, .dropdown'

**Comment by Nittarab** [comment]
I have the same problem, no update?

**Comment by afshinm** [comment]
it's not easy to do this but I'm working on it. PRs are welcome.

**Comment by afshinm** [comment]
duplicate.

**Comment by msqar** [comment]
Nice afshinm... with that it would be awesome. I know it's not easy to add tho.

**Comment by dominhtri1995** [comment]
any update ?

**Comment by kadiiskiFFW** [comment]
Same here, would really love to see it possible. And thanks for the errort!

**Comment by xjy1592922966** [comment]
希望能有这个功能，  加油
