### ISSUE TITLE
Error in CSS of introjs

### ISSUE THREAD

**Issue by byjrubira** [usablica/intro.js#569]
Hi, when i'm triying to make a gulpfile with all the css, on the line 432 of introjs.css there are a mistake with this line  `@-webkit-keyframes "introjspulse"`. To solve it whe have to remove the double quotes.

Please, notify me when it will be resolved to possibly buy an Business License.

**Comment by PhilippSchreiber** [comment]
Same here.

**Comment by PhilippSchreiber** [comment]
fixed in PR #604
