### ISSUE TITLE
Feature idea: Highlight table columns

### ISSUE THREAD

**Issue by NiklasBr** [usablica/intro.js#57]
Imagine trying to highlight the content of a table "This column contains info about X", wouldn't that be nice to do?

I have to admit I am not sure how to solve the problem where colspans would break away from the intro.js highlight if it is even possible to do this to begin with…

**Comment by mathiasleroy** [comment]
Highlighting a group of multiple cells or 1 column  
+1 need this

**Comment by Gottwik** [comment]
Until this becomes a feature I suggest adding dummy div's. Check it out here: https://jsfiddle.net/s848n5hs/2/

**Comment by russellmann** [comment]
Anything better for this yet?  The JS Fiddle doesn't allow interaction
within the column.

Thanks,

Russell Mann
Premier Hosting

**Comment by russellmann** [comment]
Using <colgroup> seems to have the same issue.

Thanks,

Russell Mann
Premier Hosting

**Comment by gb5256** [comment]
Hi, Is there a way to highlight columns of tables as described above? 
What I try to do is that all elements that have a certain class will be highlighted at once. By that we could add a step to a column of tables, but this seems also be interesting for other use cases.

Any idea?
Thanks !
gb5256
