### ISSUE TITLE
When scrollToElement is set - it should scroll back to top for "no element" tooltips

### ISSUE THREAD

**Issue by jitbit** [usablica/intro.js#571]
Scenario:
1. Element is below the fold
2. Plugin scrolls to the element
3. Next "step" in tutotrial has NO element
4. "Step" is shown outside of the screen.

**Comment by pratiksha2211** [comment]
I have also same issue same issue can anyone have solution for that ?

**Comment by analog-nico** [comment]
+1

A workaround you can apply right now:
``` js
intro.onbeforechange(function (targetElement) {
    if (targetElement.className === 'introjsFloatingElement') {
        window.scrollTo(0, 0)
    }
})
```

**Comment by afshinm** [comment]
sure, thanks. will fix it for the next version.
