### ISSUE TITLE
Licensing still in need of clarification

### ISSUE THREAD

**Issue by philippnagel** [usablica/intro.js#574]
On [http://introjs.com/#commercial](http://introjs.com/#commercial) it says "[...] you can subscribe to one of commercial licenses [...]". 

The license.md file is not explicit either: "If you want to use Intro.js for a commercial application, theme or plugin the commercial license is the appropriate license. ".

These two formulations do not explicitly state whether a commercial entity can freely use intro.js commercially. They merely imply that it is possible to purchase a commercial license entailing some additional perks. As the MIT license is very permissive, a commercial entity can simply choose to abide the MIT license, rightfully avoiding payment.

Please clarify. 

I know software engineers usually hate wrangling with these things but for a small company these details matter.

**Comment by afshinm** [comment]
will do. thanks.

**Comment by niftylettuce** [comment]
Here's an MIT licensed version, free for all.  https://github.com/niftylettuce/introjsmit  Install on Bower or NPM with the name `intro.js-mit`
