### ISSUE TITLE
Add options to animate popup (fadeIn/fadeOut or similar)

### ISSUE THREAD

**Issue by jnachtigall** [usablica/intro.js#590]
An option for simple animations would be nice to increase the "joy to use". Some people will hate it, because it does not really add functionality. But it would make intro.js more sexy and a boring introduction maybe more joy to use. 

Something like http://www.jquerypowertour.com/ (click "Run tour 1" and "Run tour 2") to see what I mean.

**Comment by afshinm** [comment]
Good idea. I was thinking about the same but I think it would be better to use css3 animations instead of JS anims.

**Comment by jnachtigall** [comment]
@afshinm Since you closed this one, is there another ticket (duplicate) to follow so that I know when this has been implemented?

**Comment by afshinm** [comment]
ah sorry @jnachtigall. just reopened and attached to the next milestone

**Comment by afshinm** [comment]
I'm changing the milestone to v3.0.0 to add or somehow integrate animate.css which looks much better and also we will have more options to use as an animation.
