### ISSUE TITLE
Regarding Pull Requests - New features

### ISSUE THREAD

**Issue by dugajean** [usablica/intro.js#591]
Great work with this plugin!

I have been coding some custom features to this plugin. Everything I've coded in is regarding form/contenteditable elements and making input required etc.

Can I make pull requests for such custom features and have it considered? It'd be awesome if this such features were available by default, so the community can help strengthen the code and so that users can gain more by using this plugin...

Features I have implemented:

- Have a `data-fill` attribute which fills an input field or a contenteditable field with the given value
- Make a field required. If the field is empty, then you cannot continue to the next step
- Show skip button on the last step only, just set `skipLabel` to `false`
- Another `data-focus` attribute which adds focus to the current element (if it's an input or contenteditable)

Please let me know if this is useful enough to be considered.

**Comment by afshinm** [comment]
awesome! 

Can you please make different PRs so I can marge them better?

**Comment by dugajean** [comment]
I'll still improve on the code I've written and make it more foolproof. Once I'm done with that I'll try to make separate PRs. Never done that before, so I gotta proceed with caution :)

**Comment by afshinm** [comment]
thanks @dugajean
