### ISSUE TITLE
License change breaks semver.

### ISSUE THREAD

**Issue by graingert** [usablica/intro.js#614]
An MIT->AGPL change should cause a change in the major version.

Otherwise this can cause people to accidentally infringe when node automatically upgrades them.

**Comment by afshinm** [comment]
I wasn't aware of this. I can't find anything related to Semver and license changes. Can you please give me a link?

**Comment by graingert** [comment]
@afshinm it's backwards incompatible, because people can't distribute their software under the same license any-more. Please unrelease 2.2.0 and re-release as 3.0.0

People won't be liable to the GPL if they accidentally infringe on it because you forced it onto their systems.
