### ISSUE TITLE
Hiding all hints and then displaying them again

### ISSUE THREAD

**Issue by Giegling** [usablica/intro.js#616]
Hello, seems like hints don't work this way. For example I've got one button, which is "Show/Hide Hints". When hints aren't displayed, I call "introJs().addHints()" and it displays all hints. On the second click, I call "introJs().hideHints()", which removes all hints and after this I have a problem. When I click that button third time "introJs().onhitsadded()" is getting called, but no hints are shown.

**Comment by noeliasfranco** [comment]
I'm having the same problem that @Giegling mentions. Once I call addHints() and then clicked on the "Got it" button I'm not able to show the hint again. Thi idea is display the hint based on some conditions, so I need to show/hide the hints multiple times.

**Comment by 54mu3l** [comment]
Same here. I'd like to show and hide hints based on conditions.
But when I hide them with `introJs().hideHints()` and try to show them again with `introJs().addHints()` it won't work. I can only add hints once. It would be nice, if I can show/hide them multiple times.

**Comment by nblackburn** [comment]
The problem here is that there isn't a `showHints` method because `addHints` renders them on the page where as hide simply attaches a class to the visible hints.

**Comment by Giegling** [comment]
When I hide hints and then I want to display them again, I'm re-initializing introJs and then displaying the hints again, that solves my problem, but I don't think that it's a good solution.
