### ISSUE TITLE
Doesn't work properly with bootstrap 3

### ISSUE THREAD

**Issue by brunocechet** [usablica/intro.js#617]
I'm having some problems using introjs with bootstrap 3. When I configure a tour guide on a modal, the elements gets desaligned (see the first image bellow, would have a modal there).
I have a filter bar on top, and the introjs with the dropdown component doesn't works properly too.
I made a small change on css, at the .introjs-fixParent, changing his content to:

.introjs-fixParent {
  z-index: 9999999 !important;
  opacity: 1.0 !important;
}

This 'small fix' makes my modal and filter bar gets better.

Someone could help me please?
![imagem1](https://cloud.githubusercontent.com/assets/7764288/16779585/5605e126-4849-11e6-880b-280c14ac480b.png)
![imagem2](https://cloud.githubusercontent.com/assets/7764288/16779586/560ae126-4849-11e6-95c0-ea1431af7b34.png)
![imagem3](https://cloud.githubusercontent.com/assets/7764288/16779587/560bc5c8-4849-11e6-9864-b3ff7fdadf4d.png)
![imagem4](https://cloud.githubusercontent.com/assets/7764288/16779589/561f23f2-4849-11e6-8e03-ca4f012fc648.png)
![imagem5](https://cloud.githubusercontent.com/assets/7764288/16779588/561ef530-4849-11e6-8c06-7dd2446c6f89.png)
![imagem6](https://cloud.githubusercontent.com/assets/7764288/16779590/562317dc-4849-11e6-81bf-e87149f7fc79.png)

**Comment by afshinm** [comment]
hey @brunocechet, do you have any online example to see? a jsfiddle can help, too. thanks.

**Comment by mohitsud** [comment]
I have the exact same issue. Have you found a resolution?

**Comment by afshinm** [comment]
can you please provide an example @mohitsud? a jsfiddle please.

**Comment by mohitsud** [comment]
This is actually related to issue #583. Removing position: absolute from the introjs-fixedparent class fixed the issue.
