### ISSUE TITLE
Tip displayed outside of the viewport

### ISSUE THREAD

**Issue by asfixia** [usablica/intro.js#618]
When a Tip is displayed it should garantee that the Window Tip is fully visible. If not, the window tip shoulw be shown 'floating' like when no target element is defined.

**Comment by afshinm** [comment]
Sure, can you please provide an example? jsFiddle maybe.

**Comment by RicardoVaranda** [comment]
I also have this issue. If an element is to close to the left hand side for example the tip will go out of the view.

**Comment by kyleamadio** [comment]
Here is an example - the control is near the right edge - the tool tip should float left:

![selection-261026-20 45 06-001](https://cloud.githubusercontent.com/assets/1647986/19721250/34440de8-9bbd-11e6-9e4f-6c9c0a89d2b3.png)

**Comment by RicardoVaranda** [comment]
@afshinm Is this in the pipeline of fixes?

**Comment by bozdoz** [comment]
This should be resolved when #768 is merged.
