### ISSUE TITLE
Support for mobile pages?

### ISSUE THREAD

**Issue by vivekhub** [usablica/intro.js#62]
Will this be supported on mobile devices?  Seeing strange issues on android on screen resolution changes during device rotation

**Comment by valessiobrito** [comment]
Mockup proposal to intro.js interaction in mobile.

![introjs-mobile](https://cloud.githubusercontent.com/assets/310049/5827248/fb612c7e-a0df-11e4-81ea-3776efc3586c.png)

**Comment by rhulshof** [comment]
The mockup of @valessiobrito is very nice. Though might be problematic in case of a fixed footer/header one wishes to highlight.

Anyway, I would also fancy improved mobile support big time!

+1 :-)

**Comment by matiastucci** [comment]
+1 :+1:

**Comment by danieltartarottisobrosa** [comment]
:+1:

**Comment by micksatana** [comment]
I have similar problem but it happens to a page with long scrolling in mobile.

+1 for @valessiobrito mock-up

and i'd like to add idea to solve @rhulshof concern.
in case of the target element's position is fixed on top of the page, then the message is also a fixed layout and the whole page move down so it's not on top of the element.

**Comment by afshinm** [comment]
I will work on this to add for the next versions.
