### ISSUE TITLE
Use intro.js with select2 dropdown

### ISSUE THREAD

**Issue by Nittarab** [usablica/intro.js#629]
I'm creating a tutorial for my site, how do I include the entire Select2 block element in intro js?

This is mi situation: 
![schermata del 2016-08-30 18-18-40](https://cloud.githubusercontent.com/assets/6181406/18097860/0693c226-6ee0-11e6-831e-faea1495472f.png)
I read [this](http://stackoverflow.com/questions/22433675/use-intro-js-on-bootstrap-dropdown-element) question, and the result is not what I expected:
![schermata del 2016-08-30 18-19-18](https://cloud.githubusercontent.com/assets/6181406/18097887/1fde4918-6ee0-11e6-8243-f14505e75b62.png)
I use this code:
````
if (RegExp('multipage', 'gi').test(window.location.search)) {
            $("#contract_contract_textId").select2('open');

            intro.start()
        }
````
I have no idea how to fix this ...

**Comment by afshinm** [comment]
Share a demo, jsfiddle. i don't know what select2 is.

**Comment by brundles** [comment]
Hi @Nittarab - did you ever fint anything out about this?

**Comment by praveenkumar074** [comment]
still not fixed

**Comment by EhsanZ** [comment]
Hello guys

I'm having the same issue, were you able to resolve it? @praveenkumar074

**Comment by johnef** [comment]
Had the same issue any updates

**Comment by Nittarab** [comment]
@johnef This is very old. Maybe you can provide the jsfiddle as @afshinm  asked. I'm no more using this library. 

Btw [Select2](https://github.com/select2/select2) is a very popular Jquery select boxes replacement

**Comment by Itsharzy** [comment]
@Nittarab Here is a jsfiddle of the issue.

https://jsfiddle.net/4bzxogvh/1/

Reason it's happening is due to the dropdown selection being in a seperate div away from the original selection (I think its appears under a script tag in this example.) Any ideas how we could get around this?

**Comment by Nittarab** [comment]
@afshinm  the @Itsharzy  replicate the issue 

Thank you

**Comment by Itsharzy** [comment]
If it's any help, I've taken off the overlay, made the intro not end on click of the overlay and managed to make it work but it doesn't highlight anything it's more or just a tooltip now.
