### ISSUE TITLE
use intro.js with meteor.js 

### ISSUE THREAD

**Issue by saeedjalali1** [usablica/intro.js#632]
Hi, I trying to use this package into meteor.js(1.4.1.1). but is not working! intro.js is best package for this aim and  it is a pity that not have specific Document for meteor.js  
please add specific Document for [meteor.js](https://github.com/meteor/meteor)

**Comment by afshinm** [comment]
Hey, "it's not working" means a lot. Please share a code, jsfiddle, demo. Closing.
