### ISSUE TITLE
Helper number out of screen

### ISSUE THREAD

**Issue by pehuensolari** [usablica/intro.js#633]
Hi, Im using introjs and sometimes when you add an step to a div or an element that is near the top of the screen (the same happens with a side) the helper number is out of screen....

How can I fix it??
Thanks

![screen shot 2016-09-07 at 11 21 20 pm](https://cloud.githubusercontent.com/assets/8869023/18334962/fceed99a-7551-11e6-928a-f053bc93880f.png)

**Comment by afshinm** [comment]
It's a known issue. I will add another position for the helper number. thanks @pehuensolari

**Comment by MarkHerhold** [comment]
@afshinm Was this fixed in any release yet?

**Comment by pehuensolari** [comment]
No, @afshinm I think it's still happening 👎

**Comment by sebastian-raubach** [comment]
Is there any update on this?

**Comment by hajimurtaza** [comment]
@bozdoz  @afshinm  Can you plzz provide temporary fix until this feature is added? The examples above are not precise.
