### ISSUE TITLE
[Feat] Add flow control

### ISSUE THREAD

**Issue by luchillo17** [usablica/intro.js#637]
Say in my project i'm using the `intro.js` lib as a mean to give an interactive tutorial, so far so good, but there's sections where i would like to block the next button event until some action is taken on the highlighted element, that way the user does go through the tutorial in a proper way, basically i want a way to disable certain buttons (specifically the next button) when calling a function, and do the inverse, calling a function to enable the button.

An optional param would be if clicking the backdrop or the skip button could be disabled, but that's another story.

This feature would add a lot more use cases than just tours, maybe even guided tutorials.

**Comment by johndark** [comment]
Agree with @Luchillo, please add this feature.
