### ISSUE TITLE
prevTooltipButton/nextTooltipButton is sometimes null

### ISSUE THREAD

**Issue by PikachuEXE** [usablica/intro.js#638]
Encountering errors like

```
Unable to get property 'removeAttribute' of undefined or null reference
```

at https://github.com/usablica/intro.js/blob/v2.3.0/intro.js#L1012

or 

```
Unable to get property 'tabIndex' of undefined or null reference
```

at https://github.com/usablica/intro.js/blob/v2.3.0/intro.js#L856

Is it missing some null checking?

**Comment by tgirgin23** [comment]
Having the exact same issue as above. Has anyone come up with a fix?

**Comment by afshinm** [comment]
merged.
