### ISSUE TITLE
Can't set nextLabel, prevLabel, etc. for specific steps

### ISSUE THREAD

**Issue by Coedcoe** [usablica/intro.js#640]
How do can you get a specific nextLabel for step 1, then have a different nextLabel for the rest of the steps? It seems that once you setOption for nextLabel and start introJS, you can't change the setOption again

**Comment by fltkintern01** [comment]
same question but for prevLabel.
trying to make specific back buttons have different actions.

**Comment by BenHarris** [comment]
This can actually be achieved in a relatively simple way. Hope this helps someone!

```
// Init introjs
var introjs = introJs();

// Store the default next label value
introjs._options.defaultNextLabel = introjs._options.nextLabel;

introjs.onbeforechange(function(){
  // Revert next label (may have been overridden in the previous onbeforechange)
  introjs._options.nextLabel = introjs._options.defaultNextLabel;

  // Current Intro Item
  var iItm = this._introItems[this._currentStep];

  // Maybe set nextLabel
  if (iItm && iItm.hasOwnProperty('nextLabel') && iItm.nextLabel.length) {
    introjs._options.nextLabel = iItm.nextLabel;
  }  
})
.setOptions({
  steps: [{
    title: 'Hello World! 👋',
    intro: 'This button is different, using the custom nextLabel in this step.',
    nextLabel: 'I\'m different'
  },
  {
    element: document.querySelector('#step2'),
    intro: 'The nextLabel has now reverted to the default label ("Next"), but we could set it to something else here too.'
  },
  {
    title: 'Farewell!',
    element: document.querySelector('#step3'),
    intro: 'The final step shows the doneLabel.'
  }]
})
.start();
```

I also created a quick [JSFiddle here](https://jsfiddle.net/69omkp0z/1/).

**Comment by LeandroVignoni** [comment]
Hi @BenHarris , actually I am trying to change prevLabel in the same way you changed nextLabel and is not possible. If a set prevLabel in first step, it keeps the same value over the other steps, no matter if I set another value in the upcoming steps. Used same JSFiddle added the logic for prevLabel and nothing. Hope you can give me an answer.
