### ISSUE TITLE
Prevent next step

### ISSUE THREAD

**Issue by iFlash** [usablica/intro.js#645]
Is there a way to prevent the next step to show (for example if a field has not been filled out in a form)? I tried to do it with beforechange but when I use gotoStep in beforechange weird things happen.

**Comment by bozdoz** [comment]
An option to bail out if a function returns false, like #737, might be good for `onbeforechange`, too. 

@afshinm

**Comment by afshinm** [comment]
Ah I like this idea. I will work on this for 2.7.0.

**Comment by afshinm** [comment]
https://github.com/usablica/intro.js/pull/739
