### ISSUE TITLE
Responsive behavior

### ISSUE THREAD

**Issue by julmot** [usablica/intro.js#646]
When resizing the viewport I expect the tooltip inside a corner which has space. Unfortunately that isn't the case and the tooltip is overflowing:

![screen shot 2016-11-08 at 16 11 14-fullpage](https://cloud.githubusercontent.com/assets/8310677/20104456/57fd8ac8-a5ce-11e6-8a88-92b4319d163b.png)

This not just applies to the tooltip, but also to the step number. 

Also, the plugin has many problems with elements that are positioned using `translate` or `position: absolute`. I can't use the plugin with these bugs.

**Comment by designbyadrian** [comment]
Bump!

Tooltips flow outside window if target element is too far to the side.

![screen shot 2017-09-19 at 16 38 03](https://user-images.githubusercontent.com/2064558/30601139-1b1d603c-9d59-11e7-8f58-dc7878971608.png)

**Comment by bozdoz** [comment]
I can't reproduce this.  Can you post a jsfiddle/codepen example?

**Comment by Spope** [comment]
I reproduce this on the intro.js demo website http://introjs.com/example/hint/index.html

On a mobile browser add hints and open the top hint (on github button). The tooltip will be cut on top.

![tooltip](https://user-images.githubusercontent.com/1098552/31127408-2336c424-a84f-11e7-93f9-b0c5634c2d1e.png)

**Comment by bozdoz** [comment]
Some screenshots from #768 : 

auto bottom-left-aligned:
![bottom-left-aligned](https://user-images.githubusercontent.com/1410985/31137168-cbc942ec-a840-11e7-95d7-c757ce54fec5.png)

auto bottom-middle-aligned:
![bottom-middle-aligned](https://user-images.githubusercontent.com/1410985/31137190-dd2794ee-a840-11e7-8459-ea6aa2f73a0d.png)

auto bottom-right-aligned:
![bottom-right-aligned](https://user-images.githubusercontent.com/1410985/31137209-f567544a-a840-11e7-85ff-2f8971bc6202.png)

**Comment by pg1671** [comment]
+1 .. I just came here to report the same issue. When I resize the browser to be smaller my tooltips will eventually be positioned off screen if the target is too close to the top of the screen and the tooltip will overflow the highlight (even though there is plenty of room below the target element for the tooltip to be displayed).

**Comment by pg1671** [comment]
I tested the new code in the fix-autoposition branch and it worked a lot better for my case where a tooltip with a target high on the page was placed off screen .. but there was a change to one of the other steps that was working fine in 2.7.0.

![tour-with autoposition fix](https://user-images.githubusercontent.com/616457/31226197-984376ca-aa18-11e7-82fe-bb8d6c69924d.png)

The above screenshot shows the tooltip placed above the target but off screen (when there is plenty of room to the right).

The below screenshot is where it is placed in version 2.7.0.
<img width="600" alt="tour-introjs_2 7 0" src="https://user-images.githubusercontent.com/616457/31226271-d07030ce-aa18-11e7-8174-f91c8950448e.png">

everything else worked better with your autoposition improvements. One factor is that this part of the tour was scrolled to from higher on the page .. could the scrolling be the cause of the bad positioning of the tooltip for this step?
