### ISSUE TITLE
[Request] Add support for react native

### ISSUE THREAD

**Issue by raviteja83** [usablica/intro.js#658]

**Comment by anhtuank7c** [comment]
I would love to see it happen.
Let's voting up.

**Comment by ZKM** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9990837-153854334_7-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by saudpunjwani101** [comment]
yeah!

**Comment by bozdoz** [comment]
Just a question to the group here:  Wouldn't this be a large undertaking?  

Note: I am freshly going through a React Native course.  My initial thoughts are that it would be intensive to rewrite this library to use native elements and methods.  I do not yet know how much JavaScript and CSS can be translated over (simply) with React Native.
