### ISSUE TITLE
Add API call to remove all hints

### ISSUE THREAD

**Issue by 54mu3l** [usablica/intro.js#659]
Hello
I've a page with dynamic content. That means, I need a way to remove added hints without reloading the whole page.
I'd like to remove all hints and add some new, when the content changes. Currently I can only call `hideHints()` to hide them. But when I call `showHints()`, all are shown (even those that should no longer exist...).

**Comment by Manuel83** [comment]
+1

**Comment by mdschweda** [comment]
In the meantime

```js
let container = document.querySelector(".introjs-hints");
if (container)
    while (container.firstChild)
        container.removeChild(container.firstChild);
```
