### ISSUE TITLE
Bug: Doesn't work with SVG

### ISSUE THREAD

**Issue by sroerick** [usablica/intro.js#66]
I'm developing a site where the navigation is entirely drawn in SVG. 

I have tried including the intro.js elements in my a tags, in my <circle> tags, and surrounding them with divs, to no avail. Each time, the intro text loads in the upper left corner. 

I have pushed an example of this to http://gendale.net

More Info Edit: I made gendale  call intro.js onload. The script is still aware the location of the SVG element -- it scrolls down to the bottom of the page. The tooltip, however, still loads in the top left of the page. Perhaps the ability to set the origin of the tooltip would be a simple fix for this?

**Comment by sardanalokesh** [comment]
Do we have any news on this one? Is it fixed?

**Comment by Narretz** [comment]
Why is this closed? This is not fixed in 2.3.0

**Comment by Ilanak** [comment]
Doesn't work for me too. 
Any news with this issue?

**Comment by afshinm** [comment]
Hey guys, sorry for closing this I thought we have solved this. I'm working on a workaround to fix the issue but please note that it's not possible to add `z-index` to elements inside an SVG but I have tested something with D3 and looks like it's working fine. Screenshot attached.
<img width="516" alt="screen shot 2016-12-15 at 22 10 29" src="https://cloud.githubusercontent.com/assets/314326/21243975/517fae58-c313-11e6-8288-9e1b5a4e844e.png">

I'm hoping to finish it in next few days.

**Comment by afshinm** [comment]
Ok guys, I have pushed a testing for SVG support here: https://github.com/usablica/intro.js/commit/66b2f1a18ba143eca593fc4f05e1b5861f0d5cce

Could you please confirm if it's working fine? Thanks.

**Comment by KennethVerbeure** [comment]
I have testing the svg fix and everything seems to be working fine now in my project. When can we expect a release for this ?

**Comment by ropeladder** [comment]
Thanks for adding SVG support! Should SVG elements also work programmatically? (I've tried but it doesn't seem to work)

**Comment by lakinmohapatra** [comment]
Does intro js work for svg elements ?
