### ISSUE TITLE
Problem by using nextStep() in a onbeforechange

### ISSUE THREAD

**Issue by ptrussart** [usablica/intro.js#660]
Hello,

Based on certain conditions, I need to skip some steps (for instance if the element targeted is not in the DOM) and I have found a problem using the `nextStep()` in a `onbeforechange` method.

When I use this, the highlighted area is the one from the next step but the text and the tooltip used is the one from the step I wanted to skip.

![image](https://cloud.githubusercontent.com/assets/11556849/21219096/9cde3316-c2b3-11e6-88f4-3bd78a9577f3.png)

I have made an example here : http://jsfiddle.net/qy4mkeuz/11/ . You can see that before entering step 2, it is supposed to skip the step and go on step 3.

Is this supposed to work the way I did it ? 

Regards,
Pierre.

**Comment by ptrussart** [comment]
Hello,

Does someone as an idea about this issue. This is very annoying and I cannot find a workaround.

Regards.

**Comment by afshinm** [comment]
Changing the event to `onafterchange` fixed the issue for me: http://jsfiddle.net/afshinmeh/qy4mkeuz/13/

**Comment by shikelong** [comment]
Changing the event to onafterchange will cause another problem ----- can't back to step1 when in step3.

@afshinm

**Comment by brenopolanski** [comment]
Thanks @afshinm. 

But if the step is now `Test 3` and I would like back `Test 1` clicking in back button?! It will be called `this.nextStep();` and not `this.previousStep()`.

How could this be solved? I tested some things and it did not work...

**Comment by brenopolanski** [comment]
Okay... I found a solution. Thanks :)

**Comment by CesarAntolinez** [comment]
The solution that was implemented was this:

var intro = introJs();
intro.start().oncomplete(function () {
introJs().exit();
}).onskip(function () {
introJs().exit();
}).onafterchange(function(targetElement) {
var input = $(targetElement).data('status');
if (input == 0 && intro._direction === 'forward')
{
intro.nextStep();
//introJS().nextStep();
}
if (input == 0 && intro._direction === 'backward')
{
intro.previousStep();
//introJS().nextStep();
}
});
