### ISSUE TITLE
introjs in Ionic 2, screen is black in iOs

### ISSUE THREAD

**Issue by namgiang** [usablica/intro.js#661]
Hi, I am using introjs in a mobile app developed with Ionic 2 (Angular 2). Everything works great in Android, but in iOs, the screen is black, only the highlighted element, the helperlayer, and the tooltip reference is shown, as in the picture below:
![capture](https://cloud.githubusercontent.com/assets/3806284/21239582/bc84b16e-c307-11e6-8fea-68b7f89a669c.PNG)

As I investigated further, the main screen is revealed when I change the z-index of the introjs-fixParent class to a number. But at the same time the highlighted element is covered (the z-index in introjs-showElement doesn't work anymore). 

I tried different things, but still I haven't been able to solve the problem. Please help me!!

**Comment by CottleC** [comment]
Hi there,

Did you ever figure this one out? I am running into a similar issue.

**Comment by namgiang** [comment]
Hi, I couldn't solve it, and introjs won't support this. So I made this from scratch, getting inspirations from how they do it in introjs. And it turned out really easy to do, the result is more lightweight and easier to customize than introjs. Good luck!

**Comment by CottleC** [comment]
Very cool, good job! Thanks for the reply :)

**Comment by masimplo** [comment]
@namgiang care to share a blueprint of how you solved it so that others might tackle this as well?

**Comment by zephylac** [comment]
I manage to get around this problem. If you want it to work on IOS all you need to do is to replace/ overwrite :
`.introjs-fixParent{z-index:auto!important`
![before](https://user-images.githubusercontent.com/17520006/43131025-4d8d3084-8f38-11e8-9671-3397b5a10633.png)

To
`.introjs-fixParent{z-index:999999!important`
![after](https://user-images.githubusercontent.com/17520006/43131033-53d4bfa2-8f38-11e8-9306-b504872300fa.png)

After that is seems to work on IOS and it looks like it doesn't affect Android
