### ISSUE TITLE
If the data-step is off page in an absolutely positioned element, it fails to scroll.

### ISSUE THREAD

**Issue by AndrewDK** [usablica/intro.js#662]
The background dims, and there is no tooltip to be seen.

**Comment by bozdoz** [comment]
Could you provide an example? Perhaps on jsfiddle or codepen, or some simple inline code?

**Comment by Esger** [comment]
I have a similar problem. 
An element with a tooltip that is (way) outside of the viewport, within a scrollable element won't scroll into the viewport when 'next' is clicked, so you can't continue without pressing escape.
I solved this by modifying the function at line 2280 as follows:

`function _scrollParentToElement(parent, element) {
        if (element.scrollIntoView) {
            element.scrollIntoView();
        } else {
            parent.scrollTop = element.offsetTop - parent.offsetTop;
        }
    }`
