### ISSUE TITLE
Problem while accessing multiple html page in single html file

### ISSUE THREAD

**Issue by PriyankaBondarde** [usablica/intro.js#663]
Suppose index.html is my main html page . In index.html  I have included multiple html pages using ng-include. While using Intro js , its not finding divs ? Any solutions?

**Comment by Simon-Briggs** [comment]
Maybe put addHints in a timeout of some length to give time for angular to finish rendering the DOM?

**Comment by afshinm** [comment]
could be related to DOM loading.
