### ISSUE TITLE
Incorrect width/height calculation on absolute positioned svg element

### ISSUE THREAD

**Issue by KennethVerbeure** [usablica/intro.js#674]
I'm having a problem with positioning the helper overlay correctly with the absolutely positioned svg (svg is used as a button).

Even while every piece of my svg (seperate buttons) has a clear width and height the introjs lib is unable to calculate the correct position. Width and height are showing as NaNpx when using devtools to investigate

Any idea on how to fix this problem?

**Comment by afshinm** [comment]
Could you please share your example? or a jsfiddle.

**Comment by mathphreak** [comment]
After spending an hour or two tracking down a similar bug, this looks like it might be the same as #66, which has been fixed but not released yet. @afshinm, any idea when we can expect v2.5.0 with the SVG fix?

**Comment by afshinm** [comment]
I will release it in a week.
