### ISSUE TITLE
Basic usage example does not work with Content-Security-Policy

### ISSUE THREAD

**Issue by Knagis** [usablica/intro.js#680]
The basic usage example does not work with the CSP header:

    Content-Security-Policy: default-src 'self'

The button does not work but that can be easily worked around by calling `introJs().start()` from the console, however the browser prevents multiple inline styles from running thus the positioning of the popup and overlay is wrong.

![image](https://cloud.githubusercontent.com/assets/8700285/22644046/ba1f5d4e-ec69-11e6-9a3a-52fbb7647c4d.png)

**Comment by Nessworthy** [comment]
CSPs and element style attribute usage is a tricky business. If you want to go hard on blocking inline styling, I wonder if you could provide a style nonce in the header, an option to set it in the plugin, and instead of the plugin using `style` attributes, to write to a `style` element instead.

**Comment by bozdoz** [comment]
I see this as a wontfix
