### ISSUE TITLE
Bug: Calculating auto position removes top/bottom placement options incorrectly

### ISSUE THREAD

**Issue by smajl** [usablica/intro.js#681]
Easy to reproduce, just open the auto position demo page and shrink your window enough.

![image](http://i.imgur.com/nxV2zTu.png)

Caused by this line in `_determineAutoPosition` function.
```javascript
661:  if (targetOffset.left + tooltipWidth > windowSize.width || ((targetOffset.left + (targetOffset.width / 2)) - tooltipWidth) < 0) {
```
What is the purpose of the second part of the condition? I don't see any reason to have it there. Even if the tooltip had been positioned in something like `bottom-center` you would have to divide `tooltipWidth/2`.

I think this should be removed, it basically breaks the `auto` positioning on mobile devices.

**Comment by ZizzyZizzy** [comment]
Agreed, however it doesn't completely fix Mobile display issues. Removing the second condition fixes the issue where the tour box isn't actually on the bottom, but now the red step number is off the screen on the left for me. It needs to pad over a little bit to be visible.

I tried bottom-center and bottom-right, neither does anything.

**Comment by afshinm** [comment]
thanks guys @smajl @ZizzyZizzy 

I will have a look at this for the next version.

**Comment by Klass-A** [comment]
Looks like this hasn't be fixed.
Below 534px the left & top are set to 0 and the tooltip covers the element.

![Uploading image.png…]()
