### ISSUE TITLE
Whenever I change step, location href changes

### ISSUE THREAD

**Issue by tiagodreis** [usablica/intro.js#682]
Hi, whenever I change a step (next or prev), location href gets added "javascript:void(0);". Is there a way I can prevent this? Thanks in advance.

**Comment by tiagodreis** [comment]
Bear in mind that I'm using v. 2.0.0 (I tried using the new one and it simply wipes my current hash).

**Comment by bozdoz** [comment]
Perhaps the buttons should be `button` types and not anchor type elements.  I might keep this in mind if/when we alter that part of the code.
