### ISSUE TITLE
I used data-step number, if some data setp number is not exist means the bullets not working

### ISSUE THREAD

**Issue by mahesfsp** [usablica/intro.js#683]
The bullets only working the data step number is only correct order. 
if some step number is missed , it will not work.what can i do ?

**Comment by Nessworthy** [comment]
You can potentially polyfill it by grabbing all elements with [data-step-number], ordering them by step, then looping through and re-assigning the steps with an incremented number.

**Comment by bozdoz** [comment]
I think we should revamp the library to accept either a data-step number or auto-increment in the for loop.  Thoughts, @afshinm ?
