### ISSUE TITLE
Do not show hints for hidden elements

### ISSUE THREAD

**Issue by SGE00** [usablica/intro.js#684]
Anyone any idea where to change the code so hints are no displayed for hidden elements (or an element within a hidden element ?

**Comment by SDKiller** [comment]
:+1: 

And **for elements, that do not exist on page**.

My use case is that some users may not see some elements on page that other users see - that may depend on ACL or on different data sets they retrieve in grid view.

Preparing different sets of hints in this case is almost impossible - as there may be different combinations of user's ACL and data on page - better to have option not to show hint if DOM element not exists.

**Comment by anitr** [comment]
I was using version v2.7.0, with option: **jQuerySelector.** So, I was able to add something like:

intro.setOptions({
                jQuerySelector: true,
                steps: [
                    {
                        element: '.presentation-element:visible',
...

So, I could add jQuery selector **:visible** that worked.

But now, I upgraded to version 2.9.3 and there is no more jQuerySelector option!!
