### ISSUE TITLE
Option/method to hide "skip button"

### ISSUE THREAD

**Issue by SDKiller** [usablica/intro.js#688]
I ran into the issue that there is no option/method to hide "skip button".

My usecase was that on certain pages "skip button" should not be shown - because next page should be shown only to users with specific ACL.

I could only add `a.introjs-skipbutton {display: none !important;}` as inline css on that pages, but having an option would be nice.

**Comment by ayyazzafar** [comment]
Is there any plan to add feature so we can disable or hide skip button?
