### ISSUE TITLE
how to add intro text when using "data-step" with out focusing any element

### ISSUE THREAD

**Issue by mahesfsp** [usablica/intro.js#689]
i am using data-step and data-intro attribute , but i dont know how to add introduction text without focusing any element . is anyone know the solution?

**Comment by millerscout** [comment]
it's not possible when using intro.js attribute approach, because when you start intro.js, it'll loop through elements that have data-step, then creates a new step binded to that element.

you should use the programmatic way, like so:

```javascript
 intro.setOptions({
            steps: [
              { 
                intro: "this is a step!"
              },
              {
                element: '#step1',
                 intro: "This is a tooltip."
              },
            ]
          });
```

**Comment by matthew798** [comment]
This would actually be great for those using view localization in asp.net core. We can have the page translated before being sent to the client and if we have to add the steps "the programmatic way" in stead of directly on the elements, we need to figure out some way of translating JS files as well.

I would propose that the attributes could be on the <body> tag, and it could assume the user wants a "popup" in the center of the screen with no elements focused.
