### ISSUE TITLE
Lauching by an element ID or by class group not working

### ISSUE THREAD

**Issue by maurodias** [usablica/intro.js#69]
I've made a simple test in intro.js example ... changing in the Chrome DevTools the button action

```
<a class="btn btn-large btn-success" href="javascript:void(0);" onclick="javascript:introJs('.test').start();">Show me how</a>
```

and a step information , adding a class : 

```
<div class="span6 test" data-step="2" data-intro="Ok, wasn't that fun?">
      <h4>Easy to Use</h4>
      ...
```

Any ideas what can it be?

**Comment by dspoonia7** [comment]
Is there any way to achieve what @jrencz has described in above [comment](https://github.com/usablica/intro.js/issues/69#issuecomment-15493603)? I need to define multiple tours within the same container with the different number of steps, for first-time users and revisiting users. @afshinm.
