### ISSUE TITLE
Change the background / text color of buttons and tooltip box

### ISSUE THREAD

**Issue by ahmednawazbutt** [usablica/intro.js#690]
I want to change the color of buttons and tooltip box according to the look and feel of my site. Though I can apply hacks of my own by applying the jquery on element-classes found in source code of page but its not a regular/standard way.
So my question is, how can I change the style properties for both the tooltip and buttons as well as the tip # label in circle found under "introjs-helperNumberLayer".

**Comment by millerscout** [comment]
don't use jquery to do that, it's a slower and not reliable.

why don't you create your own intro.css using a existing theme like [this](https://github.com/usablica/intro.js/blob/master/themes/introjs-dark.css)?

it's just plain css, or i didn't understood what you're askin?

**Comment by ahmednawazbutt** [comment]
Thank you for your reply.
But my requirements are to do so using jquery and not pure css. I have already done that by adding the below lines of code:

`$(".introjs-tooltip").css({"background-color" : "black", "color" : "white", "opacity": 0.9});
    $(".introjs-arrow.top").css("border-bottom-color" , "black");`

I added the above lines of code after starting the tour i.e 
`introJs().start();`
