### ISSUE TITLE
Disable the buttons, links in background when the guide is open?

### ISSUE THREAD

**Issue by ahmednawazbutt** [usablica/intro.js#691]
I have a button upload File in my index page.
When I start the tour, I want to make sure the user click does nothing when in guider. In order to use the button functionality, he must get out of wizard first. How can I do that?

**Comment by millerscout** [comment]
On my project i disable the button as the intro starts, then after completes i enable again.

if you're using angular there's a directive that does that.

https://github.com/mendhak/angular-intro.js

**Comment by ahmednawazbutt** [comment]
No I am not using AngularJs.
I need this to be done only in jquery.

I have tried a bunch of techniques but none worked for me. I have tried below options:

`//	Close the wizard on any button click or disabled clicking any button there in the page
	$("body").on("click", "main_view_container_div a", function(e){
		if( $(".introjs-showElement")[0] )	//	case: the tour is in process
		{
			//e.stopPropagation();	//	not working
			e.stopImmediatePropagation()	//	not working
			
			//var esc = $.event("keydown", {keyCode:27});
			//$("body").trigger(esc);	//	didnt work at all
			
			//	Trigger the below event
			//	a.introjs-button.introjs-skipbutton
			introJs().exit();	//	Exit the Tour and Work on new set	//	doesn't work very well
			//	need to apply "press Esc event" programmatically in jquery
			//	Triggering event equavalent to pressing Esc button
			//	disable all events associated with it 
			introJs().exitIntro()
		}
	});`

**Comment by millerscout** [comment]
as it's pure jquery

i would write something like:
```javascript

///run before introjs starts
	function disableTag(){
		$('a').each(function(){
		
		//gets the current dom.
		var e = $(this)
		
		//gets the current bind to click 
			var disableclick = e.attr('onclick')
			
			if(typeof e.attr('disable-onclick') === 'undefined'){
				//adds the current onclick value to an attribute;
				e.attr('disable-onclick', disableclick);
			}
			
			// replace on click with return false;
			e.attr('onclick', 'javascript:return false')
		})
	}
	
	///run after introjs completes / exits
	function enableTag(){
	
		$('a').each(function(){
			var e = $(this);
			
			if(typeof e.attr('disable-onclick') === 'undefined'){
			//if doesn't exist the attribute it just removes the attr so href should work.)
				e.removeAttr('onclick');
				
			}else{
				///put the disabled click backs to normal.
				e.attr('onclick', e.attr('disable-onclick'));	
				e.removeAttr('disable-onclick');
			}
		})
	}
```

**Comment by ahmednawazbutt** [comment]
Thank you for your reply. I did something different to achieve the same effect.
here is what I did in order to meet my requirement. 
```bash
//	Close the wizard on any button click or disabled clicking any button there in the page
	$("body").on("click", ".parent_container_window_div a", function(e){
		if( $(".introjs-showElement")[0] )	//	case: the tour is in process
		{
			$('.introjs-skipbutton').click();	//	Terminate Introduction
		}
	});
```
I just did exit the tour if user clicked on any of the links of parent window.
