### ISSUE TITLE
does intro.js work with webpack?

### ISSUE THREAD

**Issue by litan1106** [usablica/intro.js#695]
does intro.js work with webpack?

**Comment by litan1106** [comment]
I got it to work by exposed a window introjs variable.

**Comment by infinityhacks** [comment]
@litan1106 Can you supply more details about this issue ? I met the same issue

**Comment by marceloavf** [comment]
Me neither, i'm getting the following error:

`"TypeError: __WEBPACK_IMPORTED_MODULE_2_intro_js___default.a.start is not a function"`

**Comment by rauwebieten** [comment]
I imported the JS like this:

    import introJs from "intro.js";

and then do whatever you like.

CSS is imported in my entry scss file:

    @import '~intro.js/introjs.css';
