### ISSUE TITLE
hint not placed within querySelector container

### ISSUE THREAD

**Issue by thewaywest** [usablica/intro.js#698]
I have a scrolling div, and the hint target is an ID within that div whose position is by default outside of the viewport. the tag, meanwhile, exists and is accessible via JQuery.

I noticed that the hint is placed at an apparently random X/Y position within the visible page; if it is an intro (not a hint) it is not present or visible, I used the browser inspector to manually adjust the Y value of the hint, and watched it walk down the screen -- and then off the page -- it was attached to the window, and not to the div container which is scrollable. 

In both cases, it is impossible to scroll to the intro or hint. Could you add a JQuery lookup to the target parent, so the positioning is more accurate and dynamic? Or maybe this already exists, but I didn't find it in the documentation.

Thank you!

Mark

**Comment by thewaywest** [comment]
Noticed this is related to Issue #662

**Comment by bozdoz** [comment]
Thanks! I'll try to address this from the referenced issue.
