### ISSUE TITLE
Scroll issue in fixed div (modal) using intro.js hints

### ISSUE THREAD

**Issue by LouysPatriceBessette** [usablica/intro.js#699]
There is an issue scrolling a hint when the scrolling element is not the body.

Like a modal...

I tryed the refresh() function found in intro.js line #1881
No success.

Complete issue description on StackOverflow : http://stackoverflow.com/questions/43245732/scroll-issue-in-fixed-div-modal-using-intro-js-hints

CodePen : http://codepen.io/Bes7weB/pen/oZRjWq?editors=1111

**Comment by bozdoz** [comment]
I think **this needs some high-level discussion** about the best way to approach this.

First, I will assume this is common enough that it shouldn't be a `wontfix` (I often prefer scrolling elements over a scrolling body).

Perhaps we could have an option for `scrollableParent` and allow the user to optionally select this.  Then we could create a container within that parent.  This would mean that we could very easily have more than one tooltip/hint container. Then, the tooltip position becomes relative to the `scrollableParent`.  
**Complications:**
- *Will this work with the dark backdrop for normal tooltips, or should it only apply to hints?*
- *What does intro.exit cleanup look like with multiple containers?*

**Comment by bozdoz** [comment]
Thoughts, @afshinm?

**Comment by l86110** [comment]
@bozdoz 
I try to _targetElement.appendChild(hintsWrapper)
and hintsWrapper's left and top minus _targetElement's left and top 
it work
