### ISSUE TITLE
Option to change position of step number

### ISSUE THREAD

**Issue by xSirrioNx** [usablica/intro.js#702]
Add option like "stepNumberPosition": top-left | top-right | bottom-left | bottom-right for every step.

**Comment by vivek12345** [comment]
@xSirrioNx There is already a position attribute to do the same.

**Comment by xSirrioNx** [comment]
@vivek12345 I mean not tooltip position, but Step Number position (in red circle on top-left corner of highlighted element)
For example i have element on top-left corner of the page:
![60c7907f30d1b4649ffc485e1f117f5b](https://cloud.githubusercontent.com/assets/10046467/26821239/72f40c50-4aae-11e7-9b1a-8d2efab4a73f.png)
So i cant't see the step number
Yes, i can change position through CSS, by changing top/left to bottom/right:
![6413c9088561ebaa61aad2aede6d5ef9](https://cloud.githubusercontent.com/assets/10046467/26821397/f59aca4a-4aae-11e7-94af-acb4e037a0e6.png)
But it's not convenient if you have dozens of elements on the page and some of them aligned to the left side of page.

**Comment by assaflei** [comment]
This would help me as well

**Comment by ghenry** [comment]
Same for us. On left hand menus the step number is not visible and I don't see an option for this.

**Comment by neilandrews** [comment]
We'd love this feature too!

**Comment by nitin-jotwani** [comment]
seems like not yet fixed. I've added a temporary fix,
```
intro.onbeforechange(function (targetElement) {
  if (targetElement.id === 'element-id') {
    JQuery('.introjs-helperNumberLayer').addClass('introjs-stepno-top-visible')
  } else {
    JQuery('.introjs-helperNumberLayer').removeClass('introjs-stepno-top-visible')
  }
})
```

**Comment by hajimurtaza** [comment]
@bozdoz @afshinm Hi sir , can u please look at this. There also seems to be issues where when top nav elements are selected the number is shown beyond the screen. This functionality will help us bypass that

**Comment by doodhJalebi** [comment]
I'm facing the same issue. It would be nice to have official support for this.

**Comment by ponnuru** [comment]
https://github.com/usablica/intro.js/pull/335
