### ISSUE TITLE
Changing button label text 'onChange' for each steps with 'setOptions'.

### ISSUE THREAD

**Issue by arifhussain353** [usablica/intro.js#703]
I want to change button text for each steps.I did with below method but text is not changing .Should  i call `refresh()` method after  `setOptions`  ? Or i am doing with wrong way ?.
```javascript

 var intro = introJs();
      intro.setOptions({
           steps: [
                {
                     intro:$('#intro_start').get(0).outerHTML,

                 },
                 {
                   element:document.getElementById('intro_left_menu'),
                     intro: $('#intro_left_menu_html').get(0).outerHTML,
                     position: 'right'
                 },
                  {
                         element:document.getElementById('intro_top_right_menu'),
                            intro: $('#intro_top_right_menu_html').get(0).outerHTML,
                           position: 'left'
                   },
                  {
                       element:document.getElementById('intro_top_setting_menu'),
                      intro: $('#intro_top_setting_menu_html').get(0).outerHTML,
                        position: 'left',
                  },
                   {
                        intro:$('#intro_start_center_html').get(0).outerHTML
                   }
                ],
       });
      intro.start();

       intro.onbeforechange(function(targetElement) {
                 switch (intro._currentStep){
                     case 1:
                            intro.setOptions({ 'nextLabel': 'Step1 Next' , 'prevLabel': 'Step1 Back'});
                            break;
                      case 2:
                            intro.setOptions({ 'nextLabel': 'Step2 Next' , 'prevLabel': 'Step2 Back'});
                             break;
                    }
        }

```
Here is official [Demo Link](http://introjs.com/example/hello-world/withoutBullets.html).Here if we can `setOption('showBullets', false))` Or `setOption('showBullets', true))` for different steps ?

**Comment by bozdoz** [comment]
Does not look like this can happen with the current version.  Could be something to recommend for future versions.

**Comment by tilomitra** [comment]
Yea, that `setOptions` API doesn't work well. I ended up using `document.querySelector('.introjs-nextbutton').innerHTML = 'Step 2 Next'.

**Comment by jesobreira** [comment]
Had a similar issue. I am unable to set the labels following the docs in any way. As I am in a hurry, I will end up changing the texts directly on the intro.js file (I know it's a terrible practice, but hey, I have to eat). Would love to see this issue fixed.

**Comment by Klass-A** [comment]
This one does seem to change text on all buttons, if you target by class nesting, it returns a 'Cannot set property 'innerText' of null' error.

`document.querySelector('.introjs-nextbutton').innerHTML = 'Step 2 Next';`

**Comment by namlq93** [comment]
> Yea, that `setOptions` API doesn't work well. I ended up using:
> 
> ```
> document.querySelector('.introjs-nextbutton').innerHTML = 'Step 2 Next';
> ```

But I can't change the number of step number: 
`document.querySelector('.introjs-helperNumberLayer').innerHTML = ' ';`
It's not working. When I use `console.log(document.querySelector('.introjs-helperNumberLayer').innerHTML)`, it will get the value in the previous step.

**Comment by namlq93** [comment]
> This one does seem to change text on all buttons, if you target by class nesting, it returns a 'Cannot set property 'innerText' of null' error.
> 
> `document.querySelector('.introjs-nextbutton').innerHTML = 'Step 2 Next';`

But I can't change the number of step number: 
`document.querySelector('.introjs-helperNumberLayer').innerHTML = ' ';`
It's not working. When I use `console.log(document.querySelector('.introjs-helperNumberLayer').innerHTML)`, it will get the value in the previous step.
