### ISSUE TITLE
Width of introjs-helperLayer and introjs-tooltipReferenceLayer

### ISSUE THREAD

**Issue by ivanbacher** [usablica/intro.js#706]
At the moment the width of these layers is about 5 px greater than the original bounding box of the element. 

Is it possible to set the width to the exact size of the data-step/data-intro element?

![screen_shot_2017-05-10_at_17_07_57](https://cloud.githubusercontent.com/assets/5493114/25909039/d4c77e28-35a3-11e7-85bb-b2c2d848a239.png)

**Comment by ivanbacher** [comment]
https://github.com/usablica/intro.js/blob/master/intro.js#L742

Changing the following code seems to fix the issue. 

```
//set new position to helper layer
helperLayer.setAttribute('style', 'width: ' + (elementPosition.width  + widthHeightPadding)  + 'px; ' +
                                        'height:' + (elementPosition.height + widthHeightPadding)  + 'px; ' +
                                        'top:'    + (elementPosition.top    - 5)   + 'px;' +
                                        'left: '  + (elementPosition.left   - 5)   + 'px;');

helperLayer.setAttribute('style', 'width: ' + (elementPosition.width)  + 'px; ' +
                                         'height:' + (elementPosition.height)  + 'px; ' +
                                         'top:'    + (elementPosition.top)   + 'px;' +
                                         'left: '  + (elementPosition.left)   + 'px;');
```

**Comment by bozdoz** [comment]
Shouldn't cause any other issues. It's just a style change/preference.

**Comment by afshinm** [comment]
I believe we have fixed this in the previous version.
