### ISSUE TITLE
addStep() doesn't work

### ISSUE THREAD

**Issue by ethaniel** [usablica/intro.js#711]
My code is:
```html
 <a href="" class="joyride_home">hi</a>
    <script>
		introJs().addStep({
		    element: document.querySelectorAll(".joyride_home")[0],
		    intro: "Ok, wasnt that fun?",
		    position: "right"
		});
		introJs().refresh();
		introJs().start();
    </script>
```

Nothing happens.

**Comment by JamesDonnelly** [comment]
I'm having this issue as well. It doesn't work through the console on http://introjs.com either.

I've tried using the following code, which should apply to the "Browser compatability" icon on the homepage:
```javascript
introJs().addStep({
  element: document.querySelector('fa-globe'),
  intro: "foo",
  position: "right"
})
```

**Comment by vivek12345** [comment]
@JamesDonnely your code needs a minor change. 
Instead of
document.querySelector('fa-globe')

It should be 
document.querySelector('.fa-globe')

I hope that helps.

**Comment by vivek12345** [comment]
@ethaniel instead of querySelectorAll, can you try querySelector

**Comment by ethaniel** [comment]
I think here is the proper way: 

intro = introJs();
intro.addStep({
  element: document.querySelector('fa-globe'),
  intro: "foo",
  position: "right"
});
intro.start();

Documentation is very hard to understand for newcomers.

**Comment by vivek12345** [comment]
@ethaniel this is also incorrect. document.querySelector will take either an ID identifier or class identifier so I this case it should be
document.querySelector('.fa-globe')

**Comment by ethaniel** [comment]
@vivek12345 thanks, fixed!
