### ISSUE TITLE
Exclude steps where item has parrents that are hidden.

### ISSUE THREAD

**Issue by ErikV88** [usablica/intro.js#718]
Exclude steps where item has parrents that are hidden.
Is this available? If  not I will create it, it's irrational that steps that are relvent on the big screen come on mobile too.

**Comment by RamezIssac** [comment]
I faced the same issue, i solved it by: instead of calling the IntorJS directly, i call a function that checks steps location and if not visible, remove the step.

**Comment by bozdoz** [comment]
I don't believe there is a check for parent visibility.  

Currently, I believe, the only checks on parents happen in this while loop: https://github.com/usablica/intro.js/blob/master/intro.js#L1283

It is checking for z-index, opacity, and transform to fix the context stack issue.  

Checking for visibility of parents is likely important as well.
