### ISSUE TITLE
How do I play audio with each step?

### ISSUE THREAD

**Issue by bostondevin** [usablica/intro.js#722]
How do I play audio with each step? I'm amazed this is a new question!

**Comment by bozdoz** [comment]
Try `onbeforechange` or `onafterchange`: http://introjs.com/docs/intro/api/#introjsonbeforechangeprovidedcallback

something like:

```
intro.onbeforechange(function (elem) {
  if (elem.id = "audio-1") {
    audio.play();
  }
});

intro.start();
```

**Comment by afshinm** [comment]
thanks @bozdoz
