### ISSUE TITLE
BUG: oldtooltipContainer not defined

### ISSUE THREAD

**Issue by mkontsek** [usablica/intro.js#732]
oldtooltipContainer on https://github.com/usablica/intro.js/blob/master/intro.js#L423 isn't always defined, then a error is thrown when accessing `style` object in https://github.com/usablica/intro.js/blob/master/intro.js#L527

**Comment by afshinm** [comment]
Thanks for reporting this @mkontsek 

Could you write a jsfiddle for this?

**Comment by mkontsek** [comment]
Sure, right here: https://jsfiddle.net/caa2vsfh/2/
