### ISSUE TITLE
How to use intro.js with Polymer 2?

### ISSUE THREAD

**Issue by amanshu-kataria** [usablica/intro.js#733]
I'm trying to use intro.js in my Polymer 2 application for the first-time users. But, it's not working out for me. Here's the [codepen](https://codepen.io/amanshu_kataria/pen/oeBwNa) link.
Can anyone please help me integrating intro.js into Polymer 2 app?

**Comment by amanshu-kataria** [comment]
@afshinm need help here please.

**Comment by bozdoz** [comment]
Have you tried the programmatic approach?

https://github.com/usablica/intro.js/blob/master/example/programmatic/index.html#L73

**Comment by afshinm** [comment]
+1 @bozdoz 

Please use the JSON form to define the steps.

**Comment by amanshu-kataria** [comment]
@bozdoz It worked but there's some styling issue. The opacity of the focused part is too much. 
As you can see in the images the button is not visible. The button can be slightly seen by taking a close look on it, which means the opacity is too much.
![capture 2](https://user-images.githubusercontent.com/13014093/29274535-d8b0cdbe-8125-11e7-81d9-a56ce11944fb.PNG)
![capture](https://user-images.githubusercontent.com/13014093/29274543-dc88c482-8125-11e7-9c9b-ca20054e2bfa.PNG)

How to fix this?

**Comment by afshinm** [comment]
I believe this is z-index issue. Could you change the z-index of button /
highlight area manually and see if it helps?

I mean, it doesn't related to Polymer specifically.

**Comment by amanshu-kataria** [comment]
@bozdoz tried that. Nothing changed.

**Comment by amanshu-kataria** [comment]
@afshinm tried that but nothing changed.

**Comment by amanshu-kataria** [comment]
@afshinm  How to change the z-index of highlight area?

**Comment by amanshu-kataria** [comment]
@afshinm fixed it. Had to set `z-index: 9999999;`. Thanks :)

**Comment by amanshu-kataria** [comment]
@afshinm the problem has been solved. But, is there's any way to reduce the opacity of the highlighted area? Because the button remains on top of the backdrop even when it is not highlighted, which doesn't looks good. It would be really very helpful if you could please help me with reducing the opacity of the highlighted area.

**Comment by amanshu-kataria** [comment]
@afshinm is there's any way to reduce the opacity of the highlighted area? Because the button remains on top of the backdrop even when it is not highlighted, which doesn't looks good. It would be really very helpful if you could please help me with reducing the opacity of the highlighted area.
