### ISSUE TITLE
Missing Start with first step button

### ISSUE THREAD

**Issue by ssibitz** [usablica/intro.js#744]
Hello !
When i start with a special step but a user want to start from scratch with step 1 he 
can't do this at the moment. 
Aktually the user must navigate back until he is on the start again. 

That's not "user-friendly"...

**Comment by bozdoz** [comment]
Could you please explain, and provide an example?

**Comment by afshinm** [comment]
I don't think that's a good way to report an issue / bug. 

@bozdoz We need to define a template for issues I think

**Comment by bozdoz** [comment]
Agreed. Never done it, but here's the details for it: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by ssibitz** [comment]
I am using now jquery for intro.js and using a script like this to start the intro with Step3 (Containing new features for the user):

```
// Preparing fields via jQuery for use with intro.js:
						// Step1
						$('#step1-large').attr("data-step",   	 "1");
						$('#step1-large').attr("data-intro", 	 "Step1");
						// Step2
						$('#step2-large').attr("data-step",   	 "2");
						$('#step2-large').attr("data-intro", 	 "Step2");
						// Step3
						$('#step3-large').attr("data-step",   	 "3");
						$('#step3-large').attr("data-intro", 	 "NewFeature1");
						// Step4
						$('#step4-large').attr("data-step",   	 "4");
						$('#step4-large').attr("data-intro", 	 "NewFeature2");
						// Step5
						$('#step5-large').attr("data-step",   	 "5");
						$('#step5-large').attr("data-intro", 	 "NewFeature3");
var intro = introJs();
intro.goToStep(3).start();
```
When now the user want to re-start from step1 (From beginning) he has only the option to click back until he is at step1. So i am missing a button for directly jumping back to the start (Step1) like
in the screen-shot i attached...

![intro-sample](https://user-images.githubusercontent.com/652355/29738817-83520420-8a2e-11e7-881d-4bae2da75b1f.png)

**Comment by bozdoz** [comment]
Looks like this is a recommendation for a restart button.  I don't know if this is extremely useful.  Could be a candidate for a plugin.
