### ISSUE TITLE
Tooltips on top navbar cut off (positioned too high)

### ISSUE THREAD

**Issue by deltaGPhys** [usablica/intro.js#748]
This is the same problem as issue 96 (https://github.com/usablica/intro.js/issues/96) from a few years back. That indicates that the issue had been solved viz update, but I'm having the issue with the current version.

**Comment by deltaGPhys** [comment]
To be clear - the tooltip is OK, but the number is half cut off

**Comment by timobehrens** [comment]
I have the same problem:
![image](https://user-images.githubusercontent.com/15941188/35809712-c7272f50-0a89-11e8-8667-f45a61df12cc.png)

**Comment by Sweetyy** [comment]
Same problem for me :(

**Comment by Sweetyy** [comment]
Try :

`.introjs-fixParent {
  position: absolute;
}`

**Comment by deltaGPhys** [comment]
That fix didn't work (actually, it caused the modal that the tooltip was attached to to come unattached and go up to the top of the screen, also)

**Comment by tungmv7** [comment]
> Try :
> 
> `.introjs-fixParent { position: absolute; }`

Works like a charm :) thank you
