### ISSUE TITLE
How to change text of `introjs-donebutton`?

### ISSUE THREAD

**Issue by vanloc0301** [usablica/intro.js#749]
Default text of `introjs-donebutton` is `done`. I want to change this text for my case.

How to do it? Thanks.

**Comment by bozdoz** [comment]
```JavaScript
var intro = introJs();

intro.setOptions({ doneLabel : 'Whatever you want' });

intro.start();
```

See option here: https://github.com/usablica/intro.js/blob/master/intro.js#L40

**Comment by vanloc0301** [comment]
Thanks @bozdoz
