### ISSUE TITLE
onbeforechange: Callback function doesn't receive the new step

### ISSUE THREAD

**Issue by devongermano** [usablica/intro.js#755]
.onchange receives the correct element when called, Eg: 
`introJs.onchange(target => {
console.log(target);
});`
logs: _element_

.onbeforechange does not, Eg:
`introJs.onbeforechange(target => {
console.log(target);
});`
logs: _undefined_

**Comment by bozdoz** [comment]
Looks to be true.  I'm wondering, would you expect the target to be the previous target, the next target, or should both be available?

**Comment by devongermano** [comment]
Currently I'm relying on .onbeforechange receiving the next target, but I think the flexibility of both would be very nice.

**Comment by devongermano** [comment]
Rolled back version from `v2.8.0-alpha.1` to `2.7.0` for now, it seems like a problem with just the alpha as of now... can anyone confirm?

**Comment by bozdoz** [comment]
Can confirm:

https://github.com/usablica/intro.js/commit/52eeb3d918cba9efaca8e29e91e656cbd169aa79#diff-42068bed56449c4ec84ddf8745e56b7cL404

**Comment by afshinm** [comment]
Ok, my bad guys. I think the current behaviour is correct because you don't know what is the next element when `onbeforechange` happens. 

Please note that you can return `false` in the latest version and halt the process. Will send a fix soon.

**Comment by afshinm** [comment]
Just sent the PR. Let me know if you are happy to merge.
