### ISSUE TITLE
Adding buttons with custom behaviours

### ISSUE THREAD

**Issue by bassman2112** [usablica/intro.js#757]
Hi there! 

On the final step of my walkthrough/intro, I would like to give users an option for an "advanced" walkthrough which is only accessible at the end of the simple walkthrough. Think of this as the flow:

User clicks on intro button on dashboard/page -> Opens 5-step Intro -> On step 5 the buttons are "Done," "Back," and "Advanced" 

When they click advanced, this will bring them to a different intro (for example, runs `advancedIntro()` - not just replacing the "next" button, I don't want them to accidentally move through to advanced with the right arrow on their keyboard). 

Is there a way to do this easily, or would it be better for me to fork and customize intro.js to do this?

Thank you very much! =)

**Comment by bozdoz** [comment]
My vote is forking, at this point.  :fork_and_knife:

**Comment by spix26** [comment]
> When they click advanced, this will bring them to a different intro (for example, runs advancedIntro() - not just replacing the "next" button, I don't want them to accidentally move through to advanced with the right arrow on their keyboard).

Should be custom button also can access other javascript function.

**Comment by brandonjamesparkinson** [comment]
Does anyone have an update on how to do this?

**Comment by Paras-Rastogi-23** [comment]
As we know intro.js box contains two buttons "prev" and "next" ...so is this possible to hooke these buttons.I mean when i click on the "next" buttong then some function of javascript will execute

**Comment by Paras-Rastogi-23** [comment]
Please let me know if somebody know this thing
