### ISSUE TITLE
tour on targetElm not working 

### ISSUE THREAD

**Issue by steoo** [usablica/intro.js#758]
I'm trying to execute `introJs(".some-selector").setOptions({... options ...}).start()` but there's no way this is going to work, the tour does not start at all.

HTML is: 

`<div class="some-selector" data-intro="test test"></div>`

Am I missing something? 

[example](https://codepen.io/anon/pen/WZvyOv)

**Comment by bozdoz** [comment]
Thanks for the example.

In this case, you need to fix your HTML.

From the [W3 spec on Paragraph tags](https://www.w3.org/TR/html401/struct/text.html#edef-P):

> The P element represents a paragraph. It cannot contain block-level elements (including P itself).

The problem should be fixed by changing the paragraph tag to a `div` tag, for example.
