### ISSUE TITLE
Commercial license

### ISSUE THREAD

**Issue by stereokai** [usablica/intro.js#766]
@afshinm Hi, we are considering using Intro.js commercially and we have a few questions before we go ahead with it. We did send you an email a few days ago, but never got an answer. Any chance you can address our questions? Thanks!

1. What kind of license is the commercial one?
1. One of the provisions of each license is the number of projects you can use Intro.js in. What is your definition of a project?
1. In the GitHub readme you state that a commercial license is required for using plugins - what are plugins?
1. We would like to use angular-intro with Intro.js, which is under the AGPL license as well. (We are aware it is not your work). We would like to know, if we purchase Intro.js, does it affect third-party wrappers like this one.

**Comment by magnusvikstrom** [comment]
We are looking into using intro.js with angular-intro.js as well. Did you resolve this issue?
