### ISSUE TITLE
".call(self)" leads to ReferenceError in Node.js environment

### ISSUE THREAD

**Issue by andreyg-moby** [usablica/intro.js#767]
When intro.js is used in scope of test automation in strict Node.js environment, it leads to `ReferenceError` exceptions because of missing `self`` in scope:

Example: https://github.com/usablica/intro.js/blob/cf080c1a8edbf984c94cb9bf61e5bedc5f6ab802/intro.js#L512

Proposed solution:

1. Add 'use strict' in scope of https://github.com/usablica/intro.js/blob/cf080c1a8edbf984c94cb9bf61e5bedc5f6ab802/intro.js#L8

2. Replace broken "this.X.call(self)" with "this.X()" or "this.X.call(undefined)"

3. Fix other possible issues found

**Comment by bozdoz** [comment]
Thanks! Already addressed in #764
