### ISSUE TITLE
Intro goes off screen for elements at right edge of page

### ISSUE THREAD

**Issue by russellsmith** [usablica/intro.js#77]
With elements that are on the right edge of the screen the intro overlay will be displayed off screen in Chrome 26.  A fiddle displaying this behavior:

http://jsfiddle.net/3vcbr/

**Comment by doublej74** [comment]
I encounter this problem with a navigation menu on the left. The intro has position set to auto, is displayed on the right side and goes off screen at the top of the screen (can't see the first few lines of the intro)
