### ISSUE TITLE
Any chance of 2 decimal places and auto numbering???  Suggestion not bug

### ISSUE THREAD

**Issue by stevehomer** [usablica/intro.js#770]
I love intro.js. Only one thing drives me crazy that is if you need to edit a page and put a new tour stop in.

On one page I have about eight stops. Now I want to add a new stop between 2 and 3 so I have to hunt down pre existing stops and renumber.  3 goes to 4 ... 8 goes to 9...

I am a fairly crap coder and can never find the intro.js calls very quickly.

If we had decimals then we would only have to reorder a couple of steps eg:
1 2 3 4 5 6 7
with two new ones and one taken out
1 2 2.2 2.7 3 4 5 7

Sorry I cannot code this but it looks fairly straightforward to me in js

-- Count number of stops
-- loop through lowest to highest and (via InnerHtml or whatever) substitute `i` in place of original number...
                                 And that's that.

We could use a `decimals:true` or something like that to activate.

Once again I apologise for not coding this myself - I am very very slow with js.

And once more thanks
Steve

PS Sad to say have given up on intro.js.

**Comment by bozdoz** [comment]
Love the idea of decimals.
