### ISSUE TITLE
targetElement is gone on some onCallbacks (e.g. onbeforechange). A Step index would be nice btw

### ISSUE THREAD

**Issue by sfiedler90** [usablica/intro.js#776]
If I register a callback function the targetElement is mostly undefined. 

And as an additional, a returned step number or the step configuration would be nice to handle different cases.

**Comment by swifty-team** [comment]
+1
for me onbeforechange give me only 'undefined'.

step's index is needed for quick access

**Comment by chrismbarr** [comment]
Looks like a dupe #207 which was opened in 2013, lol
