### ISSUE TITLE
Error: Uncaught TypeError: Cannot set property 'className' of null

### ISSUE THREAD

**Issue by sergsagan** [usablica/intro.js#783]
I'm using the version  2.8.0-alpha.1 in the project
example Multi-page.
I receive an error in the console:
**Uncaught TypeError: Cannot set property 'className' of null**

**Comment by bozdoz** [comment]
I'm not sure I understand how to reproduce the error.  Are you saying that the multi-page example on this repo is producing that error?

**Comment by sergsagan** [comment]
yes, it was he

**Comment by sergsagan** [comment]
The problem disappeared: added an additional step to the second page
