### ISSUE TITLE
OnSkip callback needed

### ISSUE THREAD

**Issue by LukeBillo** [usablica/intro.js#788]
I'm currently in need of an OnSkip callback so that I can record when a user skips a tour - it's mainly for analytics.

Was wondering if there's currently a way of doing this? I also noticed there's a PR for adding it in  ( #517 ) and was wondering when this would be merged in?

**Comment by shivamrr9** [comment]
"onskip" worked for me!

**Comment by juliettebeaudet** [comment]
onskip callback now exists but is still undocumented.
