### ISSUE TITLE
React Wrapper

### ISSUE THREAD

**Issue by plysik** [usablica/intro.js#789]
Hi Guys,

is there development of REACT wrapper ongoing? Or maybe can you recommend any?
I found some wrappers in Your documentation, but not the REACT one...

**Comment by eeh** [comment]
I found this one:

https://github.com/HiDeoo/intro.js-react

**Comment by bozdoz** [comment]
At a glance that looks like a lot of great work went into that react library.  Looks clean, and great for development.
