### ISSUE TITLE
Need to allow return a promise within onbeforechange, onafterchange and onchange

### ISSUE THREAD

**Issue by ivorobioff** [usablica/intro.js#791]
I have integrated introjs to one of the projects I worked on and found one thing that is really missing/needed in this beautiful library.
 
Sometimes, it happens that before moving to the next/previous step we need to trigger some stuff and wait till it's ready so that when moving to the next step all the needed elements are on the page and introjs can catch them up. 
For example, it could be that some elements are loaded with ajax, and that would be cool to have ability to wait till request completes and all the needed elements are inserted onto the page.
Another example is animation. Some elements appear on the page with animations, and it would be useful to wait till animation is finished before moving to the next step. 
All in all, I'd really love to see in the library ability to return promises within "onbeforechange", "onafterchange" and "onchange" methods. 

For example,

```javascript
introjs.onbeforechange(function(el){

	//... some code

       return $.get('/items').done(function(html){
		$(el).html(html);
       });
});
```

In the example above, initially, the step is bound to an empty element. Then, before moving to it, we want to load html and insert it into that element. Since the html is taken from the server we want to wait till html is retrieved and  inserted. Once that done, we move to the step and introjs should catch the things up as normally. 

What do you think? I have already implemented everything mentioned above. Just one to know you opinion before creating another pull request :)

**Comment by guanzo** [comment]
I can confirm that this would be very useful.

**Comment by envision** [comment]
Very much needed!

**Comment by JeanZhao** [comment]
Terribly needed!

**Comment by vitorleonel** [comment]
Very much needed!

**Comment by jpike88** [comment]
This library has aged like milk. 92 pull requests. I think people need to abandon or fork. I'm going to fork.

**Comment by jpike88** [comment]
Also, documentation is out of date.

Things like this in the code are not mentioned:

```

    if (typeof (this._introBeforeChangeCallback) !== 'undefined') {
      continueStep = this._introBeforeChangeCallback.call(this, nextStep.element);
    }

    // if `onbeforechange` returned `false`, stop displaying the element
    if (continueStep === false) {
      --this._currentStep;
      return false;
    }
```

**Comment by SamanthaAdrichem** [comment]
This is so desired, and it just got closed without any change :(

**Comment by SamanthaAdrichem** [comment]
So i've provided a PR.

This is how the code has been implemented in our system, allowing us to open modals and wait until they are done loading.
I'm currently loading our fork. But would be nice if you guys could test it further and eventually create it as a version.

```
this.introJs.onbeforechange(async () => await this.stepChange());


public async stepChange(): Promise<void> {
	const currentStepIndex: number = this.introJs._currentStep;

	if (this.currentStepIndex && 'function' === typeof this.steps[this.currentStepIndex]?.onLeave) {
		await this.steps[this.currentStepIndex]?.onLeave();
	}

	if (!this.steps[currentStepIndex]) {
		return;
	}

	if ('function' === typeof this.steps[currentStepIndex]?.onEnter) {
		await this.steps[currentStepIndex]?.onEnter();
	}

	// Refresh element selection
	if (this.steps[currentStepIndex].elementSelector) {
		this.steps[currentStepIndex].element = document.querySelector(this.steps[currentStepIndex].elementSelector);
	}
	this.currentStepIndex = currentStepIndex;
}

onEnter: () => {
	return new Promise((resolve: () => void) => {
		const subscription: Subscription = this.campaignModalService.bsModalService.onShown
			.subscribe(() => {
				resolve();
				subscription.unsubscribe();
			});
		this.campaignModalService.show(TourComponent.TOUR_CAMPAIGN_ID);
	});
}
```

**Comment by danielvandermaas** [comment]
Thank you for creating this PR, it is really useful :)

**Comment by afshinm** [comment]
PR https://github.com/usablica/intro.js/pull/1712
