### ISSUE TITLE
How to apply css to individual tip in intro.js ?

### ISSUE THREAD

**Issue by nandaram19** [usablica/intro.js#805]
I'm using your plugin which is great but I come across some requirement which demands to apply different css to each tip. Although we can use setOptions but it applies css to whole Tips.
So please solve this issues or provide alternate.

**Comment by RomainCscn** [comment]
Hello, you can use `tooltipClass` to specify a css class to a tooltip. For example:

```
const intro = introJs();
intro.setOptions(
  {
    steps: [
      {
        intro: "My example",
        tooltipClass: 'main-tooltip'
      }
    ],
  });
```

**Comment by ranjith19** [comment]
Your API docs do not say that I can pass tooltip class to each step.

What other args could I pass to each step?
