### ISSUE TITLE
The content is covered

### ISSUE THREAD

**Issue by xiaozhanghui** [usablica/intro.js#808]
The content is covered
![tim 20180112142257](https://user-images.githubusercontent.com/23646391/34862208-2267ec54-f7a4-11e7-8074-77f890a0b263.png)

**Comment by mdahlke** [comment]
@xiaozhanghui Any luck on this? I'm having the same issue with multiple versions (master, 1.7, 1.6).

**Comment by bozdoz** [comment]
Duplicate of #123

**Comment by xiaozhanghui** [comment]
z-index conflict transform @mdahlke
