### ISSUE TITLE
CLA for intro.js contributions

### ISSUE THREAD

**Issue by cmrd-senya** [usablica/intro.js#814]
Contributions guidelines for your project don't say anything about [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) for the project contributors. At the same time you provide dual licensing of your library: AGPLv3 and proprietary license. However if you don't request an explicit permission from your contributors whose changes you have accepted, you can't distribute their changes under a proprietary license (this is because you received their contributions under AGPLv3 terms in your turn). If your contributors didn't give you explicit permission for distributing their contributions under the proprietary license, then basically distribution of your software under the proprietary license is illegal.

Could you please clarify that moment and possibly make changes to the contribution documentation?

**Comment by bozdoz** [comment]
Might need one of these @afshinm: https://github.com/Microsoft/vscode/wiki/Contributor-License-Agreement

**Comment by bozdoz** [comment]
Something like what Facebook is doing looks good too: https://code.facebook.com/cla/individual
