### ISSUE TITLE
Intro Js is not working with the other component

### ISSUE THREAD

**Issue by vibingopal** [usablica/intro.js#816]
## Description
Hi,
I integrated introJs Module in my angular Project. It works fine when i click on main menu with Introduction. But i have sub menu where the component redirects to particular page but intro is not working on that new component.

Perhaps as per document and api provided , i tried to start the help feature by explicitly mentioning 

>  const IntroJs2 = require('../../../../node_modules/intro.js/intro.js');
>         IntroJs2.introJs('.addPool').start();
> 

But i am getting an issue with the operation - "Error: There is no element with given selector."

## Expected Behavior
IntroJs should work as mentioned in the docs provided.

## Actual Behavior
Intro should be visible for every component.

Please let me know why we are seeing this issue ?

**Comment by vibingopal** [comment]
Any update on this please ?

**Comment by Benderjrk** [comment]
Curious on anything you may find on this happening

**Comment by Benderjrk** [comment]
seems my problem may be because of ui bootstrap getting skipped over somehow and typeof reading as undefined and being replaced with the model in the center of the screen.

**Comment by alaparsalan** [comment]
I found a solution guys

well im not CSS guy but this works soo fine
`.introjs-helperLayer {
    // opacity: 0 !important;
    border-radius: 0.5em !important;
    border: 0.2em solid rgba(255, 255, 255, 0.9) !important;
    box-shadow: 0 0 0 1000em rgba(0, 0, 0, 0.7) !important;
    // opacity: 1 !important;
    // z-index: 99999 !important;
    // background: transparent !important;
    // position: relative !important;
    pointer-events: none; 
}`
 pointer-events: none;  is the issue causing this issue
