### ISSUE TITLE
Move Done Button to the right of Back and Next Buttons

### ISSUE THREAD

**Issue by ghost** [usablica/intro.js#817]
## Description
I think from a UX perspective, it would make sense for the Done button to be to the right of Back and Next. Better yet, perhaps the final next button could be replaced with Done? Interested in hearing any feedback.

## Errors and Screenshots (optional)
<img width="233" alt="screen shot 2018-01-24 at 7 08 03 pm" src="https://user-images.githubusercontent.com/13770733/35368809-0a60d3ec-013a-11e8-870b-9d7a2b2d38dd.png">

**Comment by skmbr** [comment]
It's not ideal, but I've done this as a temporary solution....

.introjs-donebutton {
    float: right;
    margin-left: 5px;
}

**Comment by jakegarelick** [comment]
@skmbr This is what I did in my image
```
&.tooltip__last {
    .introjs-tooltipbuttons {
      display: flex;
      flex-flow: row-reverse;

      .introjs-donebutton {
        margin-right: 0;
      }

      .introjs-prevbutton {
        margin-right: 5px;
      }
    }
  }
```
with hideNext: true

**Comment by jeffatpf** [comment]
Agreed!

**Comment by iamakimmer** [comment]
Used this approach:

`
.introjs-tooltipbuttons {
   display: flex;
}
.introjs-donebutton {
   order: 3; //or wherever you want it 
}

`
