### ISSUE TITLE
Implement smooth scrolling?

### ISSUE THREAD

**Issue by megaroeny** [usablica/intro.js#828]
## Description
Right now (based on your demo), when scrolling the page instantly jumps to the next section. This can be jarring to the user and would be much nicer if the page scrolled smoothly to that section.

## Expected Behavior
For the page to scroll to the next section

## Actual Behavior
The next section caused the page to *jump* instantly

## Example (recommended)
LinkedIn's onboarding library, Hopscotch, has nice smooth page scrolling: http://linkedin.github.io/hopscotch/

## Additional notes
Would be nice since we would have to add this to intro.js, that there was an option for scroll timing/duration

**Comment by jaminroe** [comment]
@Egrace I have no clue. I don't write any JS 😅

**Comment by Zvonimir1995** [comment]
To anyone who might look for this again, check out my response here https://github.com/usablica/intro.js/issues/1719#issuecomment-1854055937
