### ISSUE TITLE
skip and done not work 

### ISSUE THREAD

**Issue by pranaysonisoft** [usablica/intro.js#832]
## Description
Skip and Done not work in example  index.html
intro.js-master/example/hello-world/index.html

## Expected Behavior
 skip tour

## Actual Behavior
Uncaught TypeError: Cannot read property 'call' of undefined
    at HTMLAnchorElement.skipTooltipButton.onclick (intro.js:1266)

## Errors and Screenshots (optional)
Give us any additional information if you have.

**Comment by sohrab-salehi** [comment]
I had the same problem
Use stable version 2.7.0 and it solves

**Comment by cavo789** [comment]
Same for me. Using 2.7.0 and the problem has disappeared.

**Comment by parmarsanjay** [comment]
Same for me. Using 2.7.0 and the problem has disappeared.

**Comment by pjuchniewicz** [comment]
After doing some debugging, it looks like the code in **skipTooltipButton.onclick** was not setup to check if the _introSkipCallback is defined before it tries to call() on it.

Quick fix until the code gets adjusted to check for this is to add an empty function for onskip:
.onskip(function () {});

**Comment by lito003** [comment]
Same for me, but not before 2.9.0 - and I really want to use latest version of IntroJS due to the scrollable div improvement.

Agree to @pjuchniewicz - simply check if a function is defined as done for self._introExitCallback.

But quick fix works great :)

**Comment by cssagogo** [comment]
+1, worked on v2.8.0-alpha.1 but 2.9.0 and 2.9.1 it is broken.

**Comment by dperish** [comment]
Seeing this issue with 2.9.0, loaded with systemjs

**Comment by bozdoz** [comment]
Please update your versions.  2.9.0 is 3 versions old.

**Comment by dperish** [comment]
Ahh, the 2.9.3 release wasn't there this morn.  I see it now, thanks.
