### ISSUE TITLE
Destroy all hints and steps

### ISSUE THREAD

**Issue by parmarsanjay** [usablica/intro.js#834]
Is it possible to destroy all the hints and steps? 

This is what I'm seeing. 

#1 User navigates specific page..
#2 Show the hints specific to this page. 
#3 User navigates to other page. 
#4 I don't want to show any hints. For some reason I continue to see the hints from #2 on this new page.

**Comment by parmarsanjay** [comment]
Looks like there's a API to remove all hints.

intro.removeHints();
intro.removeHint();

It's not part of the documentation.

**Comment by bakztfuture** [comment]
I am still experiencing this issue on Safari.  I've tried using removeHints() even though my main has steps, I've also tried manually setting the steps to null inside the introJs instance, still have had no luck.
