### ISSUE TITLE
Tooltip is not highlighting a dynamic element

### ISSUE THREAD

**Issue by Klass-A** [usablica/intro.js#837]
Our products menu is dynamically generated using PHP MVC.
And I want to point the last step of the tooltip on a button that is in the first products card.
(I am using the setOptions not the inline data-attribute.)
I have selected that button using jQuery, please see the code for the step I'm referring to.

`{
          element: $('.add_to_cart:nth-child(2)')[0],
          intro: '<div class=\'tooltip_js\'>Last Step</div>',
          tooltipClass: 'last-step',
}`

But the tooltip is not selecting and highlighting the element and It's placed in the center of the screen.

_Any help with this would be much appreciated.
I couldn't find much information on this particular case of selecting dynamic elements._

**Comment by jhadenfeldt** [comment]
That sounds like the element does not exist on the page the moment you set the option. What happens if you paste `$('.add_to_cart:nth-child(2)')[0]` into the console of your dev tools?
