### ISSUE TITLE
while using Multi page both oncomplete and onexit functions trigger

### ISSUE THREAD

**Issue by SKMDC** [usablica/intro.js#842]
## Description
While trying to use Intro.js across multiple pages, where onexit creates a cookie and oncomplete goes to the next page, both functions are triggered causing the second page's Intro.js steps to never be shown

## Expected Behavior
Upon completion of the first pages Intro.js steps, the user should be directed to the second page with its Intro.js steps should start

## Actual Behavior
Upon completion of the first pages Intro.js steps, the oncomplete function is triggered redirecting the user to the second page and the onexit function is triggered creating a cookie which keeps Intro.js from loading on the second page

## Example
Make these changes in the multi-page example provided in the project
Note: if testing using these files locally, you can't use Chrome b/c a cookie won't be created

index.html:
```
    document.getElementById('startButton').onclick = function() {
        if(document.cookie.indexOf("introjs") < 0) {
            introJs().setOption('doneLabel', 'Next page').start().oncomplete(function() {
                console.log("oncomplete");
                window.location.href = 'second.html?multipage=true';
            }).onexit(function() {
                console.log("onexit");
                var expires = "";
                var date = new Date();
                date.setTime(date.getTime() + (30 * 24 * 60 * 60 * 1000));
                expires = "; expires="+date.toUTCString();
                document.cookie = "introjs=true"+expires+";"; 
            });
        }
    };
```

second.html:
```
    if (RegExp('multipage', 'gi').test(window.location.search)) {
        if(document.cookie.indexOf("introjs") < 0) {
            introJs().start();
        }
    }
```

## Environment
Intro.js version > 2.4.0

My solution thus far has been pinning the version to 2.4.0, but I'd like to be able to upgrade the version if possible

**Comment by timothyyjoo** [comment]
Is there any guidance on this issue for future releases?

**Comment by juliettebeaudet** [comment]
That was actually a really useful issue @SKMDC , did you find any solution? I am having the exact same phenomenon.
