### ISSUE TITLE
Cannot end the intro

### ISSUE THREAD

**Issue by dylanlt** [usablica/intro.js#843]
Clicking on skip or end results in an error because _introSkipCallback is null in c._introSkipCallback.call(c)

![bug1](https://user-images.githubusercontent.com/7636222/39162895-2a67cbb0-47bb-11e8-9cb3-1b470aaa56b5.PNG)

Example code:
    $.ajax({
	    url : siteurl + "/_api/web/lists/getbytitle('Introduction')/items?$orderby=Order",
	    contentType : "application/json;odata=verbose",
	    headers : requestHeaders,
	    success : function(data){
	    	var results = data.d.results;
		    	for (var i = 0; i < results.length ; i++) {
			    	var intro= {element:results[i].Component, intro:results[i].Description, position:results[i].Position};
			    	IntroSteps.push(intro);
		    	}
		    	var intro = introJs();
	          	intro.setOptions({
	            	  steps: IntroSteps
	         	});
				
	          	intro.start();	    	

	    },
	    error : function (data){}
  	});

(IE11 + SharePoint 2013)

**Comment by dylanlt** [comment]
extra html tags from a copy paste caused this (</head>)

**Comment by victorlevasseur** [comment]
Take a look at this issue, it contains a workaround (I successfully used it in my project) : https://github.com/usablica/intro.js/issues/832

**Comment by dylanlt** [comment]
Awesome, thank you Victor!
