### ISSUE TITLE
Cannot set property 'keydown0_1' of undefined

### ISSUE THREAD

**Issue by Themandunord** [usablica/intro.js#846]
## Description
Hi, in my app, I have one problem with the lastest version of intro.js.

## Expected Behavior
No errors

## Actual Behavior
When I change page in my react page, I have an error.

## Errors and Screenshots (optional)
![image](https://user-images.githubusercontent.com/2819925/39196203-cfafded4-47e1-11e8-86c4-91b85f54c4e3.png)

![image](https://user-images.githubusercontent.com/2819925/39196266-f47a0da2-47e1-11e8-882c-c6ad9eb715a5.png)
(sorry it is on production)

## Example (recommended)
I use [https://www.npmjs.com/package/intro.js-react](https://www.npmjs.com/package/intro.js-react)

**Comment by bozdoz** [comment]
Hopefully 2.9.1 will fix that.  Thanks for the screenshots

**Comment by afshinm** [comment]
@bozdoz thanks for this quick fix!

**Comment by Themandunord** [comment]
Whoo so fast :)

Thanks it works again !
