### ISSUE TITLE
NPM package not in alignment with GitHub repo

### ISSUE THREAD

**Issue by cssagogo** [usablica/intro.js#847]
## Description
The NPM package changed between 2.8.0-alpha.1 and 2.9.1.  The new package does not contain the minified folder.  

https://www.npmjs.com/package/introjs

## Expected Behavior
For the directory structure to remain the same or at very least a equivalent minified version be available in the updated package.

## Actual Behavior
Minified versions do not exist.

**Comment by bozdoz** [comment]
Enjoy

**Comment by afshinm** [comment]
BTW this is the correct package on NPM: https://www.npmjs.com/package/intro.js

**Comment by cssagogo** [comment]
@bozdoz  Perfect. Thanks.

@afshinm  Good catch.  I'm pulling in the right package, just typo here.
