### ISSUE TITLE
"nextStep is undefined" on last step when pressing right arrow keyboard button

### ISSUE THREAD

**Issue by chrismbarr** [usablica/intro.js#849]
## Description
Using Intro.js 2.9.3, when I go to the last step of a tour the "Next" button is (correctly) disabled, however if I've set `keyboardNavigation: true` and I press the right arrow keyboard button on this last step, I get an error in the console.

## Expected Behavior
No errors

## Actual Behavior
Error `TypeError: nextStep is undefined` appears in the console

**Comment by jhorowitz-firedrum** [comment]
Fixed in PR #871
