### ISSUE TITLE
onexit gets called twice when you click the skip button

### ISSUE THREAD

**Issue by cssagogo** [usablica/intro.js#850]
## Description
When you click the skip button the onexit function fires twice.  I would use onskip, but it does not get fired when you click the transparent background overlay.  I need a method of firing an event anytime the tour exits.

## Expected Behavior
The onexit function should only be called once.

## Actual Behavior
onexit is called twice 

## Example (recommended)

```
            var intro = introJs();
            intro.setOptions({
                overlayOpacity:     0.8,
                scrollToElement:    true,
                showBullets:        false,
                showProgress:       true,
                showStepNumbers:    false,
                disableInteraction: true,
                hidePrev:           true,
                hideNext:           true,
                doneLabel:          'Exit Tour',
                skipLabel:          'Exit Tour',
                steps:              this.getSteps()
            });
            intro.start();
            intro.onexit(function() {
                console.log('exit.tour');
            });
```

**Comment by cssagogo** [comment]
As a work around I found I can use onbeforeexit

**Comment by jhorowitz-firedrum** [comment]
Fixed in PR #871

**Comment by OAnouman** [comment]
I got the same issue using version 2.9.3

**Comment by libattistella** [comment]
Any update on this issue? I have this bug too in version 2.9.3

**Comment by subasically** [comment]
I am experiencing this issue as well. Using version 2.9.3

**Comment by benelliott** [comment]
bump

**Comment by AlbertMN** [comment]
Still an issue. Using `onbeforeexit` instead is still a "fix"

**Comment by afshinm** [comment]
Please install 3.0.1 and let me know if the issue is fixed. Thanks and apologies for the delay.

**Comment by ayesha-iftikhar-relayr** [comment]
@afshinm I'm currently using introjs `3.2.1`,  introjs-react `0.3.0`; and the issue still exists.
