### ISSUE TITLE
Problem with work

### ISSUE THREAD

**Issue by ArtemPavliienko** [usablica/intro.js#854]
Hello. 

I can not understand. Why does the plugin work so crookedly? Positioning also does not work. I tried writing in js and in the tag.

https://repl.it/@Kvazarmw/MammothStupidPercent

**Comment by bozdoz** [comment]
More information is needed on this one.

**Comment by ArtemPavliienko** [comment]
if the text is a lot that the plugin does not work, the .introjs-tooltip block is not correctly positioned. The example shows.

And if there is not a lot of text, for example, so much:  "Lorem ipsum dolor sit amet, consectetur adipisicing elit." . Then everything works correctly. 

Why is that and how to fix it?

**Comment by bozdoz** [comment]
I believe what is happening is that there is no room on the screen to display the tooltip above, below, or to the sides of the content, so it shows the tooltip over the content.  As far as I know, that's how it is supposed to work.  I understand that this is opinionated.

**Comment by ArtemPavliienko** [comment]
that is, do you need to use a small text? There are no options, how can you use large text, but what will be displayed well?  There is an option that automatically turns on the scroll if the content does not fit: "scrollToElement". But for some reason it does not work
