### ISSUE TITLE
Scrolling inside containers doesn't reposition the tooltip

### ISSUE THREAD

**Issue by jhadenfeldt** [usablica/intro.js#855]
## Description
The tooltip should be repositioned when the container the tooltip refers to, has been scrolled

## Expected Behavior
I expect the tooltip to always point to the correct element.

## Actual Behavior
When scrolling, the target element and the tooltip become disconnected.

## Screenshots
![scrollingbug](https://user-images.githubusercontent.com/959356/39724316-4ea7fa9e-51fd-11e8-91e1-4d2d833e787c.PNG)

## Example
https://jsfiddle.net/0tgrfmje/ - Go to step 1, make sure the cursor is over the highlighted area and then scroll.

## Related PR
https://github.com/usablica/intro.js/pull/801 is related, but not the cause of the issue.

**Comment by benelliott** [comment]
bump

**Comment by benelliott** [comment]
bump

**Comment by benelliott** [comment]
bump

**Comment by fantypants** [comment]
Just had this, looking into it now. Will update with a temp fix or a PR if interested

**Comment by afshinm** [comment]
PR merged.
