### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by Deval9** [usablica/intro.js#864]
Get Error when we click on Done button.

intro.js:1266 Uncaught TypeError: Cannot read property 'call' of undefined
    at HTMLAnchorElement.skipTooltipButton.onclick (intro.js:1266)
skipTooltipButton.onclick @ intro.js:1266

![error](https://user-images.githubusercontent.com/4348463/40296748-23754968-5cfb-11e8-87ff-99b03f809a32.png)

**Comment by Deval9** [comment]
@afshinm Please have look in this issue it is very important with new version v2.9.0

**Comment by bozdoz** [comment]
Please update to v2.9.3!

**Comment by Deval9** [comment]
Thank you
