### ISSUE TITLE
position -right-aligned not working

### ISSUE THREAD

**Issue by JusuVh** [usablica/intro.js#868]
The step position '*-right-aligned' (and all the aligned position for that matter) is not working at all for me.
I checked in you code and there are several things I don't quite understand.

In the **_determineAutoAlignment** function, you remove the '-right-aligned' possible alignement when **offsetLeft < tooltipWidth**. This means that if the highlighted element takes up most of the window width (offsetLeft is then small), it's not possible to align to the right, although there is a lot of space to align to the right.

Should the check rather be **offsetLeft + winWidth < tooltipWidth** ? Meaning, if the highlighted element width + the offset on the left leaves enough room for the tooltipwidth, under the element for example, the '-right-aligned' alignement should be possible.

This should also be changed for 'middle-aligned'.

**Comment by Stanley521** [comment]
I needed this too, do you have any progress for now? @JusuVh 

I tried using 
setTimeout( function ()  {
$('.introjs-tooltip').addClass('right-position');
}, 600);

.right-position {
  left: unset !important;
  right: 15px !important;
}
it worked, but with a bit delay, any faster delay, introjs will reapply left-aligned

**Comment by JusuVh** [comment]
Hi @Stanley521 ,
I corrected the issue on my side, simply by changing line 903 on my local _**intro.js**_ file with 

`if (offsetLeft + winWidth < tooltipWidth) {`

instead of 

`if (offsetLeft < tooltipWidth) {`

If you're not using any framework, you can do the same as a quick fix.

**Comment by Stanley521** [comment]
I have tried your way and it worked perfectly, the only downside is it doesn't work with npm install.

**Comment by JusuVh** [comment]
If you want to use it in an angular app, you can copy the script to a folder in your project (e.g. /lib/intro.js/) and then add 

```
"scripts": [
   "src/lib/intro.js/intro.js"
]
```

to your angular.json file. If you're using another framework, i'm sure there's some other way too.
