### ISSUE TITLE
AutoPosition for Bottom is wrong?

### ISSUE THREAD

**Issue by jvalst** [usablica/intro.js#873]
## Description
When the autoposition for bottom is triggered, it needs double space then needed (wrong coding)

## Expected Behavior
The tooltip should get bottom if there is room there.

## Actual Behavior
Tooltip will float.

## Errors and Screenshots (optional)
The code in the function determineAutoPosition is wrong. This is the current code:

```
// Check for space below
    if (targetElementRect.bottom + tooltipHeight + tooltipHeight > windowSize.height) {
      _removeEntry(possiblePositions, "bottom");
    }

```

Shouldn't it be? 
```

// Check for space below
    if (targetElementRect.bottom + tooltipHeight > windowSize.height) {
      _removeEntry(possiblePositions, "bottom");
    }
```

**Comment by pg1671** [comment]
+1

**Comment by rkabanov** [comment]
I've faced this issue too. What is the reason to add tooltipHeight twice?
