### ISSUE TITLE
Deprecated: please use require("intro.js") directly, instead of the introJs method of the function

### ISSUE THREAD

**Issue by zedsimple** [usablica/intro.js#874]
I got this error when using introjs 2.9 version,but 2.8 work well. How can i fix it?

**Comment by bozdoz** [comment]
Use `require('intro.js')` like the warning says.

**Comment by SidMorad** [comment]
Does anybody here knows how to make this warning disappear in typescript?

And this is my working syntax for version `2.8.0-alpha.1`:
```typescript
import introJs from 'intro.js/intro.js';
...
    const intro = introJs.introJs();
    intro.setOptions({
      steps: [ { element: '#pin-1', 'Select pin one', position: 'auto' } ]
    });
    intro.start();
```

And after updating to `2.9.0` I notice above syntax works in one page and not in another page, but that is different story I guess. So I don't want to see this warning in typescript, what should I do? thanks.

**Comment by bozdoz** [comment]
How are you importing/requiring the library?

**Comment by SidMorad** [comment]
@bozdoz Thank you for the link, that helped me to solve my issue.

I am using the library in an Ionic 3 project, and here is how I did fix my issue:
```typescript
import introJs from 'intro.js/intro.js';
...
    const intro = introJs();
    intro.setOptions({
      steps: [ { element: '#pin-1', 'Select pin one', position: 'auto' } ]
    });
    intro.start();
```
So in summary instead of `const intro = introJs.introJs()` we simple use `const intro = introJs()` which is shorter, thanks! :+1: 

p.s. It also works fine in all pages of my application, thanks again.

**Comment by bozdoz** [comment]
I would also be surprised if you needed `import introJs from 'intro.js/intro.js';`

Wouldn't this work?

`import introJs from 'intro.js';`

**Comment by bozdoz** [comment]
Also, glad it worked out. Thanks!

**Comment by SidMorad** [comment]
> Wouldn't this work?
>
> `import introJs from 'intro.js';`

Not for my setup, I do receive following error in console:

```js
 ERROR ReferenceError: introJs is not defined
```
Thanks!

**Comment by bozdoz** [comment]
Weird.  Sounds like a bug.

**Comment by bozdoz** [comment]
What about `import * as introJs from 'intro.js'`?  Note: I have not actually looked into this on my machine.

**Comment by Stiveknx** [comment]
```import * as introJs from 'intro.js'```

worked too (Y)

**Comment by bmustata** [comment]
<pre>
import IntroJs from 'intro.js'
import 'intro.js/minified/introjs.min.css'
</pre>
