### ISSUE TITLE
Cannot find name 'introjs'

### ISSUE THREAD

**Issue by CyrilEdison** [usablica/intro.js#877]
## Description
After installation compiler shows " Cannot find name 'introjs' "

## Expected Behavior
Intro js installed but not working properly as it shows " Cannot find name 'introjs' "

**Comment by mbryant1988** [comment]
I believe it may be named 'intro.js' instead of just 'introjs'

**Comment by bozdoz** [comment]
Duplicate of #874?  Please confirm
