### ISSUE TITLE
Bootstrap 4 Tabs

### ISSUE THREAD

**Issue by JimmySbordoneJr** [usablica/intro.js#880]
Hello,

I know others must have encountered this issue. When creating a tour of a site that uses tabs, if the next step in the tour is a tab that is not open, the highlighted box goes to the top left corner of the webpage. 

![image](https://user-images.githubusercontent.com/40463726/43906951-76eb2ec2-9bc2-11e8-8995-0f8963458d0c.png)

Visit [our website](http://www.northernpomolanguagetools.com/qr_codes/introduction.html) to see this activity.

Version 9.2.3

Thank you for your hard work in creating this project. Other than this one small bug, it works fantastically! 

Best,
Jimmy

**Comment by pg1671** [comment]
I usually use the onbeforechange event to click on the tab when the next tooltip is in a new tab.

**Comment by JimmySbordoneJr** [comment]
Thank you!

**Comment by JimmySbordoneJr** [comment]
Actually, now I have a slightly different issue: now, the tooltip flies away if I have one tab open and try to go back to a previously open tab. I tried to use onbeforechange to click on the appropriate tab, and it is not working. Is onbeforechange not the right function here?

	introJs().onbeforechange(
		function(targetElement) {  
			switch (targetElement.id) 
			{ 
			case "Phrasicon-tab": 
				targetElement.click();
				break; 
			case "SeeAlso-tab": 
				targetElement.click();
				break;
			case "Examples":
				document.getElementById("Examples-tab").click();
				break;
			}
	}).start();

**Comment by shayeste1996** [comment]
> @JimmySbordoneJr Note that click() must be called on the element that has data-toggle="tab" attribute. This is the element that actually toggles tab, not its parent element.

would u plz explain in more i have the same issue but cant solve it... thanks in advance
