### ISSUE TITLE
Relative Positioning

### ISSUE THREAD

**Issue by JimmySbordoneJr** [usablica/intro.js#881]
Hello,

I used relative positioning to adjust the Facebook and Twitter share buttons on our site, as they do not sit in line with each other by default. As expected, the highlight box is highlighting the original position of the element.

![image](https://user-images.githubusercontent.com/40463726/43907619-e015066a-9bc3-11e8-9141-ead9f8604eb4.png)

Is there any way I can tinker with this page to get the highlight box to center on the buttons' new positions?

Version 9.2.3

Best,
Jimmy

**Comment by sk0028** [comment]
Avoid relative position and try to get the the buttons aligned. A workaround this is possible but will be a nasty use of JQuery.

**Comment by JimmySbordoneJr** [comment]
> Avoid relative position and try to get the the buttons aligned. A workaround this is possible but will be a nasty use of JQuery.

Hi Shradhan, 

Believe me, I tried. Have you worked with these buttons before? They are not developer-friendly. If you have any ideas, I would love to avoid relative positioning here.
