### ISSUE TITLE
Enhancement - additional option to not display intro

### ISSUE THREAD

**Issue by softengi** [usablica/intro.js#883]
## Description
Option to let the user specify if the intro is required next time the application/page is launched.

## Expected Behavior
Additional checkbox to be displayed on intro dialog above buttons with options -
"do not display this next time on this page"
"do not display this next time on this application"

## Actual Behavior
Feature currently not available

## Environment (optional)
List browser information - Chrome,
Intro.js version - Latest,
Operating System - Windows 10,
JavaScript libraries - Angular

**Comment by jorgeitenjr** [comment]
I was also in need of this feature. I made a [PR](https://github.com/usablica/intro.js/pull/886) to this.
In the meantime you can check my repo.
