### ISSUE TITLE
Parent fixed localization problem

### ISSUE THREAD

**Issue by 948911908** [usablica/intro.js#884]
When a fixed location element is used for a parent element, that element is not displayed at the top:
![image](https://user-images.githubusercontent.com/19320137/44789243-ada9d000-abce-11e8-827d-957293809f24.png)

My solution is to use css3's mixed mix mode and modify part of the source code to achieve element area highlighting, but make sure that clicking on the highlight area will close intro
![image](https://user-images.githubusercontent.com/19320137/44789223-9ec31d80-abce-11e8-8edc-79cc511b9887.png)

If you need it, please leave a message at the bottom. I will attach the code later

**Comment by hanjeahwan** [comment]
I need too

**Comment by reebr** [comment]
Any workaround for this? I've got the same problem.

**Comment by 948911908** [comment]
@reebr I have posted my modified code above

**Comment by reebr** [comment]
Thanks @948911908.

This solves the problem of the element not being visible, but the behavior is still failing. When I click "Finish Tutorial" and open it again on the same page, the highlight goes out of the screen:

![](https://image.ibb.co/b3YUwe/asdasd.png)

**Comment by 948911908** [comment]
Yes, this is similar to a smokescreen, the actual element is still in the lower level. As for the question you mentioned, I don't quite understand it. Can you provide the code and effect @reebr

**Comment by mostafamousvi** [comment]
This problem has been fixed :+1:  . But another problem has arisen that the helperLayers are not in their own places :(
