### ISSUE TITLE
onExit callback is called twice when clicking the Skip button

### ISSUE THREAD

**Issue by miellaby** [usablica/intro.js#885]
## Description
The onExit callback is called twice when clicking the Skip button.

## Expected Behavior
The onExit callback should be called once whatever the way one exits.

## Actual Behavior
The onExit callback is called twice when one uses the Skip button (before the last step according to code).

## Errors and Screenshots (optional)
No

## Example (recommended)
Set up an exit callback writing on the console. Push the Skip button on a multi-step introduction. Check the console.

## Environment (optional)
According to code, everytime

**Comment by subasically** [comment]
After almost a year this is still an issue.

**Comment by adamcoulombe** [comment]
Thanks for sharing your patch.

I wondered, when reviewing the code in this library, why there isn’t just an exclusive done button. It’s kind of a weird approach to modify the skip button, but oh well.

**Comment by LeonBeilis** [comment]
I just notice this when using the lib for the first week.. thought at first I was doing something wrong and started google it after 20 min of debugging.. please fix this issue. using v2.9.3

**Comment by afshinm** [comment]
I will fix this in 3.0.1

**Comment by afshinm** [comment]
https://github.com/usablica/intro.js/issues/850

**Comment by afshinm** [comment]
Please install 3.0.1 and let me know if the issue is fixed. Thanks and apologies for the delay.

**Comment by jairmedeiros** [comment]
This issue still present at 10.2.0
