### ISSUE TITLE
Balloons are getting placed out of screen when the focussed element is too big.

### ISSUE THREAD

**Issue by bramsmulders** [usablica/intro.js#887]
## Description
When a highlighted element is taller then roughly 70% of the viewport height the text balloons are placed out of screen(depends on the size of the element + the content of the balloon).

## Expected Behavior
The balloon to place to another side where there is enough space. Or focus the screen to show the balloon instead of the entire element. 

## Actual Behavior
Plugin tries to center the element into the screen and places the balloon out of screen.

## Environment (optional)
Every browser basically

**Comment by VaelVictus** [comment]
I think this might be related to my bug. https://stackoverflow.com/questions/50320498/how-to-avoid-intro-js-repositioning-my-tooltip
