### ISSUE TITLE
Integration with FontAwesome SVG fails

### ISSUE THREAD

**Issue by reebr** [usablica/intro.js#888]
## Description
I'm trying to use Introjs with [FontAwesome 5][1], that have a JS to transform all `<i>` tags into `<svg>`. 
If I set `data-intro` directly in the "icon", the tutorial fails when user interact with "next" and "previous" buttons. Is this the expected behavior?

[1]:https://fontawesome.com/

## Actual Behavior
The tutorial fails and point to initial position of screen, as you can see in the image below.

## Errors and Screenshots
![behavior](https://i.imgur.com/Vknu3om.png)

## Example
I create [this snippet](https://jsfiddle.net/0m4g5aop/2/), steps to reproduce the problem:
- Press "enable" to instantiate introjs and show the tutorial.
- Press "next" button, everything works. 👍 
- Press "back" button, everything works. 👍
- Now... press "next" button again, the tooltip points to that location on image. 👎 

## Environment
- Firefox Nightly 64 (reproduced on Chrome 68 and 69 too).
- No another JS/CSS libraries and frameworks (just FontAwesome e IntroJS).
- Windows 10.

**Comment by reebr** [comment]
I'm using this workaround: wrap the icon into a inline element and put the `data-intro` on the parent element, eg:
```html
<span data-intro='Icon introduction.' data-step='2'>
  <i class='fas fa-unlock' ></i>
</span>
```
https://jsfiddle.net/7voybcne/

**Comment by davidsneighbour** [comment]
Technically speaking this is a problem with the SVG being created after the page loads. You had added an icon reference with the i-tag, but it is replaced with an SVG tag when fontawesome does its magic. I think I read on their documentation site that you can address the created SVG tag via an id-attribute, but can't find the page to link here.
