### ISSUE TITLE
Not possible to disable animation when hints are added programmatically

### ISSUE THREAD

**Issue by alex-oleshkevich** [usablica/intro.js#895]
## Description
Not possible to disable animation when hints are added programmatically

The bug is located here:
https://github.com/usablica/intro.js/blob/master/intro.js#L1833

```js
currentItem.hintAnimation = currentItem.hintAnimation || this._options.hintAnimation;
```
If `currentItem.hintAnimation` set programmatically to false, then it fallbacks to global setting value.

**Comment by evnp** [comment]
This issue still seems to be present in latest...
```javascript
      hintItem.hintAnimation =
        hintItem.hintAnimation || hint.getOption("hintAnimation");
```
https://github.com/usablica/intro.js/blob/421a2dc5ddb8db6d1b883799c6b89acd81418170/src/packages/hint/hintItem.ts#L53-L54

Passing `hintAnimation: false` when setting hints programatically trips `||` in the expression above, and the default (true) ends up being used.

We want to disable animation when the user [prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion), so this is a major accessibility issue.

(our organization is a paying customer of intro.js, fwiw)
