### ISSUE TITLE
Not showing highlighted text correctly

### ISSUE THREAD

**Issue by devWaleed** [usablica/intro.js#900]
## Description
Not showing highlighted text correctly

## Expected Behavior
To highlight dashboard or selected item

## Actual Behavior
What actually happened?
Hidden by white overlay

## Errors and Screenshots (optional)
Give us any additional information if you have.
![unable to show properly](https://user-images.githubusercontent.com/4759525/47952366-0eb7a080-df90-11e8-8442-7ad1581c1043.PNG)

## Environment (optional)
Working with VueJS. Using 'vue-introjs' with intro.js's cdn js/css links.

**Comment by wandarkaf** [comment]
Duplicate [#884](https://github.com/usablica/intro.js/issues/884). It happen to me, exactly as you describe. Maybe a PR would be nice?

**Comment by flaviomsb** [comment]
I've got exactly the same problem.

**Comment by frkn-aydn** [comment]
I have the same problem here.

**Comment by YochevedZ** [comment]
I have the same problem, any solution?

**Comment by NuijtenDev** [comment]
I've had the same problem. The solution is to create a eventlistener that starts introJS when the selected Vue componenent is loaded. This way introJS can select the element correctly.
