### ISSUE TITLE
Select an element added at runtime when intro is running

### ISSUE THREAD

**Issue by ali-codehoppers** [usablica/intro.js#903]
## Description
I am using intro.js to show help on our sites.

Sometimes we take the user to a button and we expect him to click it, once he clicks it a new element is added at run time. This new element is the selector for the next step.

However when the user goes to the next step the newly added element is not highlighted although it can be visually seen in the page.

Please note that I cannot use addStep as I have a library that fetches all the steps for a page from the server and starts intro. So I really do not know which step should be added later on.

Also the use case is such that the pages are already built in a way where elements are added at run time so making them show or hide means going back to all screens are changing the code.

## Example 
Please visit this fiddle. User will click the start intro button, then the button highlighted in the first step a new input field is added and ideally in the next step the new field should be highlighted.

https://jsfiddle.net/7aqzw0du/1/

**Comment by Neuroforge** [comment]
Did you ever solve this?

**Comment by ali-codehoppers** [comment]
Yes I did. I will take a look at it later today and let you know.

**Comment by sabatale** [comment]
@ali-codehoppers How?

**Comment by ali-codehoppers** [comment]
I guess you are still stuck. I will update you in the morning.

**Comment by demaree** [comment]
I'm also looking for a solution to this. I have a button that populates a menu. Has anyone found a fix for this?

**Comment by Yvad60** [comment]
Any solutions now?
