### ISSUE TITLE
"." is showing up in the wrong place.

### ISSUE THREAD

**Issue by Bugs5382** [usablica/intro.js#904]
## Description

I looks like the  ending "period" is showing up in the last line of the popup.

## Expected Behavior

Expecting the period to be at the end of the last sentence, not the start of it.

What did you expect to happen?

At the end.

## Actual Behavior

Start of the last "line" has the . if the "data-hint" tag includes a period at the end.

## Errors and Screenshots (optional)

![image](https://user-images.githubusercontent.com/12115015/48798301-58afbe80-ecd2-11e8-9e41-49a17691ece7.png)

![image](https://user-images.githubusercontent.com/12115015/48799652-beea1080-ecd5-11e8-8781-5fbfd6036a39.png)

## Environment (optional)

All

**Comment by bozdoz** [comment]
Someone using the RTL css?
