### ISSUE TITLE
Report bug data-step > 12

### ISSUE THREAD

**Issue by testt23** [usablica/intro.js#913]
There is a bug when you add a step greater than 12 and it just does not show up.

example:
```
<li data-step="1" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 1</li>
<li data-step="2" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 2</li>
<li data-step="3" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 3</li>
<li data-step="4" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 4</li>
<li data-step="5" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 5</li>
<li data-step="6" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 6</li>
<li data-step="7" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 7</li>
<li data-step="8" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 8</li>
<li data-step="9" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 9</li>
<li data-step="10" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 10</li>
<li data-step="11" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 11</li>
<li data-step="12" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 12</li>
<li data-step="13" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 13</li>

```

These lines will not appear.
```
<li data-step="11" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 11</li>
<li data-step="12" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 12</li>
<li data-step="13" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 13</li>
```
FireBug Console:
TypeError: lastIntroItem is undefined[Learn More]

Thanks.

Hmmm. I can solved the problem.
In file intro.js , line 1051, 1052, 1053, 1054, 1055
```
        var lastIntroItem = this._introItems[(targetElement.step - 2 >= 0 ? targetElement.step - 2 : 0)];

        if (lastIntroItem !== null && (this._direction === 'forward' && lastIntroItem.position === 'floating') || (this._direction === 'backward' && targetElement.position === 'floating')) {
          oldHelperNumberLayer.style.opacity = 0;
        }
```

change to

```
        var lastIntroItem = this._introItems[(targetElement.step - 2 >= 0 ? targetElement.step - 2 : 0)];

        if (lastIntroItem != null && (this._direction == 'forward' && lastIntroItem.position == 'floating') || (this._direction == 'backward' && targetElement.position == 'floating')) {
          oldHelperNumberLayer.style.opacity = 0;
        }
```

And problem is solved!

**Comment by sairam592** [comment]
> There is a bug when you add a step greater than 12 and it just does not show up.
> 
> example:
> 
> ```
> <li data-step="1" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 1</li>
> <li data-step="2" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 2</li>
> <li data-step="3" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 3</li>
> <li data-step="4" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 4</li>
> <li data-step="5" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 5</li>
> <li data-step="6" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 6</li>
> <li data-step="7" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 7</li>
> <li data-step="8" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 8</li>
> <li data-step="9" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 9</li>
> <li data-step="10" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 10</li>
> <li data-step="11" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 11</li>
> <li data-step="12" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 12</li>
> <li data-step="13" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 13</li>
> ```
> 
> These lines will not appear.
> 
> ```
> <li data-step="11" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 11</li>
> <li data-step="12" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 12</li>
> <li data-step="13" data-intro="<?= Module::t('ASSISTENT_HERE_EDIT_ELEMENT'); ?>" data-position='top'>asd 13</li>
> ```
> 
> FireBug Console:
> TypeError: lastIntroItem is undefined[Learn More]
> 
> Thanks.
> 
> Hmmm. I can solved the problem.
> In file intro.js , line 1051, 1052, 1053, 1054, 1055
> 
> ```
>         var lastIntroItem = this._introItems[(targetElement.step - 2 >= 0 ? targetElement.step - 2 : 0)];
> 
>         if (lastIntroItem !== null && (this._direction === 'forward' && lastIntroItem.position === 'floating') || (this._direction === 'backward' && targetElement.position === 'floating')) {
>           oldHelperNumberLayer.style.opacity = 0;
>         }
> ```
> 
> change to
> 
> ```
>         var lastIntroItem = this._introItems[(targetElement.step - 2 >= 0 ? targetElement.step - 2 : 0)];
> 
>         if (lastIntroItem != null && (this._direction == 'forward' && lastIntroItem.position == 'floating') || (this._direction == 'backward' && targetElement.position == 'floating')) {
>           oldHelperNumberLayer.style.opacity = 0;
>         }
> ```
> 
> And problem is solved!

Thank you Soo much brother <3
