### ISSUE TITLE
IntroJs has a problem with the pop-up box used for bootbox

### ISSUE THREAD

**Issue by sandheart** [usablica/intro.js#917]
Details please see：https://github.com/makeusabrew/bootbox/issues/696

1. After the appearance of the bootstrap layer, a class was added to the original shell layer: introjs-fixparent, which was occluded due to the change of z-index attribute;

2. The guide box cannot be seen clearly due to the transparency problem;

This is the contrast after modifying class (.introjs-fixparent)

![img3](https://s2.ax1x.com/2019/03/13/Ak3STP.jpg)

![img4](https://s2.ax1x.com/2019/03/13/Ak39Ff.jpg)

**Comment by NuijtenDev** [comment]
close the current guide in the main view and start a new one inside the popup. this should fix your problem

**Comment by sunteng1227** [comment]
I also encountered the same problem, have you solved it?
