### ISSUE TITLE
Element highlighting does not work in the Chrome browser

### ISSUE THREAD

**Issue by YochevedZ** [usablica/intro.js#921]
## Description
Element highlighting does not work in the Chrome browser

## Expected Behavior
Highlighting the elements works in all browsers

## Actual Behavior
Highlighting works in all browsers except Chrome

## Errors and Screenshots (optional)
Attached screenshot from Chrome vs Safari
![image](https://user-images.githubusercontent.com/41073514/55479276-65500600-5626-11e9-9671-0174211528e2.png)
![image](https://user-images.githubusercontent.com/41073514/55479285-6bde7d80-5626-11e9-8d6f-ae04c0f6b097.png)

## Example (recommended)
js:
  introJsTest() {
    let intro = introJs();
    intro.setOptions({
      steps: [
        {
          element: '#step1',
          intro: 'This is the 1st step',
          position: 'left'
        },
        {
          element: '#step2',
          intro: 'This is the 2nd step',
          position: 'left'
        }
      ]
    });
    intro.start();
  }
html:
  <ion-content>
       <p id="step1">1st step</p>
       <p id="step2">2nd step</p>
  </ion-content>

## Environment (optional)
Intro.js version = 2.9.3
Ionic environmwnt.

**Comment by greenm1nd3d** [comment]
The developer doesn't support this project anymore. Time to move on to Shepherd.

**Comment by IsmaelSANE** [comment]
Hi @YochevedZ I have kind of the same issue with chrome so how did you handle the situation ?

**Comment by YochevedZ** [comment]
@IsmaelSANE I'm now trying to work with Shepherd as @greenm1nd3d advised.
