### ISSUE TITLE
idea : hide or disable "back" and "next" button 

### ISSUE THREAD

**Issue by thieuanh1995hn** [usablica/intro.js#925]
As i told on the title . Some time with my script, user can not back to previous step. I think you can easily added this option.

**Comment by NuijtenDev** [comment]
this is a easy workaround
`            var css = document.createElement('style');
            css.type = 'text/css';
            css.innerHTML = '.introjs-skipbutton {display: none !important;}';
            document.body.appendChild(css);
`
skip button : .introjs-skipbutton

**Comment by thieuanh1995hn** [comment]
yeah but it's like a tip trick kind. Ok i's also a solution.

Vào Th 4, 15 thg 5, 2019 vào lúc 16:55 Youri Nuijten <
notifications@github.com> đã viết:

**Comment by DeveloperSlope3** [comment]
_hideNext_ & _hidePrev_ should do this, but the CSS for .introjs.hidden is overwritten by introjs-button, so it has no effect.

the CSS rule is:

`.introjs-hidden {
    display: none;
}`

I'd recommend:

`.introjs-hidden {
    visibility: hidden;
}`

in order to maintain the space
