### ISSUE TITLE
disableInteraction in options not working

### ISSUE THREAD

**Issue by DeveloperSlope3** [usablica/intro.js#935]
## Description
I want all steps disableInteraction, so I put them in the options of introJS, not as an atribute of the DOM element.

## Expected Behavior
I expect all the steps have the interaction disabled

## Actual Behavior
Nothing happens, the interaction is enabled ignoring the value I set. (as an atribute it works perfectly)

**Comment by JohnArcher** [comment]
Works for me. Maybe you should show your code.

**Comment by MrViolin** [comment]
The source code, line 186:

> if (typeof (currentElement.getAttribute('data-disable-interaction')) !== 'undefined') {
>   disableInteraction = !!currentElement.getAttribute('data-disable-interaction');
>  } else {
>   disableInteraction = this._options.disableInteraction;
>  }

DOM.getAttribute(attr), It's type will never be undefined. It will be 'null' or 'string'
You can change it like this:

> if(!currentElement.getAttribute('data-disable-interaction'))

now, the global options 'disableInteraction' can works.

**Comment by MrViolin** [comment]
The source code, line 186:

> if (typeof (currentElement.getAttribute('data-disable-interaction')) !== 'undefined') {
>   disableInteraction = !!currentElement.getAttribute('data-disable-interaction');
>  } else {
>   disableInteraction = this._options.disableInteraction;
>  }

DOM.getAttribute, It's type will never be undefined.
You can change it like this:

> if(currentElement.getAttribute('data-disable-interaction'))

now it works.
