### ISSUE TITLE
onafterchange is clearly not called after the change

### ISSUE THREAD

**Issue by AntoineWtrnd** [usablica/intro.js#936]
## Description
Have a custom Focus callback when onafterchange, it focus, but it focus before the tooltip appear, then, the focus dissapear because tooltip has not been finished to shown.

So, "onafterchange", no way. This not working. This is the same as onbeforechange. Exactly the same except some minutes delays.

Also, i can't believe all these callback without a onNext.

Bootstrap Tour look much better...

**Comment by sr9yar** [comment]
I just spent a couple of hours trying to customize my tour in firm belief 'onafterchange' is in fact called after all changes are done. 
Learnt the truth the hard way ....

**Comment by sr9yar** [comment]
I managed to [handle this by using a MutationObserver](https://stackoverflow.com/a/58408177/3298637).  

```
const observer = new MutationObserver((mutations) => {  
    const { target } = mutations[0];

    document.querySelector('.introjs-tooltip').style.top = `${      
        document.querySelector('.introjs-helperLayer').clientHeight
        - document.querySelector('.introjs-tooltip').clientHeight - 10}px`;

    return null; });

observer.observe(   
    document.querySelector('.introjs-tooltip'),     
    { attributes: true, attributeOldValue: true, attributeFilter: ['style'] }, 
);
```

Thanks for this great library. An update on this issue would be much appreciated.

**Comment by bartimez** [comment]
Also having this issue.  onafterchange is called before the tooltip location is calculated, making calling refresh in an onafterchange worthless

**Comment by xand7** [comment]
This continues to be an issue for me.
