### ISSUE TITLE
Intro Position sometimes way off (responsive design)

### ISSUE THREAD

**Issue by vermaat** [usablica/intro.js#941]
## Description
Issue with responsive design, causing the Intro.Js elements to show up at the incorrect position (only when using a big window size).

## Expected Behavior
What did you expect to happen?
IntroJS shows up nearby the targeted element

## Actual Behavior
What actually happened?
IntroJS does not always show up at the correct place. When the window width is small ( responsive design switches to mobile mode, and get's rid of side bar on the left) it shows up at the correct position (picture 1). If I switch to full width (picture 2), the same introJS is positioned at the wrong place, including the helper layer. So i guess it has something to do with CSS positioning, but I'm kind of lost where to start. 

## Errors and Screenshots (optional)
Intro.js element shows up at the correct place
<img width="493" alt="Screenshot 2019-08-12 at 18 09 09" src="https://user-images.githubusercontent.com/19154998/62861398-f1d9a600-bd35-11e9-89bb-d82478e6d475.png">

The same Intro.js element does NOT show up at the correct place. This happens when the responsive design adds the left side bar. It does not only happen when it dynamically switches, but also when the sidebar is already shown before the intro starts.
<img width="979" alt="Screenshot 2019-08-12 at 18 08 57" src="https://user-images.githubusercontent.com/19154998/62861397-f1d9a600-bd35-11e9-9d1c-3c4b5771071c.png">

Im injecting introjs attributes to the html using javascript, since the table is dynamically generated (but i dont think this has anything to do with it):
```
$(document.getElementsByClassName('tabulator-row')[1]).attr({
            "data-intro": "Busyness shizzle",
            //"data-position":"auto",
            "data-step":2
        });

var intro = introJs();          
intro.setOption("scrollToElement", false);
intro.setOption("exitOnOverlayClick", false);
intro.setOption("disableInteraction", true);
intro.setOption("overlayOpacity", 0);
intro.setOption("showStepNumbers", false);
intro.start();
```

## Example (recommended)
at www.besttime.app you can see the left side bar  as example.

## Environment (optional)
Both Safari and Chrome, using the latest Intro.js

**Comment by anan211139** [comment]
I have the same problem too.
