### ISSUE TITLE
No way to know which step is being performed,if some step not bind element

### ISSUE THREAD

**Issue by killergxm** [usablica/intro.js#954]
## Description
the change() callback is just get the bind element.But if it not have element and I performed some rollback and forward operations,I would lose the step number.

**Comment by JohnArcher** [comment]
I second that. I would like to have a second parameter for `introJs.onchange()`, `introJs.onbeforechange()` and `introJs.onafterchange()` that takes the corresponding step data in case you used the json config method.

**Comment by LeshM** [comment]
You can get the current step number, and using that get the original step data:
`
const intro = introJs({
	steps: {
		intro: 'Hello World!',
		customData: {myCustomField: 'my custom value'}
	}
});
const currentStepData = intro._options.steps[intro._currentStep];
console.log(currentStepData.customData);
// my custom value
`
