### ISSUE TITLE
Add nuw custom button

### ISSUE THREAD

**Issue by lsantaniello** [usablica/intro.js#957]
## Description
I'd like to add new custom button to tooltip area (in my Ionic App)  in order to disable tour guide in my app. Currently I enabled tour guide in 5 pages but I don't know How allow the user to disable di features. What is the action that I can use to disable the tour?

## Example
I tried to use the "skip" button catching onexit event but it is triggered on both buttons: skip and complete/done.

## Environment
Ionic 3 Application

**Comment by MUsman888** [comment]
you can apply condition like this by catching event triggered by using @HostListener
code below ==>

@HostListener('window:click', ['$event'])
  onClickEvent(e) { 
if (e.target.className.match("introjs-skipbutton") && !e.target.className.match("introjs-donebutton")) {
      this.introJS.exit();
      // do whatever you want on exit     
    }
}
