### ISSUE TITLE
How can I add a image next to tooltip?

### ISSUE THREAD

**Issue by fjuriolli** [usablica/intro.js#958]
I have something like this:
![Image of Yaktocat](https://i.imgur.com/8H4eXuN.png)

I want to add like a profile picture like the one below:
![Image of Yaktocat](https://i.imgur.com/A5DF72A.png)

I couldn't find nothing like this in the documentation.

**Comment by KumarRitwick** [comment]
I was looking for same answer but apparently it doesn't exist.

**Comment by KumarRitwick** [comment]
https://introjs.com/docs/examples/customizing/html-tooltip

Maybe this will help.
