### ISSUE TITLE
navbar fixed top, positioning issue

### ISSUE THREAD

**Issue by desduvauchelle** [usablica/intro.js#96]
Hello,

First of all, thank you very much for this amazing plugin!
I'm using Twitter bootstrap for the layout of my site and I put one of my steps in a navbar fixed top. Making the the number step cut off... (see princtscreen).

![Screen Shot 2013-04-13 at 19 22 12 ](https://f.cloud.github.com/assets/1172911/376867/b23fc674-a45e-11e2-8b81-dfecb61b1ed9.png)
Any chance we could also change the position of the step number for such cases?

Thanks,
Denis

**Comment by AhmadrezaHK** [comment]
still have the problem with position fixed parent
