### ISSUE TITLE
Highlighted element not visible

### ISSUE THREAD

**Issue by PittCaleb** [usablica/intro.js#999]
![image](https://user-images.githubusercontent.com/6013687/77937455-5aa06f00-7282-11ea-9e67-daea3c9eb413.png)
![image](https://user-images.githubusercontent.com/6013687/77937477-6429d700-7282-11ea-9113-3d900ae9ba25.png)

As you can see, when the tour runs, the selected element is not visible to the user.  This used to work, and works for about half of our tour stops.  

Fiddling with z-index (forced to 999999 !important when selected) and position, I have been unable to get this to work.  Don't see difference for when some work and why others don't.  Any thoughts greatly appreciated.

**Comment by setatime** [comment]
Check out the solution here: https://github.com/usablica/intro.js/issues/840#issuecomment-456025423
